### ISSUE TITLE
nsq_pubsub: we should make a slice by point out capacity, not length

### ISSUE THREAD

**Issue by chenqinghe** [nsqio/nsq#1013]
https://github.com/nsqio/nsq/blob/bf3e72c5623308be9458e4a709a1693e3c4cc049/apps/nsq_pubsub/nsq_pubsub.go#L55

i think the right way is 

```Go 
     n := make([]*StreamReader, 0, len(s.clients)-1)
```

am i right ? Or is there anything i did not considered?

**Comment by mreiferson** [comment]
Thanks for the tip.

You're probably right, but `nsq_pubsub` is a pretty crufty codebase that I wouldn't actually suggest using in production.

This has come up before, but we should probably remove it.

cc @jehiah

**Comment by jehiah** [comment]
I agree... `nsq_pubsub` should probably be removed.

**Comment by chenqinghe** [comment]
got it. thank you very much.
