### ISSUE TITLE
nsqd: multiple instances /stats

### ISSUE THREAD

**Issue by zeako** [nsqio/nsq#1015]
Didn't find an answer for it on github or docs.
I have two nsqd instances and one nsqlookupd.
when I pole data from /stats it seems that there is a difference between the two instances.

is the data from stats is of the instance instance or an aggregation of all instances?
how does it actually work?

also if aggregated, does running instances of different versions (v0.3.8 and v1.0.0) impact consistency?

**Comment by ploxiln** [comment]
nsqd `/stats` is not aggregated, it is just for that instance.
You can view aggregated stats with nsqadmin.

**Comment by zeako** [comment]
Thanks.
