### ISSUE TITLE
nsqd: write latency issues

### ISSUE THREAD

**Issue by nmiculinic** [nsqio/nsq#1016]
I'm experiencing high latency when writing to nsqd (in localhost). For writing to it, I'm using nsq go client, the `MultiPublish` function.  For about on average 50 msg/sec, I'm seeing 100ms latency before the write completes, while the complete data throughput is about 50kB/s. 

How can I debug this further?

It might be relevant, I'm using 12 channels in this example. (the write are sorta evenly/unevenly distributed among them. )

They are deployed on google kubernetes engine, with requests:
```
  requests:
    cpu: 50m
    memory: 100Mi
```

which is more than ample for nsqd. Here is the nsqd command I'm running:
```
command:
  - sh
args:
  - -c
  - |
    /nsqd \
    {{- range $i, $v := until (int .Values.nsq.lookupd.replicas) }}
    -lookupd-tcp-address nsqlookupd-{{$i}}.nsqlookupd:4160 \
    {{- end }}
    -mem-queue-size "50" \
    -broadcast-address $(hostname -i)
```

All topics and channels are ephemeral since I don't want any message saving -- data goes stale in couple of seconds, thus it becomes irrelevant via new data stream.

Latency is meassured via:
```go
    marshallEnd := time.Now()
    err := producer.MultiPublish(topic, msgs)
    now := time.Now()
```

EDIT: version is v1.0.0-compat:

**Comment by jeek120** [comment]
me too

**Comment by mreiferson** [comment]
@nmiculinic thanks for your question.

I would ask that you first simplify your experiment by removing kubernetes from the equation and ensure that you're experiencing the same symptoms when connecting directly.

If so, we'll gladly dig in and try to figure out if it's the client library (go-nsq) or nsqd.

**Comment by mreiferson** [comment]
Closing without additional info.
