### ISSUE TITLE
*: compiling NSQ daemons on android

### ISSUE THREAD

**Issue by sbhushan87** [nsqio/nsq#1026]
Hi,

First of all, I would like to say thank you to entire NSQ community for such awesome library. I tested this on Ubuntu OS and it worked very well.

Further on, I want to know is there any plan to support Android OS natively, It's not about binding for NSQ client. I want to run NSQ daemons on android. My use case is to distribute some sort of data mobile to mobile ( p2p over same LAN network) using some messaging platform and I personally feel NSQ is one of the top candidate in my options

Regards,
Shashi

**Comment by mreiferson** [comment]
Hi @sbhushan87, thanks for reaching out.

I feel like this is really a Golang question more than an NSQ one, I'm not too familiar with Go/Android OS compatibility. Assuming it's possible, it should just be a matter of compiling it for that os?

**Comment by ploxiln** [comment]
NSQ has been compiled and run on ARM, and golang does have an android OS target, but daemons/services are managed completely differently on Android than on a typical Unix system, I think. No one is currently working supporting that.

**Comment by sbhushan87** [comment]
Thanks @mreiferson , @ploxiln for providing clarification.

There is golang support for android with name of GOMobile, But it is at experiental stage & even doesn't support the complete set of golang packages.

I agree with @ploxiln that Android daemons are managed differently from typical Unix system.

I will think & try out more on this topic and post my findings. Thanks.

**Comment by xeoshow** [comment]
Hello @sbhushan87 ,
I also want to run nsq on android, is it possible for now and any new findings?
Thanks a lot.
