### ISSUE TITLE
nsqd: connection EOF after TLS handshake 

### ISSUE THREAD

**Issue by DoraALin** [nsqio/nsq#1027]
greetings,

Producer connections closed with EOF, after connection upgrades to TLS 。
Problem disappeared after I commented out `tlsConn.SetDeadline(time.Now().Add(5 * time.Second))` in `Client_v2`.

My guess is, read deadline is reset to heartbeat *3 in IOLoop however write deadline specified in `Client_v2.UpgradeTLS` still in effect, and connection returns EOF after that deadline

Maybe a reset of writedeadline after UpgradeTLS, or in IOLoop?

**Comment by mreiferson** [comment]
@DoraALin thanks for opening the issue! Are you interested in opening a PR?

**Comment by DoraALin** [comment]
with plearure

**Comment by mreiferson** [comment]
see https://github.com/nsqio/nsq/pull/1065#issuecomment-409380086
