### ISSUE TITLE
nsqd: message loss during topic/channel bootstrap from metadata

### ISSUE THREAD

**Issue by michaelyou** [nsqio/nsq#1031]
Hi:

I found the code start the `t.messagePump` goroutine before all the channels of the topic are created. If there are messages in the diskqueue, some of channels created later may not receive the message.

I verified it by create 10 channels and 2 messages in the diskqueue
![image](https://user-images.githubusercontent.com/8854914/39817414-aa38e682-53d0-11e8-90dc-ea9bf6419327.png)

**Comment by mreiferson** [comment]
see #1032
