### ISSUE TITLE
nsqd: infinite bad file creation

### ISSUE THREAD

**Issue by Albibek** [nsqio/nsq#1033]
Hi. 
We've met a strange bug in NSQ recently. After some unknown  condition(still invertigating on this)
the log became full of these messages:
```
May 14 22:25:16 server-name nsqd[25852]: [nsqd] 2018/05/14 22:25:16.227593 ERROR: reading from diskqueue(topic_name:channel_name) at 0 of /var/lib/nsq/topic_name:channel_name.diskqueue.88058379.dat - open /var/lib/nsq/topic_name:channel_name.diskqueue.88058379.dat: no such file or directory

May 14 22:25:16 server-name nsqd[25852]: [nsqd] 2018/05/14 22:25:16.227600 NOTICE: diskqueue(topic_name:channel_name) jump to next file and saving bad file as /var/lib/nsq/topic_name:channel_name.diskqueue.88058379.dat.bad

May 14 22:25:16 server-name nsqd[25852]: [nsqd] 2018/05/14 22:25:16.227611 ERROR: diskqueue(topic_name:channel_name) failed to rename bad diskqueue file /var/lib/nsq/topic_name:channel_name.diskqueue.88058379.dat to /var/lib/nsq/topic_name:channel_name.diskqueue.88058379.dat.bad
```

Restarting daemon hangs up. Kiilling with SIGKILL and starting again doesn't help. Deleting only `.bad` files doesn't help. Only full clean of /var/lib/nsq helps. Seen this on many servers, so filesystem problems are excluded. 

Some unchecked hypothesis, that could lead to this behaviour as recalled from chagnes we did recently:
- changing max_bytes_per_file to lower than current value
- temporarily change rights on directory so new file could not be created (at the moment of the check rights were all right)

**Comment by ploxiln** [comment]
Maybe the metadata files referred to data files that don't exist - maybe the metadata files failed to update, or the data files were lost.

**Comment by Albibek** [comment]
I'm getting this message many times repeatedly. And each one is about a file with another code. Nobody touched any of these files on disk. 
It looks more like race condition exists somewhere.

**Comment by mreiferson** [comment]
@Albibek thanks for the report. With the information you've provided, it seems far more likely that something about your environment or configuration is the issue as opposed to something within `nsqd`. Let us know if you find additional information that indicates otherwise and please re-open.
