### ISSUE TITLE
NSQ CGI

### ISSUE THREAD

**Issue by reddec** [nsqio/nsq#1035]
Good day!
I can create utility for nsq (let's call it `nsq_to_app`) that will invoke application on incoming message.
Like 'CGI', but as much simpler.

```
| nsqd | -- message --> | nsq_to_app |  -- exec --> | stdin: content |
```

Is it interesting for community?

**Comment by jehiah** [comment]
@reddec If that meets your needs I encourage you to start a github repo with such a tool. 

This doesn't sound like something we would add to the main `nsq` repository though. Thanks!
