### ISSUE TITLE
Consumer can not consume sometimes！

### ISSUE THREAD

**Issue by czh0318** [nsqio/nsq#1041]
Hi， I used nsq as one topic and three channel on consumer client. Most of time, it work fine. However, sometimes it doesn't work good on one channel.  Below is the log, topic name is credit-data-topic and channel name is risk.
```
2018/06/05 19:03:15 WRN    2 [credit-data-topic/risk] msg 09d037dccf862000 attempted 6 times, giving up
2018/06/05 19:03:15 ERR    2 [credit-data-topic/risk] (127.0.0.1:4150) IO error - write tcp 127.0.0.1:56966->127.0.0.1:4150: write: broken pipe
2018/06/05 19:03:15 ERR    2 [credit-data-topic/risk] (127.0.0.1:4150) IO error - write tcp 127.0.0.1:56966->127.0.0.1:4150: write: broken pipe
2018/06/05 19:03:15 WRN    2 [credit-data-topic/risk] (127.0.0.1:4150) delaying close, 2 outstanding messages
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) readLoop exiting
2018/06/05 19:03:15 ERR    2 [credit-data-topic/risk] (127.0.0.1:4150) IO error - write tcp 127.0.0.1:56966->127.0.0.1:4150: write: broken pipe
2018/06/05 19:03:15 ERR    2 [credit-data-topic/risk] (127.0.0.1:4150) error sending command FIN 09d037dccf862000 - write tcp 127.0.0.1:56966->127.0.0.1:4150: write: broken pipe
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) beginning close
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) breaking out of writeLoop
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) writeLoop exiting
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) finished draining, cleanup exiting
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) clean close complete
2018/06/05 19:03:15 WRN    2 [credit-data-topic/risk] there are 0 connections left alive
2018/06/05 19:03:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) re-connecting in 1m0s
2018/06/05 19:04:15 INF    2 [credit-data-topic/risk] (127.0.0.1:4150) connecting to nsqd
2018/06/05 19:04:15 WRN    2 [credit-data-topic/risk] msg 09d037dccf862000 attempted 7 times, giving up 
```
Thank you very much for your help.

**Comment by ploxiln** [comment]
It looks like you're using the `go-nsq` client library, and messages are being failed, and the consumer is getting disconnected from nsqd for some reason ... sorry but we'll need some more info to help. You might add your nsqd logs, the nsqd stats (`curl https://localhost:4151/stats`), some of your consumer application code ...

**Comment by mreiferson** [comment]
There are no known issues with message delivery with the versions of nsqd or go-nsq that you're using. It's likely something in your handler, possibly something that's taking a long time to complete or something in the environment or network configuration of where you're running these processes.

It's hard for us to debug and help these general kinds of issues. If you believe you've found a bug in nsqd or go-nsq, please re-open!

Thanks ❤️

**Comment by qianlnk** [comment]
Hi All， I also met this problem。

my version is 0.3.8

max_in_flight: 360
concurrency: 120

one time, we import 100w+ data to nsqd then the problem arise

my solution is:

reduces `max_in_flight` and `concurrency`, then it work well, but I don't know the problem

**Comment by ploxiln** [comment]
I think the problem you run into would be in the client library. My first guess is that setting concurrency equal to max_in_flight may work-around the problem. If you have follow-up information (client library version) and questions please post on the mailing list https://groups.google.com/forum/#!forum/nsq-users
