### ISSUE TITLE
I  set  "-max-heartbeat-interval"  to nsqd ,but  not come into force 

### ISSUE THREAD

**Issue by yunnian** [nsqio/nsq#1042]
my command:

`/data/nsq/bin/nsqd  --max-heartbeat-interval=2m0s --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=172.17.110.113 --data-path=/data/nsq_data`

How do I  add  heartbeat time ?  I want to add the heartbeat time  ,because my client executes too long

**Comment by yunnian** [comment]
thanks

**Comment by mreiferson** [comment]
Your client also needs to pass `heartbeat_interval` as part of its `IDENTIFY` command
