### ISSUE TITLE
get nsqd erro

### ISSUE THREAD

**Issue by pennkao** [nsqio/nsq#1052]
[nsqadmin] 2018/07/06 14:19:32.418033 ERROR: failed to get nsqd stats - Failed to query any nsqd:
[nsqadmin] 2018/07/06 14:19:32.418046 502 GET /api/counter (192.168.1.2:50437) 549.009µs

**Comment by ploxiln** [comment]
Your nsqadmin failed to contact any of your nsqd, so nsqadmin could not give a useful response for `/api/counters`. It does not say why it could not contact any nsqd. What flags / config options did you pass to nsqadmin and nsqd? Can you show more of the logs?
