### ISSUE TITLE
nsq_to_http: support for arbitrary headers

### ISSUE THREAD

**Issue by chasei** [nsqio/nsq#1054]
It would be very helpful to be able to pass HTTP headers to nsq_to_http. As of right now, I see that you can set some, such as content type, via the command, but it would be very useful to be able to pass dynamic headers. Thanks!

**Comment by alwindoss** [comment]
I want to pick this. I will add a option `--custom-headers` that accepts a comma separated key value pairs `ex: header1:value1,header2=value2`

Let me know your thoughts on this.

**Comment by mreiferson** [comment]
@alwindoss thanks! I think a flag `--custom-header` that can be specified multiple times sounds good to me.

**Comment by alwindoss** [comment]
@mreiferson thanks for your suggestion. The reason I chose --custom-header with comma separated key value pairs is because Go does not support duplicate flags. See issue https://github.com/golang/go/issues/2096

However, if you know of a way to implement it please let me know.

**Comment by ploxiln** [comment]
That's talking about multiple boolean-type flags adding up. We already enable multiple instances of a value-taking flag in a few places. For exampe, in `nsq_to_http`, the flag `--post` may be given multiple times, like `nsq_to_http --post=http://srv01.example.com/newmsg --post=http://srv02.example.com/newmsg ...`

see https://github.com/nsqio/nsq/blob/v1.1.0-rc1/apps/nsq_to_http/nsq_to_http.go#L52-L63
and https://github.com/nsqio/nsq/blob/v1.1.0-rc1/internal/app/string_array.go

**Comment by alwindoss** [comment]
Oh sorry my bad. Will try this.

**Comment by alwindoss** [comment]
Can someone point me to the documentation of nsq_to_http I don't see to find it here https://nsq.io/overview/design.html

**Comment by alwindoss** [comment]
I have raised a PR for this https://github.com/nsqio/nsq/pull/1072

**Comment by ploxiln** [comment]
There's some documentation here: https://nsq.io/components/utilities.html#nsq_to_http

source is here: https://github.com/nsqio/nsqio.github.io/blob/master/_posts/2012-09-01-utilities.md

**Comment by mreiferson** [comment]
see #1072
