### ISSUE TITLE
hi, repeated lock pair?

### ISSUE THREAD

**Issue by zydp** [nsqio/nsq#1061]
hi,i have a question about  repeated lock pair in GetTopic function in the  nsqd.go file。
i think that the second lock pair can not be reached..

````
func (n *NSQD) GetTopic(topicName string) *Topic {
	// most likely, we already have this topic, so try read lock first.
	n.RLock()
	t, ok := n.topicMap[topicName]
	n.RUnlock()
	if ok {
		return t
	}

	n.Lock()

	t, ok = n.topicMap[topicName]
	if ok {
		n.Unlock()
		return t
	}

 ...

**Comment by ploxiln** [comment]
The second `n.Lock()` is easily reached if the topic does not yet exist - but you mean the `if ok { n.Unlock()`. That would be reached if the topic was added by another client after `n.RUnlock()` and before `n.Lock()`

**Comment by zydp** [comment]
many thks
