### ISSUE TITLE
Add support for message headers

### ISSUE THREAD

**Issue by jcchavezs** [nsqio/nsq#1063]
Most of the points described in https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers#KIP-82-AddRecordHeaders-Motivation are valid for `nsq`. 

To me, the main motivation for having such headers is to propagate distributed tracing context in the message, this way, the **consumer** can continue the distributed trace started by the **producer**.

```
   Producer Tracer                                    Consumer Tracer
+------------------+                               +------------------+
| +--------------+ |     +-----------------+       | +--------------+ |
| | TraceContext |======>| Message Headers |========>| TraceContext | |
| +--------------+ |     +-----------------+       | +--------------+ |
+------------------+                               +------------------+
```

More relevant information on how message tracing happens [here](https://github.com/openzipkin/openzipkin.github.io/blob/master/pages/instrumenting.md#message-tracing).

If this can be considered as a feature I could open a PR myself drafting the interfaces.

Ping @andy-zhangtao @adriancole

**Comment by ploxiln** [comment]
Just to be clear: you *can* add message headers (in whatever format you prefer) to your messages today. For nsqd all message bodies are arbitrary binary blobs, you can use any serialization or wrapping of messages you want.

**Comment by mreiferson** [comment]
Given the points @ploxiln made about this being entirely in the user's control, I don't think this is the kind of feature that we would add. Gonna close, but thanks for reaching out!

**Comment by malcolmrebughini** [comment]
After almost 6 years, is this a decision worth revisiting? This limits the options to provide standard tooling for tracing.
