### ISSUE TITLE
nsqd: client RDY count drops to 0

### ISSUE THREAD

**Issue by dobegor** [nsqio/nsq#1069]
We're currently running NSQ in production for more than a year. 

Sometimes a consumer starts sending a RDY count of 0 and doesn't come back itself, despite the machine does not have any load on it / no running handlers. Restarting the application does help, but it might become a problem in future and isn't a proper solution.

What might be the problem?

Consumer is created this way:
```go
func (c *NSQConsumer) Subscribe(nsqConfig *nsq.Config, topic, channel string, handler nsq.Handler, concurrency int) error {
	consumer, err := nsq.NewConsumer(topic, channel, nsqConfig)
	if err != nil {
		return stacktrace.Propagate(err, "Failed to create NSQ consumer")
	}

	consumer.SetLogger(nil, nsq.LogLevelWarning)

	consumer.AddConcurrentHandlers(handler, concurrency)

	// conect to nsqlookupd if it's specified, otherwise to nsqd directly
	if len(c.Config.NSQ.NSQLookupdHost) > 0 {
		err = consumer.ConnectToNSQLookupd(fmt.Sprintf("%s:%v", c.Config.NSQ.NSQLookupdHost, c.Config.NSQ.NSQLookupdPort))
		if err != nil {
			return stacktrace.Propagate(err, "Failed to connect to nsqlookupd")
		}
	} else {
		err = consumer.ConnectToNSQD(fmt.Sprintf("%s:%v", c.Config.NSQ.NSQDHost, c.Config.NSQ.NSQDPort))
		if err != nil {
			return stacktrace.Propagate(err, "Failed to connect to nsqd")
		}
	}

	return nil
}
```

NSQ config looks like this:
```go
config := nsq.NewConfig()

	// High number to make big enough RDY number on each producer for this consumer
	// RDY = MaxInFlight / NumProducers
	config.MaxInFlight = 500

	// Poll nsqlookupd for producers each second
	config.LookupdPollInterval = 1 * time.Second

	// In case of failure (non-nil returned error) message will be requeued with the following delay:
	// min(message.Attempts * config.DefaultRequeueDelay, config.MaxRequeueDelay)
	// these parameters are tuned so that message will be eventually deleted in ~ 5 minutes
	config.DefaultRequeueDelay = 500 * time.Millisecond
	config.MaxAttempts = 20

	// Time after which NSQd will consider msessage delivired ot this consumer timed out and requeue it
	config.MsgTimeout = 30 * time.Second

	// Disable client-side backoff
	config.BackoffStrategy = &common.NSQZeroBackoffStrategy{}
```

Is there any info I should additionally provide, please ask.
Thanks.

**Comment by ploxiln** [comment]
How many nsqd does the consumer end up connecting to? (The RDY is spread across all connected nsqd.)

What does the nsqd timeouts count look like for this channel?

1 second LookupdPollInterval is rather aggressive

**Comment by mreiferson** [comment]
Also, consumer logs would be helpful

**Comment by dobegor** [comment]
@mreiferson 
I've deployed consumers yesterday with log adapters so that I can get more logs when issue reproduces again (probably during Monday - Wednesday due to highest load on these days).

@ploxiln 
There are 4 consumers and 14 producers currently, so the RDY count is 35 (in healthy state) for each consumer-producer pair. NSQD settings are all default except the `-mem-queue-size 1000`.

I'll post more info as the issue reproduces. I've wired DEBUG-level logs of NSQ consumers to our log infra so I could get more details.

**Comment by dobegor** [comment]
@mreiferson 
Sorry for a long wait.
Today the issue was reproduced on 2 machines (of 4).
I see a lot of (per each nsqd connected, i.e. worker-vtww) of messages in consumer log:
`2 [mails2/default] (worker-vtww:4150) rdy: 0 (last message received 115h41m37.726431356s)`

I do see a `2 [mails2/default] (worker-vtww:4150) heartbeat received` just a 3 seconds before.
Also there's a line: `2 [mails2/default] redistributing RDY state (in backoff and 14 conns > 1)`.

**Comment by dobegor** [comment]
@mreiferson We store production logs for 4 days and this log entry seem to be indicating the incident actually happened more than 115 hours ago. 

I’m trying to fetch older logs but that might not be successful. I’ll notify right away when (if) I find any more entries preceding the incident. 

Other than that, what are the possible causes of this?

**Comment by dobegor** [comment]
@mreiferson I may have found an issue-localized part of log after which instance stopped processing any messages: https://gist.github.com/dobegor/ee09e9688fae79845faa5b0e4abd25c4

**Comment by mreiferson** [comment]
@dobegor thanks. One other thing, if this is indeed a bug, it is almost certainly going to be an issue with `go-nsq` not `nsqd` so we should migrate this issue [over there](https://github.com/nsqio/go-nsq).

**Comment by dobegor** [comment]
@mreiferson no problem, I'll repost an issue there when / if it's confirmed as bug. Thanks!

**Comment by mreiferson** [comment]
@dobegor digging through the logs a bit, I realized that there's a misunderstanding around how _not_ to trigger backoff.

Your consumer should be using [`msg.RequeueWithoutBackoff(delay)`](https://godoc.org/github.com/nsqio/go-nsq#Message.RequeueWithoutBackoff) rather than providing a "zero backoff" strategy. While understandable why you'd have implemented it that way considering the minimal documentation, it seems like that's throwing off the RDY logic.

My suggestion is to switch your consumer to requeue without backoff and drop the zero backoff strategy and see if the problem persists. If so, please open a new issue in go-nsq.

Thanks!

**Comment by dobegor** [comment]
@mreiferson Thanks for the tip! I'll make changes and report back if the problem persists.
