### ISSUE TITLE
nsqd: docker networking, broadcast TCP and HTTP ports

### ISSUE THREAD

**Issue by heat** [nsqio/nsq#1073]
Hi folks, sory about my bad english.
I'm trying get up nsq services at containerum, at containerum the public port to services and container are random. With nsqlookupd and nsqadmin it's easy not a big trouble.
But when we try to run nsqd it's registrer ther right broadcast url but the follow ports  that nsqd register is that expose in container and not the service port random assigned with the service.
```
  |Name   | Port       | Protocol  | Link                    |   
  | http  | 24455:4150 | TCP       | x2.containerum.io:24455 |  
  | https | 14384:4151 | TCP       | x2.containerum.io:14384 |

```
In admin I got this link to node x2.containerum.io:4151 but it should be *x2.containerum.io:14384*.
I appreciate your time

**Comment by ploxiln** [comment]
This is not currently possible.

nsqd tells nsqlookupd how this nsqd can be reached like so:

```
		ci["version"] = version.Binary
		ci["tcp_port"] = n.RealTCPAddr().Port
		ci["http_port"] = n.RealHTTPAddr().Port
		ci["hostname"] = hostname
		ci["broadcast_address"] = n.getOpts().BroadcastAddress

		cmd, err := nsq.Identify(ci)
```

So you can use the `-broadcast-address` option to give nsqd a different hostname or ip address to give to nsqlookupd and thus to other clients (and nsqadmin). But you can't specify different ports than the actual ports that nsqd listens on.

I use `--net=host` when running nsqd in a docker container. Alternatively, you could pick random ports, but pass them through as the same ports, and configure nsqd to listen on those particular random ports.

**Comment by heat** [comment]
Thank you @ploxiln .
I my service docker containerum isn't possible to especify `--net`. 

>  Alternatively, you could pick random ports, but pass them through as the same ports

This will be my next shot, but could I open a PR that adds two arguments `-broadcast-tcp-port` and `-broadcast-http-port` as a optional params ?  Or we could  add some doc in docker session about how to 
 configure port foward?

**Comment by ploxiln** [comment]
I'm not really opposed to either idea.

**Comment by cloudzhou** [comment]
@ploxiln face the same question
so any pr?

**Comment by sidvenu** [comment]
I'm not sure why this feature is not given priority yet, considering this can help simplify distributed deployments on systems. @ploxiln is anyone working on this PR right now? If not, can someone from my organisation work on this feature?

**Comment by ploxiln** [comment]
No one is currently working on this. If you're thinking of just adding those two flag options, go ahead 👍 

For documentation updates, it may require some thought about where it fits best. (The website docs source are in https://github.com/nsqio/nsqio.github.io)

**Comment by ploxiln** [comment]
done in #1297
