### ISSUE TITLE
Deployment to scheduler systems

### ISSUE THREAD

**Issue by nfisher** [nsqio/nsq#1078]
Is there a prescribed deployment for scheduling systems like kubernetes and nomad? I see there’s a Docker section on the site. Wondering if there’s any particular should/should not that you would recommend for schedulers in particular.

**Comment by mreiferson** [comment]
I haven't personally deployed `nsqd` with k8s, but my recommendation would be to treat it like a stateful database, and deploy it similarly to how you would deploy that on your platform.
