### ISSUE TITLE
About message defered doubt

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [nsqio/nsq#1079]
1. if no consumer to consume message

2. producer publish a defered message if set defered = 100ms & nsqd receive defered message in `T1` moment

3.  shut down `nsqd server` server & all message save disk

4.  restart `nsqd server`

5. consumer to consume message and get defered message in `T2` moment,
It is consumed in  T2 + 100ms 

I think the defered message in T1+100ms, not T2 + 100ms

is right?

**Comment by ploxiln** [comment]
When nsqd shuts down and starts back up, it forgets all deferred timings. All messages are queued for delivery ASAP.
