### ISSUE TITLE
NSQ consumer destruction and unsubscribe

### ISSUE THREAD

**Issue by fredhuang9Street** [nsqio/nsq#1081]
hello, 
I'm so confused about some parts of NSQ when I was developing on golang, therefore, I have some questions needed for help.

1. How to unsubscribe a topic?
  I was trying to use the golang API to unsubscribe a channel from a topic, but I didn't find it. So, I send a command "/channel/delete" to the nsq server? Is there any better way or API I can use to unsubscribe?

2. How to destroy a customer when it is disconnected?
 A new customer is created every single time by using "nsq.NewConsumer()", after the customer disconnects from the nsq, will it be destroyed automatically or is there any function I have to implement?

sincerely yours, 

Fred

**Comment by fredhuang9Street** [comment]
Thanks for your response.

I have another question, every time when I use nsq.NewConsumer(topic, channel, config) to create a new consumer, do I need to do something like deconstructor to close or destroy the consumer ?

Thanks.

**Comment by Lercher** [comment]
> If you want a channel to be deleted as soon as the last consumer disconnects, you can use an ephemeral channel ...

Be warned, this has an important, documented drawback: 

> Note, a topic/channel whose name ends in the string #ephemeral will not be buffered to disk and will instead drop messages after passing the mem-queue-size.

This means for a slower consumer that messages _will_ be dropped if only the producer pushes hard enough. This is also tricky b/c in a development context you might not have many and/or quick clients for the server app in development.
