### ISSUE TITLE
Does it need to destroy a consumer when we never use it anymore

### ISSUE THREAD

**Issue by fredhuang9Street** [nsqio/nsq#1082]
hello,

May I ask every time we use NewConsumer to create a new customer, do I need to do something like deconstructor to close or destroy the consumer if I never use it anymore?

Thanks.

**Comment by ploxiln** [comment]
if using go-nsq you should use [Consumer.Stop()](https://godoc.org/github.com/nsqio/go-nsq#Consumer.Stop)
