### ISSUE TITLE
maxMsgSize error 

### ISSUE THREAD

**Issue by lougxing** [nsqio/nsq#1083]
[nsqd] 2018/09/14 11:19:30.471123 ERROR: CHANNEL(default): failed to write message to backend - invalid message write size (2139675) maxMsgSize=-2147483630
[nsqd] 2018/09/14 11:19:30.471143 ERROR: TOPIC(CloudSafeLine.CloudKill.Access) ERROR: failed to put msg(0a4b74ce7fafe000) to channel(default) - invalid message write size (2139675) maxMsgSize=-2147483630

My Nsqd version:
nsqd v1.1.0 (built w/go1.9.1)

My configution:
/usr/local/nsq/etc/nsqd.cfg
"
max_msg_size = 2147483640
"

What I Do;
From 2147483648 decrease progressively, when max_msg_size=2147480000, it's OK.
Now, I am using 2047483648.

And, I can't find the log keyword(maxMsgSize=)  source code, too.

**Comment by ploxiln** [comment]
It's from here:
https://github.com/nsqio/go-diskqueue/blob/master/diskqueue.go#L364

This is an `int32`, a signed 32-bit number. So the maximum value is `2^31 - 1`, and if you add one to that it wraps around to `- 2^31`.

It doesn't make sense to have a single message which is 2 GiB, NSQ really does not work well at all for this case, so just pick a smaller number :)

**Comment by lougxing** [comment]
3ks.

Maybe, a mistake need correct ?
**int** need change to int32.

:$ /usr/local/nsq/bin/nsqd  -h

-max-msg-size **int** 
    maximum size of a single message in bytes (default 1048576)
