### ISSUE TITLE
nsq_tail seems to buffer data -until shutdown?

### ISSUE THREAD

**Issue by dbabits** [nsqio/nsq#1084]
I publish 3 messages at a time to nsqd, while nsq_tail in another session pipes them into a sqlite database.
**Symptoms**: 
- Sometimes I get all 3 messages into that sqlite, other times it may be 2 or 1, or none at all.
- Looking at nsqadmin shows me that correct counts, and that everything is supposedely finished.
- They just don't reach the database on the other side of nsq_tail pipe
- **But**, when I do Ctrl-C on nsq_tail, all messages that were "lost" magically make it to sqlite!

This causes confusion and I spent long time trying to figure it out . 
Also, this is not specific to sqlite as I had similar experience having curl read from nsq_tail pipe.

> I tried playing with:
> -max-in-flight
> -n 
> -consumer-opt "output_buffer_timeout=1" etc

All to no avail.

Example:

> sqlite /tmp/foo.sqlite "create table t(c1);"
> 
> cat <<EOF | curl http://localhost:4151/mpub?topic=test
> message1
> message2
> message3
> EOF
> 
> nsq_tail --topic test -channel sqlite -nsqd-tcp-address localhost:4150 | sqlite /tmp/foo.sqlite '.import /dev/stdin t'
> 
> sqlite  /tmp/foo.sqlite "SELECT * FROM t;"

Version: nsq_1.1.0.linux_amd64.go1.10.3-1.1.0
Thank you very much.

**Comment by ploxiln** [comment]
`nsq_tail` writes each message with `os.Stdout.Write()`, immediately. That should not be buffered in the nsq_tail process. Is it possible that it's being buffered at the stdin of sqlite? What if you do something like:

```bash
(
    echo message1
    echo message2
    echo message3
    sleep 20
) | sqlite /tmp/foo.sqlite '.import /dev/stdin t'
```

might you see the same behavior where the sqlite db does not contain all the records until after the 20 second sleep?

**Comment by dbabits** [comment]
@ploxiln Thank you Pierce. You are very right, I do get the same behavior with your example and I now think it's about sqlite.
Here's what I think is going on:

In case of .import statement, sqlite is looking for EOF to arrive before committing the transaction.
If we: 

> echo 'a,b,c' | sqlite '.import /dev/stdin T'

 EOF happens naturally.

- But in the case when the other end of the pipe is connected to a socket, EOF never arrives(newlines don't matter), and so data never makes it to the table, until I hit Ctrl-C. 

- Upon SIGHUP(Ctrl-C),  nsq_tail properly closes it's file handles, sqlite sees EOF and commits the transaction - data magically appears in the table.

- If data in the nsq pipeline has INSERT statements instead, sqlite works differently - it looks for the terminating ';' , or an explicit COMMIT statement to commit, not EOF - and this works as expected

- So, to get it to do what I need, I would need to either have the publisher change the data format to INSERTs (best), or  do something like this:

> while read line; do
>    echo "$line" | sqlite /tmp/foo.sqlite ".import /dev/stdin t"
> done < /dev/stdin
> 

- This will work because `read `separates the input on newlines, and a new process is created for each line and EOF happens when it exits. Very inefficient, but it works.
 
All this is largely speculation, but I hope it's close.
I tried looking through sqlite's source code, but didn't spend enough time on it, so - feel free to criticize.

Thanks again for your help

**Comment by ploxiln** [comment]
you're welcome :)
