### ISSUE TITLE
Is it passible to set nsq reader on local machines and nsqlookupd/nsqd on remote machine?

### ISSUE THREAD

**Issue by katemicse** [nsqio/nsq#1091]
I have the nsq sat up with docker-compose on remote digitalocean ubuntu droplet.

 I want to set the nsq nodjs readers on my local machine, is it passible somehow?

**Comment by mreiferson** [comment]
You would specify the remote IP:PORT to connect.

**Comment by apisit** [comment]
I might be missing something but I can't seem to connect to the remote nsqlookupd 
Do I have to run it with some specific argument? I am able to access `http://[ip]:4161/nodes` fine
