### ISSUE TITLE
How to implement eventually consistent

### ISSUE THREAD

**Issue by Stephan14** [nsqio/nsq#1097]
How to implement in nsqlookup, is there some article to intrdouce this? Thank you

**Comment by ploxiln** [comment]
"eventually consistent" in this case just means that there is a delay of up to "lookupd_poll_interval" before a consumer knows that a topic exists on a new nsqd.

https://godoc.org/github.com/nsqio/go-nsq#Config
https://nsq.io/overview/design.html#simplifying-configuration-and-administration
