### ISSUE TITLE
nsqlookupd: inactive #ephemeral topics

### ISSUE THREAD

**Issue by fredhuang9Street** [nsqio/nsq#1101]
Hello, 

I would like to ask this problem that it shows "Below is a tree of Topics/Channels that are currently inactive (i.e. not produced on any nsqd in the cluster but are present in the lookup data)" in the nsqadmin lookup page when I use ephemeral topic or I delete the topic manually.

I developed by golang, and use nsq.NewConsumer to create a consumer, and then connectToNSQD.

I was wondering if I use the wrong function so that it shows the alert in lookup page, and how should I do to avoid this warning?

Thank you very much

Fred

![image](https://user-images.githubusercontent.com/30401419/47251034-9fa25e00-d45f-11e8-84f1-ec5119be34a0.png)

**Comment by fredhuang9Street** [comment]
Hello, 

I developed by golang. and there is the part of my code below,

![image](https://user-images.githubusercontent.com/30401419/48325523-071f8800-e671-11e8-865f-80a38ef20a20.png)


after connect to nsqd, 
this is the streams page.
![image](https://user-images.githubusercontent.com/30401419/48325547-21f1fc80-e671-11e8-9eeb-bbce3d060474.png)

and I disconnect it by the following code
![image](https://user-images.githubusercontent.com/30401419/48325581-4ea61400-e671-11e8-9c9a-fcaa38312c88.png)


this is the stream page after disconnection.
![image](https://user-images.githubusercontent.com/30401419/48325597-6087b700-e671-11e8-83f2-368e35f9cff6.png)

this is the lookup page after disconnection.
![image](https://user-images.githubusercontent.com/30401419/48325610-71d0c380-e671-11e8-9b7e-0eea2a312477.png)


this is the log after disconnection
![image](https://user-images.githubusercontent.com/30401419/48325620-7bf2c200-e671-11e8-9093-118ba8ef696e.png)


Please tell me if you need more information


Thanks

**Comment by mreiferson** [comment]
thanks! can you provide the command line arguments (or configuration file) to `nsqd` and `nsqadmin`?

It looks like you're connecting `nsqadmin` (and consumer) _directly_ to `nsqd`, I'd like to confirm that.

**Comment by mreiferson** [comment]
fixed in #1116, thanks for the report!
