### ISSUE TITLE
What method do you recommend to put in the message queue a total of 7625597484987 messages ?

### ISSUE THREAD

**Issue by dertin** [nsqio/nsq#1102]
Hello,

I made an application in Go lang to send the messages, but it is too slow, the other option is to use "nsq_to" I can not measure the time with this option. But delay ...

Messages are a string of 9 characters, but the problem is the total number of messages 7625597484987. all stored in a text file, separated by a line break.

Is there any way to send this amount of messages in a reasonable time?

Any ideas ?

**Comment by ploxiln** [comment]
This is a good question for the mailing list.
https://groups.google.com/d/forum/nsq-users

**Comment by ploxiln** [comment]
short answer is
  * mpub - maybe 10,000 messages at once
  * combine 1000 of these items into a single messages and process all 1000 items when processing that message

**Comment by dertin** [comment]
Hi, @ploxiln 

This is the command that I am using:
```sh
sudo nice -n -20 fastcat input.txt | sudo nice -n -20 to_nsq -topic="topic_test" -nsqd-tcp-address="127.0.0.1:4150" &
```
used the command "fastcat" is a version of the command "cat" but improved.
https://matthias-endler.de/2018/fastcat/

If it could be added that the file is sent out of 10,000 messages, it should increase performance. I guess so.

We could add the following argument:

```sh
to_nsq -mpub = "10000"
```

What you think ?
