### ISSUE TITLE
How can I set username and password for nsqadmin

### ISSUE THREAD

**Issue by YinYongTao** [nsqio/nsq#1103]

**Comment by heat** [comment]
The nsq is made to run internal and there isn't security to it.
There is no need to admin password.

**Comment by jehiah** [comment]
@YinYongTao This type of question is good for the mailing list https://groups.google.com/forum/#!forum/nsq-users

There are numerous tools designed to provide authentication for internal tools like nsqadmin; https://github.com/buzzfeed/sso, https://cloud.google.com/iap/docs/concepts-overview, etc

**Comment by YinYongTao** [comment]
@jehiah  thank you
