### ISSUE TITLE
nsqadmin static files

### ISSUE THREAD

**Issue by nanom1t** [nsqio/nsq#1106]
Hi.

How can I install nsqadmin correctly?

There is no any information about it in documentation. I've started nsqadmin process and specified the path to config file:
```
log-level = "info"
http_address = "127.0.0.1:4171"
graphite_url = ""
proxy_graphite = false
statsd_prefix = "nsq.%s"
statsd_counter_format = "stats.counters.%s.count"
statsd_gauge_format = "stats.gauges.%s"
statsd_interval = "60s"
notification_http_endpoint = ""

## nsqlookupd HTTP addresses
nsqlookupd_http_addresses = [
        "127.0.0.1:4161"
]
```
nsqadmin is located behind Nginx web server, so I'm just proxy requests to nsqadmin:
```
location ^~ /nsq {
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://127.0.0.1:4171/;
}
```
It works, but static files (css, js) are not loading:
![imageedit__3053972393](https://user-images.githubusercontent.com/6481192/48676318-aeb72180-eb6d-11e8-9b42-c0674c1c59b6.png)
Also I tried to manually build [static files](https://github.com/nsqio/nsq/tree/master/nsqadmin) and put then into static directory in my website root folder. After that static files started to load, but I get next error in browser console:
```
app_state.js:17 Uncaught ReferenceError: BASE_PATH is not defined
    at n.defaults (app_state.js:17)
    at Function.d.result (vendor.js:1)
    at n.u.Model (vendor.js:1)
    at new n (vendor.js:1)
    at Object.34.backbone (app_state.js:46)
    at c (_prelude.js:1)
    at _prelude.js:1
    at Object.44../app_state (router.js:3)
    at c (_prelude.js:1)
    at _prelude.js:1
```
Why so difficult? How to specify the path to static files(there is no any info in [documentation](https://nsq.io/components/nsqadmin.html))?

Also it would be awesome to create separate deb/rpm package for linux system and put it somewhere (for example, packagecloud.io).

Thanks

**Comment by nanom1t** [comment]
@jehiah @imsnakes @mreiferson Could you please help?

**Comment by mreiferson** [comment]
You need the `--base-path` flag added in https://github.com/nsqio/nsq/pull/856.

We have not yet issued an official release that includes this feature.

To compile `nsqadmin` yourself, refer to the [README](https://github.com/nsqio/nsq/tree/master/nsqadmin#working-locally).

**Comment by nanom1t** [comment]
Ok. When the official release with this feature will be published?
