### ISSUE TITLE
inFlightPqueue 

### ISSUE THREAD

**Issue by GYSml** [nsqio/nsq#1111]
Why should it be first in first out, or is there a special need in it?

**Comment by GYSml** [comment]
Queue shouldn't we meet first-in, first-out, or do we have special needs in it?

**Comment by SwanSpouse** [comment]
Hey old iron, inFlightPQueue is not FIFO, it's a priority queue implemented by a min heap.

这个不是小根堆实现的优先级队列吗？

**Comment by GYSml** [comment]
看懂了，谢谢您的解答，因为接触go的时间不是很长，坚持学习中，从工程中学习到很多了的知识

**Comment by SwanSpouse** [comment]
🙂 互勉~

**Comment by SwanSpouse** [comment]
You can close the issue if your problem has been solved.
如果问题解决了的话可以自己把issue关掉。
