### ISSUE TITLE
nsqd: cancel deferred messages

### ISSUE THREAD

**Issue by RussellLuo** [nsqio/nsq#1121]
Hi, is there a plan to add support for cancelling deferred messages?

**Update**

After some thought, I think maybe it's not an easy work.

If NSQD is [deployed as suggested](https://nsq.io/overview/faq.html#deployment), then it's possible for the producer to delete a deferred message by [ID](https://github.com/nsqio/nsq/blob/6d6f453306c90205b9119731e2171e53c3d42446/nsqd/message.go#L19), since the message has been produced to the same instance of NSQD.

But nowadays, many micro-services (i.e. producers of NSQD) are deployed in [kubernetes](https://kubernetes.io/), which makes it unreasonable to deploy a NSQD alongside a micro-service in each pod. One possible alternative is to deploy multiple instances of NSQD behind a load balancer, then it's hard to figure out which NSQD holds the message to be deleted without some cluster-like metadata.

Even in the suggested deployment scenario, it's impossible to delete the deferred message, which is being sent to the client (i.e. after [Channel.put](https://github.com/nsqio/nsq/blob/6d6f453306c90205b9119731e2171e53c3d42446/nsqd/channel.go#L547)) or has been sent to the client (i.e. after [protocolV2. SendMessage](https://github.com/nsqio/nsq/blob/6d6f453306c90205b9119731e2171e53c3d42446/nsqd/protocol_v2.go#L316)). But this issue is less critical for regular use-cases.

Some discussions ([here](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/16#issuecomment-115248096) and [here](https://stackoverflow.com/a/1970782/963379)) turned out to suggest us to implement the cancelling or revoking based on databases or by recording deleted messages in consumers (which is the method [Celery adopts](http://docs.celeryproject.org/en/latest/userguide/workers.html#revoke-revoking-tasks)).

Any suggestions?

**Comment by mreiferson** [comment]
Hi @RussellLuo, unfortunately no, there are no plans to support cancelling deferred messages. We suggest this be implemented outside of NSQ, e.g. if a client has enough state to tell NSQ to cancel a deferred message presumably it can just ignore the message upon redelivery.
