### ISSUE TITLE
can nsqd prevent message loss by setting --mem-queue-size = 0 ?

### ISSUE THREAD

**Issue by RifeWang** [nsqio/nsq#1142]
> the only edge case that would result in message loss is an unclean shutdown of an nsqd process. In that case, any messages that were in memory (or any buffered writes not flushed to disk) would be lost.

If I set --mem-queue-size = 0 , it means that all message will be written to disk. so it can prevent message loss in this way?

**Comment by ploxiln** [comment]
Mostly, yes. But in-flight and deferred messages will be in memory and not in the valid part of the disk queue, so those can still be lost. And nsqd is in general not optimized for this case, performance is probably not good, there may be some other complications.

What mem-queue-size=0 gets you is a reduction from thousands of queued messages being lost, to potentially only a couple, on hard-crash / power-cut.
