### ISSUE TITLE
Question: repeated message

### ISSUE THREAD

**Issue by RifeWang** [nsqio/nsq#1144]
![image](https://user-images.githubusercontent.com/20348639/53580174-01b16380-3bb6-11e9-8239-72ef42f3d634.png)
lIke the above picture, if I have three nsqd which have a same topic and channel , then I pub one message to this three nsqd , so the consumer that connected to this three nsqd will get three times for this one message, the same even consumer connect to nsqlookupd not directly to nsqd ?

**Comment by ploxiln** [comment]
Yes - one consumer could get all 3  copies of the same message, or some of the copies could be received by other consumers on the same channel. You generally only want to publish a message to one nsqd. nsqlookupd does not change how this works, just how the consumer finds all the nsqd which are relevant (which have the topic).
