### ISSUE TITLE
Is there a problem with this misjudgement?

### ISSUE THREAD

**Issue by tomener** [nsqio/nsq#1151]
https://github.com/nsqio/nsq/blob/e788b6b9eb8624813d62471218903c4e756e607e/nsqd/nsqd.go#L301

```
func readOrEmpty(fn string) ([]byte, error) {
	data, err := ioutil.ReadFile(fn)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to read metadata from %s - %s", fn, err)
		}
	}
	return data, nil
}
```

**Comment by ploxiln** [comment]
No, that's correct. `readOrEmpty()` is intended to return the file bytes if it exists, or an empty byte slice if it does not exist. If there's some other problem, besides the file not existing, for example not having permission to read the file, then that's an unexpected error we have to report and do something about.

**Comment by tomener** [comment]
Thank you. I see.
