### ISSUE TITLE
nsqd: use compress/flate or compress/zlib for deflate

### ISSUE THREAD

**Issue by andyxning** [nsqio/nsq#1152]
Currently, nsqd uses `compress/flate` to compress/decompress for deflate compression algorithm in https://github.com/nsqio/nsq/blob/master/nsqd/client_v2.go#L498-L516. However, when it comes to Python, it seem that the compatibility is broken. I.e., the output of python `zlib.compress` can not be decoded by `compress/flate`.

FYI, i have fired a issue in https://github.com/golang/go/issues/30982, and the contributor of golang said that i should use zlib instead of flate. But, for now, pynsq has use zlib to collaborate deflate compression with nsqd. 

What's the real problem?

/cc @mreiferson @ploxiln

**Comment by ploxiln** [comment]
There are pynsq integration tests that use deflate compression between a consumer and nsqd, and it works. It did take me a few minutes to confirm why. So here's what I found:

> zlib compressed data are typically written with a gzip or a zlib wrapper. The wrapper encapsulates the raw DEFLATE data by adding a header and trailer. This provides stream identification and error detection that are not provided by the raw DEFLATE data.

- https://en.wikipedia.org/wiki/Zlib#Encapsulation

> The wbits argument controls the size of the history buffer (or the “window size”) used when compressing data, and whether a header and trailer is included in the output. It can take several ranges of values:

> −9 to −15: Uses the absolute value of wbits as the window size logarithm, while producing a raw output stream with no header or trailing checksum.

- https://docs.python.org/3.5/library/zlib.html#zlib.compressobj

```
self._decompressor = zlib.decompressobj(-zlib.MAX_WBITS)
```

  - https://github.com/nsqio/pynsq/blob/master/nsq/deflate_socket.py

So, we use the python zlib module, and set the wbits option so it does not include header and footer, giving us pure deflate.

**Comment by andyxning** [comment]
@ploxiln Thanks for sharing the information! But the output of `DeflateEncoder.encode` seems to lack of a tailing of `0 0 255 255` compared with Golang's `compress/flate`.

**Comment by andyxning** [comment]
> self._decompressor = zlib.decompressobj(-zlib.MAX_WBITS)

This is used to decompress data. What i need is compressed with Python's `zlib` and decompress with Golang's `compress/flate`

**Comment by ploxiln** [comment]
yeah, the encoder is similar, the key point is the negative `wbits` to indicate no header/footer:

```python
class DeflateEncoder(object):
    def __init__(self, level):
        self._compressor = zlib.compressobj(level, zlib.DEFLATED, -zlib.MAX_WBITS)

    def encode(self, data):
        return self._compressor.compress(data) + self._compressor.flush(zlib.Z_SYNC_FLUSH)
```

**Comment by mreiferson** [comment]
I think we can close this, right?

**Comment by ploxiln** [comment]
to clarify, we tend to not do the "separate issue and PR" thing which is common in other projects, we just discuss on the PR, and then maybe revise and force-push the PR

**Comment by andyxning** [comment]
> I think we can close this, right?

@mreiferson @ploxiln No, Can you please give the above example a try to test the correctness? I have no idea that why i can not encode message in python and decompress it in Golang over socket. Many thanks.

**Comment by andyxning** [comment]
I have bypassed this by adding a new blank string encoding like this:
```go
encode = DeflateEncoder(zlib.zlib.Z_DEFAULT_COMPRESSION).encode
compressed_msg = encode(message.Body)  + encode('')
```

**Comment by andyxning** [comment]
@mreiferson @ploxiln

**Comment by ploxiln** [comment]
condensed stand-alone example of how pynsq can send deflate compressed data to nsqd:

```
$ python3 --version && seq 12300 12309 | python3 deflate_send.py 
Python 3.6.8
python raw_len=60 cmp_len=38
```

```
$ go version && go run deflate_recv.go 
go version go1.12.1 darwin/amd64
2019/03/27 22:05:45 golang raw_len=60
12300
12301
12302
12303
12304
12305
12306
12307
12308
12309
^Csignal: interrupt
```

```python
import sys
import zlib
import socket

compressor = zlib.compressobj(6, zlib.DEFLATED, -zlib.MAX_WBITS)

raw_bytes = sys.stdin.read().encode('utf-8')
cmp_bytes = compressor.compress(raw_bytes) + compressor.flush(zlib.Z_SYNC_FLUSH)

sys.stderr.write("python raw_len=%d cmp_len=%d\n" % (len(raw_bytes), len(cmp_bytes)))
sys.stderr.flush()

sock = socket.create_connection(("localhost", 1234))
sock.send(cmp_bytes)
sock.close()
```

```go
package main

import (
	"compress/flate"
	"log"
	"os"
	"net"
)

func main() {
	listener, err := net.Listen("tcp", "0.0.0.0:1234")
	if err != nil {
		log.Fatalf("ERROR: listen failed: %s\n", err)
	}
	readbuf := make([]byte, 3600)
	for {
		conn, err := listener.Accept()
		if err != nil {
			log.Fatalf("ERROR: accept failed: %s\n", err)
		}
		rdr := flate.NewReader(conn)
		n, err := rdr.Read(readbuf)
		if n > 0 {
			log.Printf("golang raw_len=%d\n", n)
			os.Stdout.Write(readbuf[:n])
		}
		if err != nil {
			log.Printf("ERROR during read: %s\n", err)
		}
		rdr.Close()
	}
}
```

**Comment by andyxning** [comment]
The reason is that i use `ioutil.ReadAll` in https://github.com/nsqio/nsq/pull/1149/files#r269846075. According to the source, it will finally invoke `bytes.ReadFrom`. Unless the underlying reader's `Read` method returns an `io.EOF`, or `ioutil.ReadAll` will invoke `Read` method on the underlying reader one more time. This will result in a non-EOF error and will finally make the decompress error. 

Big thanks to @ploxiln, you saved my life!

**Comment by ploxiln** [comment]
that does sound tricky :)

**Comment by andyxning** [comment]
@ploxiln Can you please send me a contact email or other contact info that can give you a DM in case i have some problems. :) My email: andy.xning at gmail dot com.

**Comment by andyxning** [comment]
I have updated the PR to use a proper way to detect the flate decompress error in https://github.com/nsqio/nsq/pull/1149/files#r269853251.

**Comment by ploxiln** [comment]
I'm on the nsq google group / mailing list, I think that's a good channel (and you can find my email address on my mails there). I was going to say, maybe you're in china and can't access google services ... but you have a gmail address so maybe you can?

**Comment by andyxning** [comment]
@ploxiln OK. I take a look at nsq google group or mailing list. 

> I was going to say, maybe you're in china and can't access google services ... but you have a gmail address so maybe you can?

Yes. I live in China. But i can access google services. :)
