### ISSUE TITLE
nsqlookupd: ConnectToNSQLookupd does not return error when nsqlookupd is not reachable

### ISSUE THREAD

**Issue by LordNoteworthy** [nsqio/nsq#1154]
Hello,

When trying to call ConnectToNSQLookupd, even if nsqlookupd is not reachable, the function will return nil. Is that the expected behavior ?
,
Thanks.

**Comment by ploxiln** [comment]
It looks like this question belongs in the go-nsq client library repo: https://github.com/nsqio/go-nsq/

**Comment by LordNoteworthy** [comment]
True, sorry for that, you can close the issue.
