### ISSUE TITLE
nsqd: cors is not enabled on http requests

### ISSUE THREAD

**Issue by samuelt1** [nsqio/nsq#1158]
If you make a call to nsq from a web browser like this `http://my.nsq.url.com:4151/pub?topic=mytopic` you will get `405 method not allowed`. This is because browsers ask for an options request before sending the post. That options will come back with `405 not method not allowed`. This will not happen if you send a curl to that url because curl does not bother sending an options. This makes creating a web app difficult due to the inability to directly publish messages to nsq. 
The current workaround is to front nsq with nginx and have nginx auto respond to options allowing anything.

**Comment by mreiferson** [comment]
Hi @samuelt1, thanks for your question.

You should not expect `nsqd` to have all the features necessary to be exposed directly to the internet. Instead, proxy those requests with something like `nginx`, `haproxy`, etc.
