### ISSUE TITLE
nsqd: --mem-queue-size=0 still creates memory channel

### ISSUE THREAD

**Issue by bitpeng** [nsqio/nsq#1160]
generally, we intend to save all the message in the disk-queue when set -mem-queue-size=0 option, but make(chan *Message, 0) just create a unbuffered chan which can also send/receive message as well.
the  follow figure   is my experiment test...

![image](https://user-images.githubusercontent.com/11880137/58929171-5b629480-8788-11e9-9af0-7b38ec3abfc6.png)

is it a bug?

**Comment by chainhelen** [comment]
https://github.com/nsqio/go-diskqueue/blob/master/diskqueue.go#L545

**Comment by mreiferson** [comment]
It was never intended to be a strict guarantee, so I don't personally consider it a bug, but I would be willing to consider the change in #1159.

Let's continue the discussion there? Thanks!

**Comment by bitpeng** [comment]
Thanks for your warmly, patient answer, but in my opinion it should give the user an option to have a chance to save all the messages on the disk-queue. What about you?
