### ISSUE TITLE
trouble running persistent service process

### ISSUE THREAD

**Issue by buguang01** [nsqio/nsq#1161]
In my server environment, the service shuts down automatically without any error messages. 

It has nothing to do with whether I use it or not. 

But when you get the latest source code generated service, it will automatically shut down after using it for a period of time. There was also no error message. Hope to solve this BUG

**Comment by ploxiln** [comment]
That sounds like a crash.

What operating system version are you running? What go version was used to compile nsq? You mean the nsqd process crashes, right? What is the service manager system that manages the nsqd process? Can you post any more details?

**Comment by buguang01** [comment]
CentOS Linux release 7.4.1708 (Core) 



Go 1.12.1 



Nsqd*2, nsqadmin*1, nsqlookup*1 



Nsqd 1.1.0, automatically shut down if not used 



Nsqd 1.1.1, will automatically shut down in about 10 hours

**Comment by ploxiln** [comment]
Sorry, we've never heard of anything like this, and that's still not enough information to go on.

You wrote that there was no error message - but I presume there was normal logging, and it seems to try to gracefully shut down? Can you post the logs, including a few before the shutdown starts?

**Comment by buguang01** [comment]
Sorry, I've tried many times, but there are no logs, nor logs that are normally closed, just like kill-9.

**Comment by buguang01** [comment]
What can I do to print out the information for you?

**Comment by ploxiln** [comment]
some ideas:
  * look for kernel messages with `sudo dmesg`
  * run "uname -a" and "file path/to/nsqd" and post output here
  * run nsqd under gdb

**Comment by buguang01** [comment]
Thank you. I'll try it first. I'll contact you when new information comes out.

**Comment by buguang01** [comment]
@ploxiln 


uname -a:
Linux gh-system-dev 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[dmesg.message.txt](https://github.com/nsqio/nsq/files/3275822/dmesg.message.txt)


GDB can't run in the background. When my SSH disconnects, it will stop automatically. What should I do?

**Comment by buguang01** [comment]
When I open it with gdb, I have to turn SSH on, and there is no problem. But when I use & boot, it automatically shuts down.

**Comment by ploxiln** [comment]
It sounds like, you are starting nsqd in the background by appending `$` to the end of the command line, and then logging out of the server, and then nsqd stops?

This is something that may have worked in the past, but no longer, due to the `KillUserProcesses` systemd configuration option in `/etc/systemd/logind.conf`, which by default intentionally kills any lingering processes from a user after they have logged out.

You'll need to use some process manager program which is designed to run and manage services. `systemd` (your "init system" on CentOS 7) can do it, but you need to figure out how to write a "systemd service unit file". Looking at #761 may help. Or, if you happen to have docker installed on the server, docker runs and manages the containers under it, so this is a common way that the nsqd process is managed (inside a container). In the past I've used yet other systems, like sysvinit or daemontools, or the "screen" utility (but that may not work anymore due to systemd `KillUserProcesses`).

**Comment by buguang01** [comment]
Before starting nsq, I entered the following command: 



Export GOTRACEBACK = crash 



Ulimit-c unlimited 



Then start up, thinking that you can generate core files when an exception occurs in nsq, but it still doesn't happen. 



Another strange phenomenon is that when I work in the company during the day, the NSQ can work properly (using many ways to turn it on). 



But when I got home from work, after 22 p.m., NSQ began to shut down frequently, which made me wonder when it did not generate core files. So I don't know what happened to it. Can you help me generate an executable that can be used to look up files?

**Comment by buguang01** [comment]
Add some error capture, etc.

**Comment by ploxiln** [comment]
If the process is getting `SIGKILL` (signal number 9) for some reason, then it won't coredump, and I don't think it can be configured to do so. I think the cause is the operating system cleaning up according to some policy, not nsqd.

**Comment by buguang01** [comment]
![image](https://user-images.githubusercontent.com/48193468/59545827-fad91180-8f56-11e9-80e4-b07730ab5e33.png)
/etc/systemd/logind.conf
After using screen, NSQ was not automatically shut down last night. 



I also checked the configuration, as shown above; it seems right. 



It's a strange question.

**Comment by ploxiln** [comment]
Using `screen` (if not a full service manager) is a good idea. If trying to do it without screen, I think that something like this might be needed ("disown" is a bash built-in):

```sh
nsqd --various-options </dev/null >/some/log/file.log 2>&1 &
disown %1
```

**Comment by buguang01** [comment]
谢谢你

**Comment by judwhite** [comment]
`nohup` is also an option if you don't want to write a systemd service file, but really you should write the systemd file if you want it to restart on reboot and be able to nicely start/stop nsqd. @ploxiln This question looks answered to me.
