### ISSUE TITLE
 failed to coerce 2 for LogLevel (2)

### ISSUE THREAD

**Issue by luobangkui** [nsqio/nsq#1164]
Hello, I can`t run the binary file after build, something like this occured

```
 build git:(master) ✗ ./nsqlookupd 
2019/06/19 18:49:30 ERROR: option resolution failed to coerce 2 for LogLevel (2) - invalid value type lg.LogLevel
```

**Comment by mreiferson** [comment]
Hi @luobangkui, are you using go "modules" to build the binaries yourself? It looks like that error would come from an older version of the [`go-options`](https://github.com/mreiferson/go-options) dependency. Try updating that and see what happens (or just use go modules).

**Comment by luobangkui** [comment]
Thanks ,it`s done
