### ISSUE TITLE
Request nsqd stats, But Connection reset by peer

### ISSUE THREAD

**Issue by zxl777** [nsqio/nsq#1167]
xxx.xxx.xxx.xxx points to my local development machine, the port exposed through NAT.

**From us remote server**:
wget  http://xxx.xxx.xxx.xxx:4151/stats?format=json

--2019-07-11 08:25:58--  (try:20)  http://xxx.xxx.xxx.xxx:4151/stats?format=json
Connecting to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx)|xxx.xxx.xxx.xxx|:4151... connected.
HTTP request sent, awaiting response... **Read error (Connection reset by peer) in headers.
Giving up.**

PING xxx.xxx.xxx.xxx 56(84) bytes of data.
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=1 ttl=52 **time=197 ms**
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=2 ttl=52 time=196 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=3 ttl=52 time=198 ms

**From local connect by 4G:**
wget  http://v86.ddns.us:4151/stats?format=json
--2019-07-11 20:28:05--  http://xxx.xxx.xxx.xxx:4151/stats?format=json
Resolving xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx)... xxx.xxx.xxx.xxx
Connecting to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx)|xxx.xxx.xxx.xxx|:4151... connected.
HTTP request sent, awaiting response... 200 OK
Length: 283 [application/json]
Saving to: ‘stats?format=json.5’

stats?format=json.5                                 100%[===================================================================================================================>]     283  --.-KB/s    in 0s

2019-07-11 20:28:05 (19.3 MB/s) - ‘stats?format=json.5’ saved [283/283]

PING xxx.xxx.xxx.xxx 56(84) bytes of data.
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=1 ttl=52 **time=5 ms**
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=2 ttl=52 time=5 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=3 ttl=52 time=3 ms

It seems that a high latency visit will cause this problem（Connection reset by peer）.

**Comment by ploxiln** [comment]
That'll be your nat/firewall/security appliance somehow.

I happen to have a couple of servers across the world from each other:

```
pierce@web81:~$ ping circle-cloudbox.st-av.com
PING ec2-54-174-202-24.compute-1.amazonaws.com (54.174.202.24) 56(84) bytes of data.
64 bytes from ec2-54-174-202-24.compute-1.amazonaws.com (54.174.202.24): icmp_seq=1 ttl=29 time=226 ms
64 bytes from ec2-54-174-202-24.compute-1.amazonaws.com (54.174.202.24): icmp_seq=2 ttl=29 time=226 ms
...
--- ec2-54-174-202-24.compute-1.amazonaws.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7001ms
rtt min/avg/max/mdev = 226.323/226.358/226.422/0.029 ms

pierce@web81:~$ wget http://circle-cloudbox.st-av.com:8120/stats?format=json
--2019-07-11 19:25:35--  http://circle-cloudbox.st-av.com:8120/stats?format=json
Resolving circle-cloudbox.st-av.com (circle-cloudbox.st-av.com)... 54.174.202.24
Connecting to circle-cloudbox.st-av.com (circle-cloudbox.st-av.com)|54.174.202.24|:8120... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘stats?format=json’

stats?format=json                                 [ <=>                                                                                              ]   5.47K  --.-KB/s    in 0s      

2019-07-11 19:25:36 (291 MB/s) - ‘stats?format=json’ saved [5597]

```

**Comment by zxl777** [comment]
@ploxiln Thank for reply.

I was also initially suspected of the Firewall and NAT settings, so I also debugged an afternoon, but did not succeed. The same Firewall and NAT work fine for other services.

The network situation is complicated, I still can't find the root of the problem.

I just want to be able to access NSQD communication locally.
My client on the local development machine is connected to the remote NSQD, and everything is fine now.
Just for development, is there a problem?

I saw in the documentation that the producer is best to configure an NSQD locally. What is the purpose?

Thank you.

**Comment by ploxiln** [comment]
Retries, backoff, and queueing are built-in to the client libraries for consumers connection to nsqd. But these features are not really provided for producers (though you could implement them on your own). The topology that works best is to run nsqd next to the producer so that this link pretty much never fails (unless the producer is also failing anyway), and then have the longer and more tenuous connections between the consumers and nsqd, where timeouts and retries and backoff are all provided automatically.

**Comment by zxl777** [comment]
Thank you for your answer.

I understand.
