### ISSUE TITLE
hash channel

### ISSUE THREAD

**Issue by lingfan** [nsqio/nsq#1171]
can support the "msg hash to channel"

**Comment by lingfan** [comment]
`
if (t.hash) {
_i := client.ID%len(chans)

for i, channel := range chans {
     if _i != i {
      continue
    }
}
}

`

**Comment by lingfan** [comment]
if (t.hash) {
    _i := client.ID%len(chans)
    
    for i, channel := range chans {
        if _i != i {
            continue
        }
    }
}

**Comment by andyxning** [comment]
Can you describe the user scenario in detail?

**Comment by lingfan** [comment]
A topic receives data hash to different subchannels

A user's logical computing services perform distributed operations on the same queue

in the mutli logic game  server

**Comment by andyxning** [comment]
IIUC, you want some kind of partition in Kafka, right?

**Comment by andyxning** [comment]
You want hash based on message id or other message field?

**Comment by lingfan** [comment]
yes,  kafka don't has this

**Comment by lingfan** [comment]
yes

**Comment by lingfan** [comment]
yes  ![image](https://user-images.githubusercontent.com/455872/62213755-3bd99800-b3d6-11e9-816a-9431c0491d04.png)

**Comment by ploxiln** [comment]
What NSQ offers which is most similar to what you request, is a single topic with a single channel, and then the messages are distributed among the consumers. They are distributed in a semi-random way between consumers, sort of like round-robin. It is not deterministic, and also it can be at very different rates, if different consumers are able to consume messages at different rates.

If you really want to use a hash function, you could do this by writing a simple consumer that consumes the original topic (on one channel), and then re-publishes messages to a set of other topics. For  example, if you want to use a hash to distribute between 4 channels, you could have this consumer read from topic-name/one-channel and publish to topic-name-1, topic-name-2, topic-name-3, or topic-name-4 depending on the message id, or whatever property of the message you want. Then you would have the working consumers connect to topic-name-1/one-channel, or topic-name-2/one-channel, etc.

You're describing a mechanism, but not what you are trying to achieve that nsq does not currently do. You probably just want to connect consumers to a channel, messages will be distributed among them. If you really just want kafka, just use kafka.

**Comment by lingfan** [comment]
now i use hash to topic-N , I wrote a middleware myself to do hash management.

thx
