### ISSUE TITLE
NSQ disk space reduction

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nsqio/nsq#1175]
Recently my NSQ server was throwing errors. And when looking into the reason I found out that the disk space was full. The disk had 10 GB size and up to 8.5 GB was utilized. Found an orphan channel for one of the topic. Since there are no readers associated with it still it was receiving messages and I think it caused the issue. Do the processed messages already removed?  Is there any other way of preventing something like this happen. Also if there is any other way to remove the orphan channels of a particular topic? Any help or recommendation appreciated.  I am using NSQ along with nsqjs.

**Comment by ploxiln** [comment]
Ephemeral channels will be deleted when they no longer have consumers. But you probably don't want to use ephemeral channels because they will be deleted if all consumers are disconnected only temporarily.

For production environments we typically have an automated monitor for all nsqd instances, and alert if any topic or channel queue depth is over a threshold, e.g. 30,000 messages. (And we usually have custom threshold for specific topic:channel)

**Comment by sujeshthekkepatt** [comment]
Does that include in nsq? Is there anything like that inbuilt to nsq? I think it's a good one. So that we can manually delete or check such channels. Any info @ploxiln

**Comment by ploxiln** [comment]
Ephemeral channels are an NSQ feature, and nsqadmin has delete buttons for channels.

NSQ is not itself a monitoring system. For this you would use nagios or icinga or sensu or maybe even datadog ... this would be the system you are already using to alert you when servers are running out of memory or disk space for other reasons, or your other services have crashed, etc.

**Comment by sujeshthekkepatt** [comment]
Hey, @ploxiln  thanks for the reply. Currently, I am not using any third-party monitoring services other than the one provided by the cloud provider. In this case, I want to know specifically about nsqio server which runs on a container in the VM. I want to know each time when a channel depth threshold goes up a number like 30000. I can query for stats of nsq and loop over the channels and check if the depth over the threshold. Is that a good method? Or Is there any other preferable way?

**Comment by ploxiln** [comment]
Yes, that's a good way to do it. Get stats from nsqd in json, loop over all channels, alert if any have too high queue depth.

**Comment by sujeshthekkepatt** [comment]
Thanks @ploxiln
