### ISSUE TITLE
How to receive messages in random order instead of published order

### ISSUE THREAD

**Issue by apmcodes** [nsqio/nsq#1182]
Currently messages are received in order of publishing and recently published messages are waiting to be received while older messages are completed. We have a requirement of receiving messages in random order. Read the docs but could not find any option. 

Is it possible?

**Comment by dudleycarr** [comment]
There's no option to force messages delivered in a random order. Imagine a topic receives only one message a minute, what would you expect to have happen with a random order option? Would you expect nsqd to wait for 10 minutes before it provided a message randomly? 

If it's really important to randomize messages, you could have a consumer that buffers messages, and then re-publishes to a new topic in a random order provided they arrive within a certain window.

**Comment by ploxiln** [comment]
another idea is deferred-publish, with random deferred time between 0 and your desired max

**Comment by judwhite** [comment]
If this is for testing out-of-order messages produce the same results you could use `to_nsq` with a randomized order of messages. I'd probably mock the server in the test code instead of using a real instance of nsqd, there are examples [here](https://github.com/nsqio/go-nsq/blob/61f49c096d0d767be61e4de06f724e1cb5fd85d7/mock_test.go#L39). @apmcodes What's your use case for random order?

**Comment by apmcodes** [comment]
Thank you for the suggestions. 

Our use case is usual task queue. Single publisher pushes tasks to a topic/ channel with multiple (8) consumers, tasks take few millisec to finish, and aim to complete them as quick as possible. But these tasks belongs to different (grouped by) jobs. For each job there can be up to a million tasks and at a time there can be tasks for up to 100 jobs. 

Publisher publishes tasks belonging to a single job at a time and then moves on to next job. So in Nsq the tasks belonging to different jobs are ordered after each other.

As consumers recieve messages (mostly) in order, tasks belonging to later jobs has to wait for older jobs to get completed/ consumed. In effect, the end users see considerable delay in starting their job and it appears as though the systems is lagging or hanging. 

Currently im trying to recieve batches of upto 500 tasks by each consumer, so that oldest task gets completed as soon as possible. But still as system scales the delay in starting recently added tasks is visible to the end user.

So was thinking if nsq could deliver messages out of order all users could see some progress in their respective job instead of waiting for other users job to get completed. 

Is this typical task queue problem (not exactly a problem) or could something be done. Scaling consumers is one way.

**Comment by ploxiln** [comment]
OK, here's an idea for your use case: have 100 instances of nsqd. Publish all 1000000 messages for a job to one nsqd, then for the next job move on to the next nsqd, in a round-robin manner. You could put all nsqd on a single server, but using separate sets of ports: 41201/4202, 4211/4212, 4221/4222, 4231/4232, etc. Maybe you have 5 publishing servers so each has 20 nsqd on separate ports - you get the idea.

If consumers (possibly on other servers) have max-in-flight greater than the number of nsqd which have the topic, then consumers are able to spread their max-in-flight aka "ready-count" roughly equally across all those nsqd, and you will see that all nsqd's queues for that topic/channel are consumed from roughly equally by consumers.
