### ISSUE TITLE
NSQ Setup Auth server

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nsqio/nsq#1183]
I am trying to figure out auth using nsq. The clients  (nsqjs) are only able to connect to the nsqd using the Auth server only but still, a simple curl can create topics and delete topics since these are not going through the auth server. What might be the possible cause? Any help appreciated

**Comment by jehiah** [comment]
quoting https://nsq.io/components/nsqd.html#auth

> NOTE: It is expected when using authorization that only the nsqd TCP protocol is exposed to external clients, not the HTTP(S) endpoints. See the note below about exposing stats and lookup to clients with auth.

Simply put, `nsqd` itself doesn't use the AUTH protocol to secure the administrative endpoints; If you want to do that you can build your own authentication layer that proxies to the http endpoints ([`nsq-contrib`](https://github.com/jehiah/nsqauth-contrib#nsqauthfilter) has a program `nsqauthfilter` which is one such implementation).
