### ISSUE TITLE
nsqauth [question]: About implementing authq  server in nodejs

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nsqio/nsq#1184]
Hai I am trying to implement auth server in nodejs specific to use internally along with our stack. I checked the python implementation. So what I am about to do is summarised below. Please take a look and give some feedback.

 1. A nodejs listens on some port accepting requests at /auth endpoint as described in the doc.
2. All readers and writers will connect using a JWT token as authSecret. Which will contain the identity and some other parameters fo ensuring the validity of the request.
3. Upon successful auth it will return the response in JSON format which contains the permissions as specified in the auth doc. We don't want any TLS support so that will be a do it later feature.

Is there something I am missing? Or Is there anything that I should consider for improvement? Any info appreciated. @jehiah @ploxiln

**Comment by ploxiln** [comment]
That all sounds good to me.

Just as a bit of clarification: The readers and writers connect to nsqd, and nsqd makes requests to the auth service. Your arrangement probably is, or could be, such that the auth service is closer to nsqd than the readers/writers are. Copies/instances of the auth service could be run on each server that runs nsqd, or in each cluster or pod with nsqd, etc. So you may not really need TLS between nsqd and the auth service, but you'll eventually want TLS between the readers/writers and nsqd.

**Comment by sujeshthekkepatt** [comment]
Yep. Currently I have only one instance of nsq are running in docker. So the auth service 
will also be running   in that container/instance. Or we can move it out separate fo maintaining. When the auth service up , I can remove or proxy the http api  to go through the auth service. So the above mentioned steps are a good to go, right? @ploxiln

**Comment by ploxiln** [comment]
Correct, the TCP protocol on nsqd (default port 4150) has auth checked by nsqd, but the HTTP protocol on nsqd (default port 4151) is not checked by nsqd, because it is expected to be easy to block direct access to that and proxy through something else for the HTTP auth.

**Comment by sujeshthekkepatt** [comment]
Thanks for the info @ploxiln
