### ISSUE TITLE
Cleaning up corrupt (.bad) files

### ISSUE THREAD

**Issue by bandesz** [nsqio/nsq#1187]
If there are corrupt .bad files in the data directory what is the correct process to clean them up? In our case we don't need to restore the data.

I couldn't find anything about this, sorry if it was asked already elsewhere.

**Comment by ploxiln** [comment]
If you don't want to try to recover them, just delete them, e.g. `rm *.bad`

There isn't any kind of easy or straightforward way to recover data from them, they're put aside for you just in case you want to try. The only place to look for more details is the code: https://github.com/nsqio/go-diskqueue/blob/master/diskqueue.go#L554

**Comment by bandesz** [comment]
And what should I do with the `.meta.dat` file? That will still show the number of messages wrong until the channel is overflow again and the file is corrected?

**Comment by ploxiln** [comment]
The metadata should be updated to skip over the files which are skipped and renamed ".bad". The metadata should show the correct number of messages.

For example, here is a metadata file contents which shows zero messages in the disk queue:

```
0
0,46347
0,46347
```

(that's depth, read position file/byte, write position file/byte)

**Comment by bandesz** [comment]
After the files were marked bad the metadata still has the previous message count and the positions are not resetted, e.g.:
```
376793
2239,0
2239,0
```
Should I just edit this file (or even delete it) and NSQ will pick up the change when it needs to write to the disk again? Currently the corrupted channels don't have anything on disk.

We are still using 1.0.0-compat but I failed to find anything relevant in the changelogs.

**Comment by bandesz** [comment]
I just realised I can call `/channel/empty` to fix these easily.

**Comment by ploxiln** [comment]
That metadata file appears to be messed up. There is probably a bug in some error-handling corner cases - this would be in https://github.com/nsqio/go-diskqueue/

Anyway, I'm glad you found an easy work-around.

**Comment by bandesz** [comment]
Thanks for the answers. I think anyone who will have the same question will find the solution here, so I'm happy to close the issue.
