### ISSUE TITLE
Using vulnerable version of handlebars library

### ISSUE THREAD

**Issue by avtrifanov** [nsqio/nsq#1188]
It seems that nsqadmin uses vulnerable version of handlebars library [package-lock.json](https://github.com/nsqio/nsq/blob/master/nsqadmin/package-lock.json#L2698)
The handlebars 4.0.11 is vulnerable for [prototype pollution](https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183) and should be updated up to 4.0.14.

**Comment by ploxiln** [comment]
thanks for the report
