### ISSUE TITLE
failed to instantiate nsqd - failed to build TLS config - open : no such file or directory

### ISSUE THREAD

**Issue by u007** [nsqio/nsq#1194]
i follow the same docker-compose.yml and having this command:

```
command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --tls-cert=/etc/ssl/certs/cert.pem and --tls-key=/etc/ssl/certs/key.pem --tls-min-version=1.1 --tls-required=true --data-path=/data --mem-queue-size=500
```
i have alreadybinded ./certs/:/etc/ssl/certs/

and it keep returning

```
nsqd_1        | [nsqd] 2019/09/29 17:54:20.877476 FATAL: failed to instantiate nsqd - failed to build TLS config - open : no such file or directory
```

if i change the file name to something that does not exists, then it will show the file path,
and still with the same error

**Comment by ploxiln** [comment]
The problem is the word "and"

> `... --tls-cert=/etc/ssl/certs/cert.pem and --tls-key=/etc/ssl/certs/key.pem --tls-min-version=1.1`
