### ISSUE TITLE
Question about docker data volume and diskqueue.

### ISSUE THREAD

**Issue by wadamek65** [nsqio/nsq#1196]
My goal is to have nsqd preserve all messages on container restarts/machine shutdowns by creating a volume to a directory with the diskqueue. Of course I run the container with flag `--mem-queue-size=0` to save all messages to the diskqueue, but messages were not persisting.

After looking around in the source code, I've figured out that the directory onto which the diskqueue doesn't seem to have a proper default value. And sure enough after adding `--data-path=/data` while running the container, the diskqueue was properly saved there and the messages were persisting between restarts.

Now my question is, what is the desired behaviour? Is it safe to set the `data-path` to `/data` or should I create my own custom image based on nsq and create a new directory for diskqueue which then I should bind to a volume? I could not find anything about it in the documentation, so if I missed anything a link is appreciated.

**Comment by ploxiln** [comment]
You are expected to specify the `--data-path`.

The nsqd default data-path is the current working directory. We didn't really think this through for the Dockerfile and docker image we provide - it looks like it uses the default docker container current-working-directory of `/`, so I guess the diskqueue and metadata end up in `/` by default. I don't think we would change the nsqd default data-path, but we could adjust the current-working-directory in the docker image to `/data`, and that would make nsqd by default put its files in there.

**Comment by wadamek65** [comment]
Thanks, it was kinda confusing since you expose the `/data` directory as a volume but I haven't seen any evidence of anything being stored there, that's why it confused me.

So to summarise, is it safe for me to set the `--data-path` to `/data` and bind the volume to host to make the diskqueue persistent?

I think changing the working directory in docker image to `/data` is the best solution. That or at least a little bit documentation on why this directory is exposed and what you can do with it.

**Comment by ploxiln** [comment]
Yes, set `--data-path=/data` and bind-mount that to the host.

**Comment by wadamek65** [comment]
Thank you for your answers. All my questions have been answered so feel free to close the issue.
