### ISSUE TITLE
nsq_to_s3: Is there a plan to develop?

### ISSUE THREAD

**Issue by GStones** [nsqio/nsq#1201]
![image](https://user-images.githubusercontent.com/6346542/67449782-e405a280-f64d-11e9-98da-2a9f006a9d21.png)
We want to archive our data to `AWS s3`, we use `plan 1` to upload our data to s3. but i think `plan 2` is better.  
So is there a plan to develop `nsq_to_s3`?

**Comment by ploxiln** [comment]
Yes, "Plan 1" is what is generally done. There are no plans to develop an `nsq_to_s3`. I think that would be fine as a separate project though (due to the likely dependency on an aws library). We would even link to it somewhere :)

**Comment by GStones** [comment]
Thanks for reply.
Maybe we can put `nsq_to_file` and `s3-upload` together in a pod in k8s cluster, It's same as `nsq_to_s3` .
