### ISSUE TITLE
reader connect error

### ISSUE THREAD

**Issue by Darkera524** [nsqio/nsq#1210]
There's a wired problem that when I start the reader on the host that nsq started on, everything  works fine and I can read the info from the channel. But when I start the reader on the other host, the following warning occur and the consumer register failed.
```
WARNING:tornado.general:Connect error on fd 10: [Errno -2] Name or service not known
WARNING:nsq.reader:[facedb-upstream:4150:test:upstream_app] connection closed
```

Is there some advices to solve the problem? thx

**Comment by Darkera524** [comment]
I'm using pynsq

**Comment by ploxiln** [comment]
the hostname `facedb-upstream` is not known to that other host

**Comment by Darkera524** [comment]
thx, I rewrite the /etc/hosts and everything works fine
