### ISSUE TITLE
depth of channel showing in nsqadmin increasing fast when producer send message to same topic via different nsqd

### ISSUE THREAD

**Issue by hoozecn** [nsqio/nsq#1213]
I play with nsqd a little bit and met the prob mentioned in the title. But when I send message via single nsqd, there is no such prob. Does this mean message should always be sent via same nsqd?

Here is my project. https://github.com/hoozecn/nsqd-cluster

**Comment by ploxiln** [comment]
I think you just need to set a higher `MaxInFlight` in the consumer config. The default is 1 - the consumer will only accept messages from one nsqd at a time, and it may not switch between nsqd often enough for you. If you set it to 4, and there are two nsqd which have a topic, the consumer will be able to receive 2 messages from each, concurrently.

**Comment by hoozecn** [comment]
@ploxiln wow. It works like a charm. Thanks for your help~
