### ISSUE TITLE
Did i use snappy=true to use compress? But no effects

### ISSUE THREAD

**Issue by cossbow** [nsqio/nsq#1214]
I read "github.com/nsqio/go-nsq", it really use "github.com/golang/snappy" upgrading Reader and Writer, then i print file on disk and see original data, never compressed.
How can i store the compressed data ?

**Comment by ploxiln** [comment]
The snappy compression option applies just to the connection between nsqd and the consumer. The message is de-compressed before being passed to your handler function.

**Comment by cossbow** [comment]
em~~Still expecting snappy feature like kafka, save  compressed data. 
Thanks!

**Comment by ploxiln** [comment]
You can compress the message yourself. For more efficiency, you could disable the nsq snappy compression, and have the producer compress the message body however you like, so the message body remains compressed just once through the entire pipeline. NSQ does not care about the format of the message body, it can be anything, thus you can compress it however you like.

NSQ is not kafka, it does not work the same way, it will not have the same options.

**Comment by mreiferson** [comment]
see discussion in #1149, too
