### ISSUE TITLE
How do I determine if a service is NSQD or Lookupd from a given address?

### ISSUE THREAD

**Issue by edoger** [nsqio/nsq#1215]
For example: 10.10.10.10:9999, it may be the HTTP service address of NSQD, or it may be the HTTP service address of Lookupd. How should I determine which one?

**Comment by edoger** [comment]
It seems to be distinguishable through the /stats interface. Is there a better solution?

**Comment by ploxiln** [comment]
We pretty much always use different ports for each.

A slightly more minimal way to differentiate would be with a request to `/info` - nsqd includes `broadcast_address` and `start_time` in the response but nsqlookupd does not.

**Comment by edoger** [comment]
@ploxiln  thanks. this is much more convenient.
