### ISSUE TITLE
nsqadmin: failed to query any nsqd

### ISSUE THREAD

**Issue by bethebest** [nsqio/nsq#1224]
when load http://localhost:4171/topics/test result in next question

UPSTREAM_ERROR: Failed to query any nsqd: Get http://SunnydeMacBook-Pro.local:4151/stats?format=json&topic=test&include_clients=false: dial tcp: i/o timeout

how to resolve

**Comment by ploxiln** [comment]
nsqd reported its broadcast-address as "SunnydeMacBook-Pro.local" to nsqlookupd, and nsqadmin got that from nsqlookupd, but then nsqadmin can't seem to connect to that hostname on port 4151. You can configure nsqd to report a broadcast address which works, perhaps "127.0.0.1", like `nsqd --broadcast-address=127.0.0.1`
