### ISSUE TITLE
nsqlookupd: confusing log message

### ISSUE THREAD

**Issue by jinq0123** [nsqio/nsq#1236]
```
[nsqlookupd] 2020/02/18 19:11:43.472975 INFO: TCP: new client(127.0.0.1:14204)
[nsqlookupd] 2020/02/18 19:11:43.473293 INFO: CLIENT(127.0.0.1:14204): desired protocol magic 'GET '
[nsqlookupd] 2020/02/18 19:11:43.473354 ERROR: client(127.0.0.1:14204) bad protocol magic 'GET '
```
The desired protocol magic should be  `'  V1'`.

**Comment by ploxiln** [comment]
I suppose that log message is unclear... what it means is:

  * client is requesting protocol 'GET'
  *  hmm ... I don't know protocol 'GET'
  * (not mentioning that the only recognized protocol is 'V2')
