### ISSUE TITLE
Question: what unit of time is E2eProcessingLatency?

### ISSUE THREAD

**Issue by Integralist** [nsqio/nsq#1241]
Datadog doesn't recognize the following metrics:

- `nsq.channel.e2e_processing_latency_95`
- `nsq.topic.e2e_processing_latency_95`

So it reports the values as (for example) `41.44G` rather than as some form of time based unit like a second, millisecond, microsecond or nanosecond.

Could someone advise what the unit of time is expected to be.

Thanks!

**Comment by alpaker** [comment]
I believe the latencies are reported in [nanoseconds](https://github.com/nsqio/nsq/blob/master/internal/quantile/quantile.go#L74):
```
func (q *Quantile) Insert(msgStartTime int64) {
	q.Lock()

	now := time.Now()
	for q.IsDataStale(now) {
		q.moveWindow()
	}

	q.currentStream.Insert(float64(now.UnixNano() - msgStartTime))
	q.Unlock()
}
```

**Comment by Integralist** [comment]
Aha! Thanks
