### ISSUE TITLE
Is there a way to scale nsqlookupd?

### ISSUE THREAD

**Issue by L1ghtman2k** [nsqio/nsq#1247]
Hey everyone, I am new to NSQ and I am trying to understand some of the concepts.

At the moment my understanding is that nsqlookupd node addresses have to be hardcoded into both clients and producers. Is there a way to scale up the nsqlookupd instances in a way that would be auto-discovered by producers and consumers?

An instance where that would be useful is when we need to keep producers and consumers operational. Imagine a setup with 2 consumers, 2 producers, and 2 nsqlookupd nodes. Say a node goes down that was carrying one of the two instances of nsqlookupd. This will create a SPOF, and without restarting the producer consumers we will be unable to eliminate that SPOF. It would be nice to scale up the nsqlookupd instances as needed.

One approach I imagine is to have nsqlookupd instanced behind a DNS round-robin, and if a node fails, the entry could be removed from DNS listing.  nsqlookupd instances, on the other hand, could perhaps create a cluster by attempting to query DNS and looking for new entries at the start, and later all nodes that get scaled up could join the cluster by also looking up the DNS names.

Any thoughts on this? Feel free to roast me as you wish 😂 

UPD: now that I think of it, it is possible to perhaps have (correct me if I am wrong):
producers and consumers to point to DNS names of nsqlookupd1, and nsqlookupd2. Assume  nsqlookupd2 goes down, then we can just respawn nsqlookupd2 instance, and point DNS name to the new instance. Thus eliminating SPOF (However we are still bound to only 2 instances). (Still leave your thoughts on previous inquiry if you can)

**Comment by jehiah** [comment]
> Imagine a setup with 2 consumers, 2 producers, and 2 nsqlookupd nodes. Say a node goes down that was carrying one of the two instances of nsqlookupd. This will create a SPOF

You should run a number of nsqlookupd that's commiserate with your ability to respond to that failure. If say it took you a week to roll out new nsqd settings to point to a new nsqlookupd hosts you might want to run 3 or 4 of them.  In most situations two is perfectly fine - but nsqlookupd is extremely lightweight so it's easy to run on multiple servers.

> Thus eliminating SPOF

It might be helpful to remember that nsqlookupd is not involved in any message handling; it's only used when consumers start up, when introducing new nsqd nodes to an existing cluster, and for nsqadmin control plane actions. Beyond that, nsqlookupd doesn't affect message flow for existing connections. You should test this to be comfortable with the failure modes.

> to have nsqlookupd instanced behind a DNS round-robin

You generally want consumers and nsqd to connect to *all* nsqlookupd instance, so you don't want to round-robin. That said, using hostnames and updating to point to new hosts as needed is a common approach. nsqd also has a HTTP api for updating it's running config of nsqlookupd in case it's helpful. https://nsq.io/components/nsqd.html#get-confignsqlookupd_tcp_addresses

**Comment by mreiferson** [comment]
Great questions, great answer, closing!
