### ISSUE TITLE
supporting Kubernetes

### ISSUE THREAD

**Issue by ccding** [nsqio/nsq#1255]
Is there any plan for supporting Kubernetes?

**Comment by ploxiln** [comment]
There are no plans for any features related to kubernetes. It is possible to run nsq in kubernetes though. See: https://github.com/nsqio/nsq/issues/1245 https://github.com/nsqio/nsq/issues/1185 https://github.com/nsqio/nsq/issues/1078 https://www.reddit.com/r/kubernetes/comments/beui94/nsqoperator_announcement/ (though this effort seems to be dead)

**Comment by mreiferson** [comment]
ping #1254
