### ISSUE TITLE
delete topic Logic optimization

### ISSUE THREAD

**Issue by tututt** [nsqio/nsq#1256]
in nsqd/topic.go, function: exit(deleted bool)
when deleted is true, use ergodic to delete channelMap's elements, why delete it once like "t.channelMap = make(map[string]*Channel)", which is more effective.

**Comment by ploxiln** [comment]
it also calls `channel.Delete()` for each channel in the map:

```go
	if deleted {
		t.Lock()
		for _, channel := range t.channelMap {
			delete(t.channelMap, channel.name)
			channel.Delete()
		}
		t.Unlock()
```

... and it is assumed that the cost of deleting each entry from the map is not significant, there are probably fewer than 100 channels, more than that is probably a bigger performance problem elsewhere ...

**Comment by tututt** [comment]
I mean change the code like this
`if deleted {
		t.Lock()
		for _, channel := range t.channelMap {
			channel.Delete()
		}
                 t.channelMap = make(map[string]*Channel)
		t.Unlock()`
yes, it is not significant, but it is a little improvement. And it is my suggestion, thanks for your reply.
