### ISSUE TITLE
create channel in BASH

### ISSUE THREAD

**Issue by max27149** [nsqio/nsq#1257]
USE
curl -X POST 'http://127.0.0.1:4151/channel/create?topic=test&channel=channel_test'
or:
curl -X POST http://127.0.0.1:4151/channel/create?topic=test\&channel=channel_test

Do not use:
curl -X POST http://127.0.0.1:4151/channel/create?topic=test&channel=channel_test
{"message":"MISSING_ARG_CHANNEL"}

**Comment by konohanaruto** [comment]
> USE
> curl -X POST 'http://127.0.0.1:4151/channel/create?topic=test&channel=channel_test'
> or:
> curl -X POST [http://127.0.0.1:4151/channel/create?topic=test\&channel=channel_test](http://127.0.0.1:4151/channel/create?topic=test%5C&channel=channel_test)
> 
> Do not use:
> curl -X POST http://127.0.0.1:4151/channel/create?topic=test&channel=channel_test
> {"message":"MISSING_ARG_CHANNEL"}

Great!!! works for me!!!
