### ISSUE TITLE
nsqd: is it safe to use self-signed certificates?

### ISSUE THREAD

**Issue by lougxing** [nsqio/nsq#1259]

**Comment by ploxiln** [comment]
If the client connecting to nsqd has already obtained the public certificate in a trusted way, and is using it in its certificate-authority list for the connections to nsqd, then yes.

**Comment by lougxing** [comment]
nsqd Config:

`
tls_cert = "/home/t/nsq/etc/cert.pem"  // md5 = bcb868708712646d023ae75ed1faeca6
tls_key = "/home/t/nsq/etc/key.pem"   // md5 =191c32161fd59b19b519b0a3e664cb56
# tls_client_auth_policy = "require-verify"
# tls_root_ca_file = ""
tls_required = false
tls_min_version = ""
`

Consumer config:

`    
// c.config.CertPath="home/q/nsq/etc/cert.pem"  // md5 = bcb868708712646d023ae75ed1faeca6
// c.config.KeyPath="/home/q/nsq/etc/key.pem"  // md5 =191c32161fd59b19b519b0a3e664cb56
  if c.config.UseTLS {
        cert, err := tls.LoadX509KeyPair(c.config.CertPath, c.config.KeyPath)
        if err != nil {
            return err 
        }   
        tlsConfig := &tls.Config{
            Certificates:       []tls.Certificate{cert},
            InsecureSkipVerify: true,
        }   
        config.TlsConfig = tlsConfig
        config.TlsV1 = true
    } 
`
This is my  nsqd's config and consumer's config , they use the same *.pem on different host,  is it ok ?

**Comment by lougxing** [comment]
I make the ca and cert, as follow:

cd /etc/pki/CA && touch index.txt serial && echo 01 > serial
cd /etc/pki/CA/ && openssl genrsa -out private/cakey.pem 2048 && chmod 400 private/cakey.pem
openssl req -new -x509 -key private/cakey.pem -out cacert.pem
openssl genrsa -out nsq.key 2048
openssl req -new -key nsq.key -out nsq.csr
openssl ca -in nsq.csr -cert /etc/pki/CA/cacert.pem -keyfile /etc/pki/CA/private/cakey.pem -days 365 -out nsq.crt

I copy the  cacert.pem  into  "/etc/ssl/certs/", I didn't set tls-root-ca-file for nsqd,  it work, too.
must set tls-root-ca-file ?

**Comment by ploxiln** [comment]
If that works for you, that works. (I just wouldn't expect you would want to install such a CA root for all applications.)

**Comment by lougxing** [comment]
Thanks you suggestion,  you are right,  I have followed your suggestion for nsq consumer,
 but why nsqd set tls-root-ca-file ?  Is it must ?

**Comment by ploxiln** [comment]
It is very unusual for a *client* certificate to be trusted by a system shared CA root store, because those are typically for servers which are validated based on DNS name. For a server (like nsqd) to validate a *client* (like a consumer) certificate, it pretty much always uses a separate custom CA root store.

**Comment by lougxing** [comment]
thanks for your help.
