### ISSUE TITLE
When the value of the parameter is greater than one million, it will be converted to scientific notation

### ISSUE THREAD

**Issue by Daleyzw** [nsqio/nsq#1265]
When the nsq callback requests my project,the parameter order_id:1000001 converted to 1.000001e+06. Is this a bug

**Comment by ploxiln** [comment]
It looks like `order_id` is something inside your messages. nsqd does not touch the contents of messages, it leave the exact bytes as-is. These numerical conversions are happening either when the library you use to publish a message encodes it as json, or when the library you use to consume messages decodes the json. It's between the client library, and the json handling probably in the standard library of the language you are using to publish or consume. It is not related to this repo.
