### ISSUE TITLE
why inFlightPQ and deferredPQ use different implements of priority queue

### ISSUE THREAD

**Issue by MrRainning** [nsqio/nsq#1267]
deferredPQ  user package heap of go/1.13/libexec/src/container/heap/heap.go.
inFlightPQ is in nsqd/in_flight_pqueue.go.
but they look very similar.

**Comment by ploxiln** [comment]
I think that `inFlightPQ` is trying to be more efficient by reducing the number of allocations - all the data it needs is in the existing `Message` struct. All messages go through the in-flight PQ, but fewer (ideally very few) go through the deferred PQ, so it may be OK that the deferred PQ allocates a additional `Item` struct for each `Message`.

But honestly I'm not sure exactly why we couldn't use the same PQ fields in `Message`, and the `container/heap` stdlib implementation, for both  cases. I may find out the reason if I try to clean it up, which would be some work. It may be "historical" - there was a reason in the past, but no longer. I'm not sure.

**Comment by ploxiln** [comment]
commit 74bfde101934700cb0cd980d01b6dfe2fe5a6a53
Author: Matt Reiferson
Date:   Sun Mar 16 20:26:00 2014 -0400

    nsqd: refactor in flight pqueue / worker
    
    this eliminates the use of container/heap and
    the associated cost of boxing and interface
    type assertions.

**Comment by MrRainning** [comment]
@ploxiln  Thanks very much for your answer.
