### ISSUE TITLE
*: how can many consumers be handled efficiently?

### ISSUE THREAD

**Issue by umialpha** [nsqio/nsq#1269]
As the topology pattern is full mesh with consumers, if we have too many consumers, (e.g. 100k consumers), can NSQ hold these consumers?

### Our scenarios 
We use NSQ as a **work queue**, we have **20k service as workers**, each task cost _10s~30s_ to finish. 

### My first thought

The workers directly connect the NSQ and consume the tasks. **However, My major concern is whether NSQ can hold so many consumers.**

### What if we scale up our workers? 
Our system is a SLA based system. If the system estimates that it could not finish all the tasks before the deadline, it will scale up workers.

### Alternative

Add a **dispatcher layer** to dispatch tasks, but it will make our system more complicated.

**Comment by mreiferson** [comment]
(moved to https://github.com/nsqio/nsq)
