### ISSUE TITLE
nsqlookupd: listen error lists incorrect address.

### ISSUE THREAD

**Issue by TangDH03** [nsqio/nsq#1270]
File : nsq/nsqlookupd/nsqlookupd.go
Around line 43-46
````
l.httpListener, err = net.Listen("tcp", opts.HTTPAddress)
if err != nil {
	return nil, fmt.Errorf("listen (%s) failed - %s", opts.TCPAddress, err)
}
````
why it will print TCPAddress instead of HTTPAddress

**Comment by jehiah** [comment]
@TangDH03 good catch. Would you be interested in contributing a fix for this?

**Comment by TangDH03** [comment]
Sure,I will raise a PR
