### ISSUE TITLE
how to ensure the order consumed when multiple consumers

### ISSUE THREAD

**Issue by kevinsir** [nsqio/nsq#1272]
they order with id 1 have two message update1 and update2. I publish it in order .they are all in same topic。when  multiple channel consumers to deal the message will not ensure in order of  update1 and update2 .how to do that!

**Comment by ploxiln** [comment]
Order is not guaranteed, sorry. This is not a feature of the NSQ system.

**Comment by ploxiln** [comment]
see also https://nsq.io/overview/features_and_guarantees.html#messages-received-are-un-ordered
