### ISSUE TITLE
broadcast to all consumers of a channel

### ISSUE THREAD

**Issue by iHDJ** [nsqio/nsq#1279]
i want a channel can send message to all consumer.

**Comment by ploxiln** [comment]
In the NSQ model, you want a topic where every consumer uses its own channel. You could generate a randomly named ephemeral channel for each consumer, or if you have one consumer per instance/VM you could use node ID or hostname or something like that as the channel name.

**Comment by iHDJ** [comment]
> In the NSQ model, you want a topic where every consumer uses its own channel. You could generate a randomly named ephemeral channel for each consumer, or if you have one consumer per instance/VM you could use node ID or hostname or something like that as the channel name.

I think it is better to implement channel broadcasting mode.

**Comment by ploxiln** [comment]
I think it is unlikely that this project will work on, or accept, that particular feature.
