### ISSUE TITLE
'binary' query parameter in the http mpub method seems position dependent

### ISSUE THREAD

**Issue by dselivanov** [nsqio/nsq#1280]
When trying to publish `N` **binary** messages using `http://127.0.0.1:4151/mpub?topic=name&binary=true` (`binary=true` as second parameter) nsqd shows a single message appended. 
However it correctly works (adds `N` messages) when `binary=true` is provided as a first parameter: `http://127.0.0.1:4151/mpub?binary=true&topic=name`

**Comment by ploxiln** [comment]
works for me:

```
printf '\x00\x00\x00\x03\x00\x00\x00\x01A\x00\x00\x00\x01B\x00\x00\x00\x01C' |
    curl -v "http://127.0.0.1:4151/mpub?topic=test_mpub&binary=true" --data-binary "@-"
```

... results in 3 messages being published.

Any chance that the issue is in the client you are using to make the request? ... quoting the URL with params in the terminal, maybe? (the `&` splits the command in the terminal)

**Comment by dselivanov** [comment]
@ploxiln sorry, seems there was a mistake on my side. Just tried to provide minimal reproducible example here (I develop a tiny producer in python), but failed to do so - everything works now.
Thanks for quick response and sorry once again for posting without small reproducible example - that would save your time.
