### ISSUE TITLE
Can I start a new nsqd and then close old one without stop service ?

### ISSUE THREAD

**Issue by cossbow** [nsqio/nsq#1284]
Sometimes i want to change data/ to another dir, how do i switch old nsqd to new nsqd gracefully?

**Comment by ploxiln** [comment]
The answer is no, this is not a feature currently offered, nor in development.

A single nsqd instance will have a couple seconds of downtime when it is stopped and started up again, for a version upgrade, or a configuration change. This is usually not a significant problem when it is a member of a cluster with multiple instances, undergoing a "rolling" restart (one at a time).
