### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by martin-sucha** [nsqio/nsq#1286]
Hi!

The last release was more than a year ago. Do you plan to tag a new stable release?

**Comment by mreiferson** [comment]
yep, we'll publish a new release soon.

Out of curiosity, any particular change you're looking to benefit from? https://github.com/nsqio/nsq/compare/v1.2.0...master

**Comment by martin-sucha** [comment]
> yep, we'll publish a new release soon.

Thanks!

> Out of curiosity, any particular change you're looking to benefit from?

Not anything in particular from the commits - I'm setting up a new deployment so wanted to use the latest version (60 commits looks like a few fixes). Also the Docker image for 1.2.0 was built with Go 1.12.9, which is no longer supported.

**Comment by sidvenu** [comment]
@mreiferson can we expect a new version anytime soon?
