### ISSUE TITLE
nsqd: ephemeral channel loses message on quick REQs

### ISSUE THREAD

**Issue by synchrone** [nsqio/nsq#1288]
If an NSQ reader calls REQ while handling multiple messages at once while working with an ephemeral channel - messages requeued after the first REQ seem to be lost forever.

the following snippet consistently loses `message2`:
```js
const NSQ = require('nsqjs')

const nsqdHost = 'localhost'
const nsqdPort = '4150'
const topic = 'topic'
const channel = 'reader#ephemeral'

const writer = new NSQ.Writer(nsqdHost, nsqdPort, {})

function sleep(time){
  return new Promise(res => setTimeout(res, time))
}

function publish(body){
  return new Promise(res => writer.publish(topic, body, res))
}

const reader = new NSQ.Reader(topic, channel, {
  nsqdTCPAddresses: [`${nsqdHost}:${nsqdPort}`]
})

reader.on('message', msg => {
  console.log(`rcv ${msg.id}: ${msg.body}`)
  msg.requeue(100, false)
})

Promise.all([
  new Promise(res => reader.once('nsqd_connected', () => res())),
  new Promise(res => writer.once('ready', () => res()))
]).then(async () => {
  await sleep(100)
  await publish('message1')
  await sleep(1000)
  await publish('message2')
})

writer.connect()
reader.connect()
```
however, if we remove `#ephemeral` suffix from the channel name - both message1 and message2 keep circulating in the loop.

server logs:
[nsqd_ephemeral_loss.log](https://github.com/nsqio/nsq/files/5370876/nsqd_ephemeral_loss.log)
[nsqd_nonephemeral_noloss.log](https://github.com/nsqio/nsq/files/5370875/nsqd_nonephemeral_noloss.log)

**Comment by ploxiln** [comment]
did you configure `mem-queue-size` for nsqd, or leave it at the default?

**Comment by synchrone** [comment]
yes, i should have specified that `--mem-queue-size=0`

**Comment by mreiferson** [comment]
Ephemeral channels will only hold messages in memory, no disk-backed queue beyond `mem-queue-size`. Given that you configured `--mem-queue-size` as `0`, this effectively means one message.

The code publishes `message1`, consumes `message1`, requeues `message1`, and when it goes to publish `message2` it is discarded.
