### ISSUE TITLE
fatal error: acquireSudog

### ISSUE THREAD

**Issue by childeYin** [nsqio/nsq#1290]
when nsq producer stop, got this problem

fatal error: acquireSudog: found s.elem != nil in cache

goroutine 34975494 [running]:
runtime.throw(0x10b07cd, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000a11690 sp=0xc000a11660 pc=0x439292
runtime.acquireSudog(0xc0018417e8)
	/usr/local/go/src/runtime/proc.go:353 +0x372 fp=0xc000a11700 sp=0xc000a11690 pc=0x43c2d2
runtime.semacquire1(0xc0018417e8, 0x0, 0x1, 0x0)
	/usr/local/go/src/runtime/sema.go:115 +0x59 fp=0xc000a11768 sp=0xc000a11700 pc=0x44c7b9
sync.runtime_Semacquire(0xc0018417e8)
	/usr/local/go/src/runtime/sema.go:56 +0x45 fp=0xc000a11798 sp=0xc000a11768 pc=0x46dd65
sync.(*WaitGroup).Wait(0xc0018417e0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65 fp=0xc000a117c0 sp=0xc000a11798 pc=0x48ca65
github.com/nsqio/go-nsq.(*Producer).close.func1(0xc001841600)
	/builds/content/topics/vendor/github.com/nsqio/go-nsq/producer.go:303 +0x34 fp=0xc000a117d8 sp=0xc000a117c0 pc=0xcee594
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000a117e0 sp=0xc000a117d8 pc=0x471ec1
created by github.com/nsqio/go-nsq.(*Producer).close
	/builds/content/topics/vendor/github.com/nsqio/go-nsq/producer.go:300 +0x6f

**Comment by ploxiln** [comment]
this kind of thing can happen when you have miscellaneous/random memory corruption, which affects core go runtime primitives, see e.g. https://github.com/golang/go/issues/10541

**Comment by ploxiln** [comment]
this may have been caused by https://github.com/golang/go/issues/40641
which should be fixed in go-1.5.3 / go-1.4.10
