### ISSUE TITLE
 module declares its path as: github.com/nsqio/nsq but was required as: github.com/bitly/nsq

### ISSUE THREAD

**Issue by mengdj** [nsqio/nsq#1293]
C:\Users\Administrator>godep get github.com/bitly/nsq/...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: C:\Users\Administrator
godep: [WARNING]:       $GOPATH: E:\go
go: found github.com/bitly/nsq/... in github.com/bitly/nsq v1.2.0
go get: github.com/bitly/nsq@v1.2.0: parsing go.mod:
        module declares its path as: github.com/nsqio/nsq
                but was required as: github.com/bitly/nsq
godep: exit status 1

win32

**Comment by ploxiln** [comment]
> godep get github.com/bitly/nsq/...

where did you get that? that url has been out-of-date for many years now.
