### ISSUE TITLE
Load testing an nsqd results in broken pipe and connection refused

### ISSUE THREAD

**Issue by sidvenu** [nsqio/nsq#1298]
We have an nsqd attached to a service called **api** (just for knowledge, both of them are placed in a single container which is in turn placed in an `ECS EC2 Task` and the producer contacts the nsqd via localhost:4150). We tried to load the service with 2,000 connections simultaneously fetching data from it as much as it can. Every 30s-1m, this container fails. Digging deeper, we discovered that the service is alive and intact, while nsqd is crashing. The service cannot contact nsqd at localhost:4150 after some time. Looking at the logs, we found that this load test results in a broken pipe and thereafter trying to connect to port 4150 results in `ERR: dial tcp 127.0.0.1:4150: connect: connection refused`.
<details>
<summary>Here are the last few logs from NSQD as well as the service before it crashes:</summary>

1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.675174 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
-- | --
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.675249 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d400ca6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680283832","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.675256 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   39
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.678255 DEBUG: PROTOCOL(V2): [127.0.0.1:35938] [PUB logs]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.678444 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.678600 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d4018a6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680356868","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.678754 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   40
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.679229 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.679678 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d401ca6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680421435","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.680074 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   41
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684068 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684124 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d402ca6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680480448","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684132 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   42
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684488 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684647 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d4030a6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680509279","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.684726 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   43
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.685121 DEBUG: PROTOCOL(V2): [127.0.0.1:35938] [PUB logs]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.686510 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.686660 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d4038a6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680530502","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.686748 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   44
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.687198 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.687390 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d4038a6001) to client(13.235.50.111:49874) - {"requestId":"1605525591680551567","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.687469 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   45
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.687932 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.688159 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d403ca6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680571205","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.688289 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   46
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767110 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767165 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   46
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767196 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d4168a6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680595123","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767204 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   47
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767525 DEBUG: PROTOCOL(V2): [127.0.0.1:60498] [PUB GET_PAYLOAD_ENCRYPTION_KEY]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767567 DEBUG: PROTOCOL(V2): writing msg(0e1ac0d416ca6000) to client(13.235.50.111:49874) - {"requestId":"1605525591680628119","minVersion":0,"maxVersion":0,"tasks":["GET_PAYLOAD_ENCRYPTION_KEY","API_1605525197874781258"],"payload":null,"headers":null,"success":false,"errorCode":"","error":"","onErrorTask":"API_1605525197874781258","completed":false,"errorOccured":false,"lastTask":""}
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767651 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   48
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767756 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3eb4a6004]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767843 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3eb4a6005]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767873 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3eb8a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767879 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3eb8a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767914 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ecca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.767944 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ecca6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768013 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ecca6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768033 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ecca6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768049 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768121 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   39
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768128 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   39
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768196 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768205 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768217 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768311 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   36
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768320 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   36
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768341 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6004]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768407 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed0a6005]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768415 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ed4a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768430 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3feca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768477 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff0a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768507 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff0a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768518 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   30
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768523 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   30
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768600 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff0a6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768620 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff0a6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768663 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff0a6004]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768709 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768793 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768800 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768866 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   24
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768873 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   24
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768948 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768960 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6004]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.768978 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6005]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769034 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   21
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769057 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   21
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769088 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff4a6006]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769124 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff8a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769136 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff8a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769226 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff8a6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769248 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff8a6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769315 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ff8a6004]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769394 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ffca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769404 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ffca6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769420 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ffca6002]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769429 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   12
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769434 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:   12
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769517 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d3ffca6003]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769537 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4000a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769618 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d400ca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769625 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4018a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769630 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d401ca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769690 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    7
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769697 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    7
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769717 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d402ca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769814 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4030a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769822 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4038a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.769826 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4038a6001]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.774486 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    3
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.774513 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    3
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.774540 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d403ca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.774556 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    2
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.995086 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    2
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.995147 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    2
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.995503 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [NOP]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.995970 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d4168a6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.996003 DEBUG: PROTOCOL(V2): [13.235.50.111:49874] [FIN 0e1ac0d416ca6000]
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.996013 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    0
1.60553E+12 | customlogs-nsqd2020/11/16 11:19:52.996017 DEBUG: [13.235.50.111:49874] state rdy:  100 inflt:    0
1.60553E+12 | 2020/11/16 11:19:53 INF    2 [API_1605525197874781258/listener] querying nsqlookupd http://lookupd-lb-d835f2151bc02fd6.elb.ap-south-1.amazonaws.com:4161/lookup?topic=API_1605525197874781258
1.60553E+12 | 2020/11/16 11:19:53 ERR    3 (localhost:4150) IO error - write tcp 127.0.0.1:35938->127.0.0.1:4150: write: broken pipe
1.60553E+12 | 2020/11/16 11:19:53 ERR    3 (localhost:4150) sending command - write tcp 127.0.0.1:35938->127.0.0.1:4150: write: broken pipe
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) IO error - read tcp 127.0.0.1:60498->127.0.0.1:4150: read: connection reset by peer
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) beginning close
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) readLoop exiting
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) breaking out of writeLoop
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) writeLoop exiting
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) beginning close
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) readLoop exiting
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) breaking out of writeLoop
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) writeLoop exiting
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) finished draining, cleanup exiting
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) clean close complete
1.60553E+12 | 2020/11/16 11:19:53 INF    1 exiting router
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | ERR: not connected
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) finished draining, cleanup exiting
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) clean close complete
1.60553E+12 | 2020/11/16 11:19:53 INF    3 exiting router
1.60553E+12 | not connected
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) connecting to nsqd
1.60553E+12 | 2020/11/16 11:19:53 ERR    3 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    3 (localhost:4150) connecting to nsqd
1.60553E+12 | 2020/11/16 11:19:53 ERR    1 (localhost:4150) error connecting to nsqd - dial tcp 127.0.0.1:4150: connect: connection refused
1.60553E+12 | 2020/11/16 11:19:53 INF    1 (localhost:4150) connecting to nsqd
1.60553E+12 | ERR: dial tcp 127.0.0.1:4150: connect: connection refused

</details>

Here's how we run `nsqd` in our service container:
`/nsqd -broadcast-address $IP -broadcast-tcp-port $INSTANCE_TCP_PORT -broadcast-http-port $INSTANCE_HTTP_PORT -lookupd-tcp-address $1:4160 -log-level debug -log-prefix customlogs-nsqd &`.

The **api** service acts as a producer of the following topics:
- GET_PAYLOAD_ENCRYPTION_KEY

It acts as a consumer of the following topics:
- API_{timestamp}
*timestamp -> the timestamp when this service was created.*

We set the default configuration for producers.
For consumers, we have the default configuration plus max in flight as 100.

We are using the [go-nsq](https://github.com/nsqio/go-nsq) client library.

Is this a limitation of `nsqd` that a single daemon cannot handle high load? Or is it due to some configuration problem on our end?

**Comment by ploxiln** [comment]
2000 connections should be OK (if the host system is more powerful than a raspberry pi 2), but there could possibly be some lock contention if they are registering all at the same time ... more likely is that you are creating lots of channels or topics? maybe ephemeral?

There is no panic backtrace from nsqd, so I wouldn't be so sure it "crashed", perhaps it became pathologically slow/frozen, or perhaps the out-of-memory killer abruptly SIGKILLed it. You'll want to monitor the nsqd process separately, and see the cpu usage and memory usage over time leading up to the apparent failure. Backgrounding it in the shell with `... &` isn't really the way to go. If using containers, nsqd should probably be in its own container, so that the system can tell you how long it has been running, when it restarted, the cpu/memory usage. (Some orchestration systems have a "pod" concept where a few containers always run together, e.g. each instance of API gets its own instance of nsqd next to it.)

Can you describe the number of topics, channels, and whether any are "#ephemeral"? Can you report memory and cpu usage before the failure? Can you list running processes in the container? Can you give output from the nsqd `/stats` just before it dies?

**Comment by sidvenu** [comment]
@ploxiln we don't have any ephemeral topics at all.

The only topics involved in this load test are:
`GET_PAYLOAD_ENCRYPTION_KEY`
`API_{timestamp}`

Here are the nsqd stats just before it dies:
```
nsqd v1.2.0 (built w/go1.15.5)
start_time 2020-11-20T07:48:10Z
uptime 2h58m7.126171694s

Health: OK

Memory:
   heap_objects             	495803
   heap_idle_bytes          	42786816
   heap_in_use_bytes        	157884416
   heap_released_bytes      	42786816
   gc_pause_usec_100        	401
   gc_pause_usec_99         	401
   gc_pause_usec_95         	401
   next_gc_bytes            	211907760
   gc_total_runs            	16

Topics:
   [GET_PAYLOAD_ENCRYPTION_KEY] depth: 0     be-depth: 0     msgs: 90398    e2e%: 
      [listener                 ] depth: 133   be-depth: 0     inflt: 50   def: 0    re-q: 0     timeout: 0     msgs: 90398    e2e%: 
        [V2 1195a0423c19         ] state: 3 inflt: 50   rdy: 50   fin: 90215    re-q: 0        msgs: 90265    connected: 7m21s

   [logs           ] depth: 3611  be-depth: 0     msgs: 3611     e2e%: 

Producers:
   [V2 94af11fad225         ] msgs: 3611     connected: 7m14s
      [logs           ] msgs: 3611    

   [V2 94af11fad225         ] msgs: 90398    connected: 2h58m2s
      [GET_PAYLOAD_ENCRYPTION_KEY] msgs: 90398
```

An observation I made during the load test is that under the topic `GET_PAYLOAD_ENCRYPTION_KEY`, in `V2 1195...` the `inflt` number is always 45-50 (tending to be 50 always) and `rdy` is at a constant 50. The `nsqd` is jumping between 2-10% of both CPU and Memory in a t3a.micro instance having 2 CPU cores and 1GB Memory.

We are using Amazon ECS for running our tasks, and we have a service there called `API`, whose task definition contains a single container having both the nsqd and our API-related code. We have set a hard memory limit of 192MB for a task, exceeding which the container will be killed. But we observe that the nsqd process is getting stopped, while the API-related code in the container is still running. So we concluded that it is not due to ECS's hard limit for the task we set.

**Comment by ploxiln** [comment]
heap_in_use_bytes is around 150 MiB, and heap_idle_bytes is around 40 MiB, that will soon hit your 192MB memory limit, and then nsqd will be killed by the OOM (out-of-memory) killer, which will pick the most "guilty" process so that the other one can continue to run.

You could try to reduce max memory usage of nsqd by reducing the `--mem-queue-size` from the default 10000 to maybe 1000. (It looks like the 3611 logs messages queued may be using the most memory, but 2000 client connections could also use roughly as much memory ...)

**Comment by mreiferson** [comment]
This is more than likely a configuration issue with this experiment and not an actual bug in `nsqd`, so I'm going to close this. (e.g. you should be able to verify if it's the OOM killer in system logs)
