### ISSUE TITLE
docker: publish ARM images

### ISSUE THREAD

**Issue by duanhongyi** [nsqio/nsq#1306]
Now arm is used more and more widely. At present, many projects have docker images of arm, such as [Nats](https://hub.docker.com/_/nats). I hope that maintainers can add arm related images in docker hub.

**Comment by danbf** [comment]
![giphy (5)](https://user-images.githubusercontent.com/5041307/126371995-4d16f50d-79fd-4102-a70e-0bc7a2b9fa4e.gif)

this may be as simple as changing over to `buildx` in the image build chain ala'

```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7
```
https://www.docker.com/blog/multi-arch-images/

i might be able to write a patch for this if someone points to the relevant section

**Comment by danbf** [comment]
is it changing https://github.com/nsqio/nsq/blob/master/dist.sh#L45 to this gonna do it?

```
docker buildx build -t nsqio/nsq:v$version . --platform linux/amd64,linux/arm64,linux/arm/v7 --push
```

**Comment by danbf** [comment]
@mreiferson ^^

**Comment by danbf** [comment]
actually since buildx needs some setup, i do this on my end for multi-arch's:

ensure i cleared out the buildx builder in case it got interrupted before
```
docker buildx rm <builder-name>
```
then:
```
docker buildx create --name <builder-name>
docker buildx use <builder-name>
docker buildx build --tag <remote_tag> . --platform linux/amd64,linux/arm64,linux/arm/v7 --push
```
then clear out the buildx builder so it's ready for the next time i run it
```
docker buildx rm <builder-name>
```

**Comment by danbf** [comment]
i have it running in `sso` like this https://github.com/buzzfeed/sso/pull/319 so i'll take a crack at this

**Comment by mreiferson** [comment]
looking forward to it @danbf

**Comment by mreiferson** [comment]
see #1355
