### ISSUE TITLE
Consumers receive messages with a big delay when multiple NSQD instances are running

### ISSUE THREAD

**Issue by L1ghtman2k** [nsqio/nsq#1310]
I have an application that runs in the K8s cluster, and my app utilizes NSQ for message publishing.

Here is a quick paint drawing of it:
![image](https://user-images.githubusercontent.com/35672535/102028534-c24b0b80-3d78-11eb-9392-7cf37f15c674.png)

I have 3 NSQD instances and 3 NSQLookupd instances. Consumers are utilizing the go-nsq library. The client discovers NSQD instances using [ConnectToNSQLookupds](https://godoc.org/github.com/nsqio/go-nsq#Consumer.ConnectToNSQLookupds) method.

Producers are publishing messages to address `nsqd`, which internally round robins to one of the nsqd instances. Every nsqd instance is still queriable by its hostname(aka nsqd-1.nsqd, nsqd-2.nsqd, nsqd-3.nsqd), which they advertise to all lookupd instances.

The problem I am encountering is when I have multiple nsqd instances, along with multiple nsqlookupd instances, the consumers receive the updates with various delays, in some cases, it is instantaneous but in some cases, the delay is very long(Upwards to 7 seconds).

I have recorded the end result here to better demonstrate what is going on(this is part of the application that is utilizing NSQ):
![screenrecorder](https://user-images.githubusercontent.com/35672535/102029180-7c437700-3d7b-11eb-838b-4ad35e3c13cc.gif)

When the Switch is clicked the producer sends the message to one of the NSQD instances(this step is instantaneous). However, the switch only changes the position when the consumer consumes the message from NSQD(this step happens to have various delays). As you can see, at some point the switch changes the position instantaneously after getting clicked, and in some cases, it does NOT change its' position when getting clicked. This behavior alternates

When scaling down nsqd instances to 1, but keeping 3 nsqlookupd instances, the issue was resolved, and there was no delay.

Any ideas on what could be the reason behind these inconsistencies? (I am utilizing nsqio/nsq:v1.1.0 docker image)

**Comment by jehiah** [comment]
@L1ghtman2k If you want to consume messages from multiple nsqd instances you must ensure that your consumer is configured to request messages from all the nsqd instances it's connecting to. This is controlled by `MaxInFlight`. 

If that isn't the issue you are running into, can you share a reproducible example, and logs from the consumer and nsqd?

https://pkg.go.dev/github.com/nsqio/go-nsq#Config.MaxInFlight

**Comment by L1ghtman2k** [comment]
Thank you, this did fix my issue. I had a wrong understanding of MaxInFlight(To me it was how many messages can consumer consume from a single NSQD instance at once)
