### ISSUE TITLE
NSQ: how can i check content of deferred or requeued messages in nsq

### ISSUE THREAD

**Issue by nafeex** [nsqio/nsq#1311]
We are using NSQ and can't figure out how can I check the content of deferred or requeued message because after a certain attempt nsq lost the message so we don't have any log to check which messages are lost 
we try to go through the nsq doc and StackOverflow #
https://stackoverflow.com/questions/65303208/nsq-how-can-i-check-content-of-deferred-or-requeued-messages-in-nsq

**Comment by ploxiln** [comment]
There is currently no way to inspect deferred or requeued messages in nsqd. However ... it is the job of the consumer to check the number of attempts and mark the message "finished" if the configured number of attempts have been exhausted. It is common for the consumer to log messages when they are failed, and it is also possible (depending on the nsq client library) to customize behavior when attempts are exhausted, for example: https://pynsq.readthedocs.io/en/latest/reader.html#nsq.Reader.giving_up
