### ISSUE TITLE
*: migrate to go:embed from go-bindata

### ISSUE THREAD

**Issue by jehiah** [nsqio/nsq#1317]
With go 1.16 the Go language supports embedding files in a binary; It is therefore desirable to switch from using `go-bindata` for embedding nsqadmin resources to the stdlib approach with `go:embed` when we are ready to drop support for Go 1.15

https://tip.golang.org/pkg/embed/

**Comment by mreiferson** [comment]
see #994

**Comment by mreiferson** [comment]
done in #1347
