### ISSUE TITLE
Is writeMessageToBackend method not thread safey？

### ISSUE THREAD

**Issue by miyazawatomoka** [nsqio/nsq#1318]
[writeMessageToBackend](https://github.com/nsqio/nsq/blob/8adb229f70538c6f6554b98285a33552bcb5832c/nsqd/message.go#L92)
The` buf` has been bufferPoolPut，but `buf.Bytes() `send to a chan.

**Comment by ploxiln** [comment]
The backend queue Put() method waits for confirmation of the write:
https://github.com/nsqio/go-diskqueue/blob/master/diskqueue.go#L156-L166
