### ISSUE TITLE
nsqadmin and basic auth

### ISSUE THREAD

**Issue by patrickbucher** [nsqio/nsq#1321]
I run nginx as a proxy to nsq, and nsq is protected using basic auth. This setup works fine for me. However, I have issues with nsqadmin. I can access the tool via basic auth. However, when I want to show details to a topic, I get this error:

`UPSTREAM_ERROR: Failed to query any nsqd: Get http://my.domain.com:4151/stats?format=json&topic=[my-topic]&include_clients=false: dial tcp [my-public-nsq-ip]1:4151: i/o timeout `

The `broadcast_address` is obviously taken from `nsqd.cfg`:

`broadcast_address = "my.domain.com"`

If I change it to 

`broadcast_address = "127.0.0.1"`

everything works fine in nsqadmin, but this of course doesn't work for the other servers that want to log to nsq.

Is there a way to tell nsqadmin to fetch his data from a different host than the one 
broadcasted?

Running everything in version 1.2.0.

**Comment by ploxiln** [comment]
You'll want your nsqd broadcast address to work for nsq clients, nsqadmin, and nsqlookupd (if used). I guess it does get tricky if clients should use auth to connect to nsqd through the standard address, but nsqadmin doesn't have a built-in way to do that itself.

One possible way to try to work-around this is to add `my.domain.com` to `/etc/hosts` on that server:

```
127.0.0.1  my.domain.com
```

**Comment by patrickbucher** [comment]
Simple solution for my simple setup, thanks! It works perfectly.
