### ISSUE TITLE
arm64 release binaries

### ISSUE THREAD

**Issue by aneeshusa** [nsqio/nsq#1324]
Related to https://github.com/nsqio/nsq/issues/1306 which is about docker images.

We use nsq and are currently working on moving large parts of our fleet to run on ARM. We currently use the release binaries you upload to S3, which are amd64 only currently. Would it be possible to also build and upload Linux ARM64 binaries?

Based on a quick look around the repo, it seems like [`dist.sh`](https://github.com/nsqio/nsq/blob/c164c776ab1af72706fff6cc05cd80a36771811d/dist.sh) would just need to be updated to also do a build for ARM64, is that correct?

**Comment by mreiferson** [comment]
Sure, why not

**Comment by mreiferson** [comment]
fixed in #1364
