### ISSUE TITLE
nsqadmin: topic with large payload fails to open

### ISSUE THREAD

**Issue by netrebel** [nsqio/nsq#1325]
One of our topics has a JSON response of 17M. According to the logs it takes around 2 mins 38s for the request to respond:

```
[nsqadmin] 2021/03/09 23:17:25.795930 INFO: 200 GET /api/topics/large-topic (127.0.0.1:60324) 2m38.429935315s
```

We've tried increasing the timeouts to accommodate this response:
```
./nsqadmin --http-client-connect-timeout=240s --http-client-request-timeout=240s
```

But we continue to get the error `ERROR: failed to connect to nsqadmin` in the UI when trying to open the topic.

Without the timeout arguments nsqadmin log showed:
```
[nsqadmin] 2021/03/10 18:20:21.496331 WARNING: net/http: request canceled (Client.Timeout exceeded while reading body)
net/http: request canceled (Client.Timeout exceeded while reading body)
```

**Comment by jehiah** [comment]
I feel like congratulations are in in order for running into this sort of scaling bottleneck. Do you have any additional context on the number of channels in that topic to better capture where nsqadmin starts encountering this type of issue?

In your test is the browser connecting directly to nsqadmin, or is the http request routed through any additional proxy layers that might also include a timeout (i.e. nginx, oauth2_proxy, load balancer, etc)?

**Comment by netrebel** [comment]
Hi @jehiah, thanks for your response. 

The topic with the highest number of channels we have has around **1200** channels in our daily peak hours.

I was using Google Chrome to make the request, which times out at 20s:
<img width="1933" alt="Screen Shot 2021-03-10 at 10 35 51 AM" src="https://user-images.githubusercontent.com/294448/110694937-20cc2e00-819e-11eb-86fb-1a705feea7dc.png">

I tried to do `curl` to `nsqadmin:4171/api/topics/large-topic` and it never ended, I stopped it at 45 mins (636MB)! 😬

```
HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Nsq-Content-Type: nsq; version=1.0
< Date: Wed, 10 Mar 2021 18:39:28 GMT
< Transfer-Encoding: chunked
<
{ [3927 bytes data]
100  636M    0  636M    0     0   232k      0 --:--:--  0:46:41 --:--:-- 12979^C
```

I'm guessing `/api/topics/` returns **all** the data needed so that when we start clicking on the _producers_ those pages are loaded faster, as in a single-page application?

**Comment by mreiferson** [comment]
Thanks for the report @netrebel.

45min, hah. 1200 channels doesn't seem like _that_ many - how many clients are typically connected to these channels (each, total)? Can you provide more the `nsqadmin` logs? Also, what version are you running?

**Comment by netrebel** [comment]
There's 381 instances of this log in the nsqadmin log when I try to open the large-topic:
`INFO: CI: querying nsqd http://100.100.X.X:4151/stats?format=json&topic=large-topic&include_clients=false`

I think that's the number of nsqd clients connected to the topic, right? 

using `v1.2.0`

nsqadmin logs:
```
$ ./nsqadmin --http-address=0.0.0.0:4171 --lookupd-http-address=100.100.0.1:4161 --lookupd-http-address=100.100.0.2:4161 --lookupd-http-address=100.100.0.3:4161 --lookupd-http-address=100.100.0.4:4161 --http-client-connect-timeout=240s --http-client-request-timeout=240s
[nsqadmin] 2021/03/22 21:26:14.590053 INFO: nsqadmin v1.2.0 (built w/go1.12.9)
[nsqadmin] 2021/03/22 21:26:14.595900 INFO: HTTP: listening on [::]:4171
[nsqadmin] 2021/03/22 21:26:58.456264 INFO: 200 GET / (127.0.0.1:33312) 6.862299ms
[nsqadmin] 2021/03/22 21:26:58.753106 INFO: 200 GET /static/base.css (127.0.0.1:33314) 277.365µs
[nsqadmin] 2021/03/22 21:26:58.754259 INFO: 200 GET /static/bootstrap.min.css (127.0.0.1:33312) 3.124804ms
[nsqadmin] 2021/03/22 21:26:59.011120 INFO: 200 GET /static/vendor.js (127.0.0.1:33316) 4.0424ms
[nsqadmin] 2021/03/22 21:26:59.011659 INFO: 200 GET /static/main.js (127.0.0.1:33318) 4.540553ms
[nsqadmin] 2021/03/22 21:26:59.437338 INFO: CI: querying nsqlookupd http://100.100.0.1:4161/topics
[nsqadmin] 2021/03/22 21:26:59.437467 INFO: CI: querying nsqlookupd http://100.100.0.2:4161/topics
[nsqadmin] 2021/03/22 21:26:59.439697 INFO: CI: querying nsqlookupd http://100.100.0.3:4161/topics
[nsqadmin] 2021/03/22 21:26:59.440890 INFO: CI: querying nsqlookupd http://100.100.0.4:4161/topics
[nsqadmin] 2021/03/22 21:26:59.442303 INFO: 200 GET /static/nsq_blue.png (127.0.0.1:33318) 364.13µs
[nsqadmin] 2021/03/22 21:26:59.443821 INFO: 200 GET /api/topics (127.0.0.1:33316) 6.529629ms
[nsqadmin] 2021/03/22 21:26:59.641279 INFO: 200 GET /static/favicon.png (127.0.0.1:33318) 208.981µs
[nsqadmin] 2021/03/22 21:27:51.857789 INFO: CI: querying nsqlookupd http://100.100.0.1:4161/lookup?topic=large-topic
[nsqadmin] 2021/03/22 21:27:51.857833 INFO: CI: querying nsqlookupd http://100.100.0.3:4161/lookup?topic=large-topic
[nsqadmin] 2021/03/22 21:27:51.857908 INFO: CI: querying nsqlookupd http://100.100.0.2:4161/lookup?topic=large-topic
[nsqadmin] 2021/03/22 21:27:51.857914 INFO: CI: querying nsqlookupd http://100.100.0.4:4161/lookup?topic=large-topic
[nsqadmin] 2021/03/22 21:27:52.018677 INFO: CI: querying nsqd http://100.100.X.X:4151/stats?format=json&topic=large-topic&include_clients=false
... 380 more of these ^ (with different IPs of course)
[nsqadmin] 2021/03/22 21:28:11.777061 INFO: 200 GET /static/bootstrap.min.css (127.0.0.1:33316) 973.244µs
[nsqadmin] 2021/03/22 21:28:11.783049 INFO: 200 GET /static/base.css (127.0.0.1:33312) 99.193µs
[nsqadmin] 2021/03/22 21:28:11.852375 INFO: 200 GET /static/main.js.map (127.0.0.1:33314) 2.924786ms
[nsqadmin] 2021/03/22 21:30:27.495817 INFO: 200 GET /api/topics/large-topic (127.0.0.1:33318) 2m35.638028248s
```

**Comment by mreiferson** [comment]
> I think that's the number of nsqd clients connected to the topic, right?

It's the number of `nsqd` that produce `large-topic`.

I'm trying to recreate the conditions of your cluster to understand where `nsqadmin` is spending its time, can you paste a redacted response from one of `nsqd` stats requests?

```
http://100.100.X.X:4151/stats?format=json&topic=large-topic&include_clients=false
```

Can you confirm the versions of all `nsqd` in the cluster? I want to confirm they all support the `include_clients` param.

**Comment by netrebel** [comment]
Here's the response to that request:
[stats-nsqd-dump.json.zip](https://github.com/nsqio/nsq/files/6194335/stats-nsqd-dump.json.zip)

We are using `v0.3.8` for all nsqd instances

Thanks for looking into this Matt!

**Comment by jehiah** [comment]
@netrebel the most recent version is 1.2.0; you should see improved performance on that version. Can you upgrade and confirm that you see better performance?

https://github.com/nsqio/nsq/releases (also note the backwards compatible changes between 0.3.8 and 1.x - see documentation here https://github.com/nsqio/nsq/releases/tag/v1.0.0-compat)

**Comment by netrebel** [comment]
Giving you some more numbers...

We have 81 `nsqd` instances **_producing_** to `large-topic`. 
On the **_consumer_** side, we have 592 client connections. So that would give us **47,952** connections to the channel. Each connection would be displayed as a row in the channel page (If we could see the _topic_ page and we could click on the _channel_ to see its connections. It would seem that that this is trying to be loaded by nsqadmin when we click on the topic?)

>the most recent version is 1.2.0; you should see improved performance on that version.

@jehiah I think you are saying that the performance of nsqadmin would also be improved if we updated `nsqd` to v1.2.0. I see in the [release notes](https://github.com/nsqio/nsq/releases/tag/v1.2.0) ([PR 1118](https://github.com/nsqio/nsq/pull/1118)) that clients are not loaded by default with that fix.

**Comment by mreiferson** [comment]
Exactly, you've upgraded `nsqadmin` which attempts to pass along `include_clients=false` but the version of `nsqd` you're running doesn't support that flag, resulting in much larger payloads and reduced performance.
