### ISSUE TITLE
nsqd: panic when nsqd exits

### ISSUE THREAD

**Issue by wangcn** [nsqio/nsq#1326]
How to reproduce?
1. Pull master branch. The lastest commit is c164c77
2. Make
3. Start nsqd
4. Kill nsqd

It panics and outputs "panic: close of closed channel".

https://github.com/nsqio/nsq/pull/1319#discussion_r584392317
https://github.com/nsqio/nsq/pull/1319/commits/ad73d0508ccaa622f4a1380abdca06b42bcdfc03#diff-4fb927abdfbf2db38da702b7131f128fa6d7e4cbd3d6d7baa3f4271eb2949956R471
These lines cause nsqd.Exit to be called twice. We can just simply use go-svc to handle all signals.

**Comment by mreiferson** [comment]
ping @jehiah

**Comment by mreiferson** [comment]
This will be fixed if #1331
