### ISSUE TITLE
Which is the latest stable version at now

### ISSUE THREAD

**Issue by michealzh** [nsqio/nsq#1328]
As README file mentioned,`master is our development branch and may not be stable at all times.`, so what is the latest stable version of nsq?
We are using version of `0.3.7`, but some times when try to send message to nsq in golang,it will using more than 1 second to publich message to nsq.

**Comment by jehiah** [comment]
It sounds like you are asking about the version of the Go client side package - the most recent release of `go-nsq` is v1.0.8. If you are instead asking about the nsq server side component, please consult the releases page - https://github.com/nsqio/nsq/releases

https://pkg.go.dev/github.com/nsqio/go-nsq
