### ISSUE TITLE
Latest Release was 2019

### ISSUE THREAD

**Issue by aviezab** [nsqio/nsq#1334]
Dear Maintainers,
I looked today Your guys latest release was still 2019.

Is master branch safe to use at production level? Yes, I have read the readme that Master branch is Your development branch, but I am curious do You guys use it in production and is stable, because We'd love to use latest commit in production.

Thank You.

**Comment by mreiferson** [comment]
We'll work to get a new release out soon, I'd defer to @jehiah for testing at scale for any of the changes pending in `master`.

**Comment by mreiferson** [comment]
started to update the ChangeLog to give you a sense of the delta https://github.com/nsqio/nsq/commit/a1da1173d3bfa0ea41b73a3b75ec447a32287c52

**Comment by kuchaguangjie** [comment]
nsq don't release often, it hasn't release for 18 months.

Does it means: 
1. It's very stable, and almost no bug.
2. Its features are so good, no need hurry.
3. You want fully testing, before any release.

Or, there are some other reason?

**Comment by mreiferson** [comment]
I like to think (1) is true, we've only rarely published immediate bug-fix releases following a normal release. (3) is certainly true as well.

The truth of it is that the maintainers do this in their free time, which is limited these days :)
