### ISSUE TITLE
"inFlightPqueue" and "pqueue"  share the same logic

### ISSUE THREAD

**Issue by xianxueniao150** [nsqio/nsq#1339]
"inFlightPqueue" and "pqueue"  are all priority queue as implemented by a min heap，it's no need to write the same logic for twice，can I  merge them?

**Comment by ploxiln** [comment]
`inFlightPqueue` is an optimization for a particularly common and active priority queue, to avoid the separate allocation for the `Item` struct for each element.

**Comment by mreiferson** [comment]
Yes, I suppose generics will provide the opportunity to clean this up.
