### ISSUE TITLE
how can i watch message in real-time?

### ISSUE THREAD

**Issue by Erchoc** [nsqio/nsq#1342]
when the message will recored to file?

the web ui don't show message detail，and i can't watch the memory message.

so，how can i watch the real-time message？thanks.

**Comment by ploxiln** [comment]
One good way to watch messages in real-time is to use [nsq_tail](https://nsq.io/components/utilities.html#nsq_tail) on a new ephemeral channel. You need to run it in a server or container which is able to access the appropriate nsqlookupd and nsqd. So it would be like:

```
nsq_tail --topic="$YOUR_TOPIC" --channel="new-random-name#ephemeral" --lookupd-http-address=http://$YOUR_LOOKUPD:4161
```
