### ISSUE TITLE
Does nsqd have the ability to provide encryption keys

### ISSUE THREAD

**Issue by hicampuswl** [nsqio/nsq#1353]
In our application, we only use nsqd and enable tls authentication. However, the tls authentication provided by nsqd only allows the loading of plaintext keys, causing our system to have a security risk, that is, exposing plaintext keys. Is there any solution or circumvention?
- --tls-cert=/etc/ssl/certs/nsq/NSQServerCrt.pem
- --tls-key=/etc/ssl/certs/nsq/NSQServerKey.pem
- --tls-root-ca-file=/etc/ssl/certs/nsq/rootCACrt.pem
- --tls-required=tcp-https
- --tls-client-auth-policy=require-verify

**Comment by ploxiln** [comment]
How would NSQ decrypt your encrypted encryption keys? It would probably need another key to do that ...

Usually, when installing these files, you should make these files readable only by the unix user nsqd is run under. Similarly, a web server like nginx will use tls key files the same way, usually by running as the `www-data` user or `nginx` user, and having these tls key files only readable by that user.

Another option you may be interested in, is to be able to pass the contents of these files as environment variables. That isn't a feature we have, and it hasn't been requested yet, but I think it's another plausible solution for making them less exposed to the rest of the host system.
