### ISSUE TITLE
NSQ as Window Service -io timeout

### ISSUE THREAD

**Issue by jronatay** [nsqio/nsq#1356]
Hi admins,

I have nsqd running as a window service and the server where it's running encounters error when running it 
![image](https://user-images.githubusercontent.com/7813323/127971983-9f2e0d23-e5ba-4842-83bd-a51b5038125f.png)
We tried to disable the firewall and still we have same problem. Do you have some idea or solution to this ?

Thank you :)

**Comment by mreiferson** [comment]
Sorry, not really possible to debug connectivity issues like this. If you can easily reproduce this, then please add more info.
