### ISSUE TITLE
nsqd: get messages over HTTP

### ISSUE THREAD

**Issue by angry-elf** [nsqio/nsq#136]
May be, this will be funny not only for me.

What I need for one of my future applications - get messages one by one. May be, I mixed with application logic. Let's explain.

I have pool of data for work on it. I populate this pool once per week/month. Operators (people in callcenter) pick one message from pool and process it. Operators works with web-application. One page access - one message from queue should be got. So, tcp-daemon usecase is useless here - in a case of empty message queue it will hung forever.

My propose is to add HTTP-handler for NSQD to process requests like this:

```
curl -i 'http://127.0.0.1:4151/get?topic=test&channel=test_channel'
```

And response may be, for existing message:

```
HTTP/1.1 200 OK
X-MESSAGE-ATTEMPTS: 1
X-MESSAGE-ID: cfd852793302455c8c1a97d2908c77ce
X-MESSAGE-CREATED: 1358791153
Content-Length: 12

Hello world!
```

Or, for empty queue, it may return... http "204 no content" code?

**Comment by heipei** [comment]
Is there anyone still working on this or similar approaches?

**Comment by Ethreal** [comment]
Can we have an update for this?

**Comment by ploxiln** [comment]
You should either use a "proper" nsq client library (of which there are a few and they're all rather light-weight), or you should use such a library to write your own to-plain-http adapter that works the way you need it to work (handling "ready" updates and acknowledgements as is appropriate for your use case).

On old possibly-no-longer-working example: https://gist.github.com/ploxiln/47732ec45db40878d12de083a1828a00
