### ISSUE TITLE
feat: NSQ cluster or public network message synchronization

### ISSUE THREAD

**Issue by godcong** [nsqio/nsq#1360]
I now have such a demand, and some nsqds are running on public network servers in different countries.
When I publish a message on a certain server, I need to synchronize it to all machines in different regions.
However, nsqlookupd cannot do this.

I want to upgrade nsqlookupd to support these functions.
Or create a new project.
I hope to get some suggestions from you.

**Comment by mreiferson** [comment]
dupe of #510
