### ISSUE TITLE
What does NSQ stand for?

### ISSUE THREAD

**Issue by carsonoid** [nsqio/nsq#1369]
I've been using it for quite a while now and someone asked me what NSQ stands for. I've searched up and down in the repo and the docs and can't find anything. Obviously the `Q` is Queue. But what about the `NS`. Thoughts:

* NameSpace?
* Not Simple?

Thanks in advance for answering my silly question.

**Comment by jehiah** [comment]
NSQ's predecessor at Bitly was a C app built on top of `libevent` named [`smiplequeue`](https://github.com/bitly/simplehttp/tree/master/simplequeue) and NSQ built on many of the client side patterns that were used with that, so while not officially an acronym let's say it's inspired by "not simplequeue"
