### ISSUE TITLE
why is deleted topic not re-created

### ISSUE THREAD

**Issue by yocaning** [nsqio/nsq#1374]
when i delete the topic。why dont re-create topic when i restart consumer server？

version：1.1.0

**Comment by ploxiln** [comment]
It's possible for consumers using nsqlookupd to automatically connect to an nsqd that used to have the topic they want, just seconds after it was deleted, recreating it, and for this to prevent you from effectively deleting topics. To fix this, nsqlookupd has the concept of "tombstones" to prevent this for a time. The default nsqlookupd tombstone-lifetime is 45 seconds.

**Comment by yocaning** [comment]
Thank you for your answer.

**Comment by yocaning** [comment]
> It's possible for consumers using nsqlookupd to automatically connect to an nsqd that used to have the topic they want, just seconds after it was deleted, recreating it, and for this to prevent you from effectively deleting topics. To fix this, nsqlookupd has the concept of "tombstones" to prevent this for a time. The default nsqlookupd tombstone-lifetime is 45 seconds.

Thank you for your answer
