### ISSUE TITLE
How to get first message in each consumer call.

### ISSUE THREAD

**Issue by bmcinnovasionstudio** [nsqio/nsq#1378]
Hi Team,

Assume that one of my backend application will insert data in to the channel in a sequential order. 
Other end, consumer will read the data from the channel.
Our requirement is , once the consumer connected to the nsq and read the channel, it should read 1 message from the channel at a time instead of all messages together. Means in a FIFO method.

Is this doable in NSQ?

Please advice.

Best Regards,

Sujan

**Comment by ploxiln** [comment]
Your consumer can be configured with max-in-flight=1, in order to only get one message at a time, and wait until it calls `finish()` on that message before getting another.

Order is not guaranteed by nsq design ... but in simple situations without retries or spilling to disk, you will usually get the messages in order.

**Comment by bmcinnovasionstudio** [comment]
Thank you ploxilin.

I tried this parameter. but still consumer app fetching all the messages from the channel.

Config.Set("max-in-flight",1)

Any other options.

**Comment by ploxiln** [comment]
If multiple messages are being processed by a single consumer concurrently, then something is wrong - either the nsq client library you are using, or your usage of it.

**Comment by bmcinnovasionstudio** [comment]
My code below. Could you verify it.

package main

import (
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/nsqio/go-nsq"
)

var (
	addr    = flag.String("addr", "192.168.3.140:4161", "NSQ lookupd addr")
	topic   = flag.String("topic", "Topic", "NSQ topic")
	channel = flag.String("channel", "Channel", "NSQ channel")
)

// MyHandler handles NSQ messages from the channel being subscribed to
type MyHandler struct {
}

func (h *MyHandler) HandleMessage(message *nsq.Message) error {
	log.Printf("Got a message: %s", string(message.Body))
	message.Finish()
	return nil
}

func main() {

	// parse the cli options
	flag.Parse()
	if *topic == "" || *channel == "" {
		flag.PrintDefaults()
		os.Exit(1)
	}

	// configure a new Consumer
	config := nsq.NewConfig()
	//config.Set("maxinflight",1)

	consumer, err := nsq.NewConsumer(*topic, *channel, config)
	if err != nil {
		log.Fatal(err)
	}
	consumer.ChangeMaxInFlight(1)
	// register our message handler with the consumer
	consumer.AddHandler(&MyHandler{})

	// connect to NSQ and start receiving messages
	//err = consumer.ConnectToNSQD("nsqd:4150")
	err = consumer.ConnectToNSQLookupd(*addr)
	if err != nil {
		log.Fatal(err)
	}

	// wait for signal to exit
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	<-sigChan

	// disconnect
	consumer.Stop()
}

**Comment by ploxiln** [comment]
Thanks for including samples. Please use "fenced code blocks" when pasting in sample code: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks (also note you can edit your existing comments if you want to).

This config setting:

```go
decodeConfig.Set("max-in-flight",1)
```

should be like:

```go
err := decodeConfig.Set("max_in_flight", 1)
if err != nil {
	// log.Fatalf() or handle
}
```

or like this is also perfectly fine:

```go
decodeConfig.MaxInFlight = 1
```

So that's my fault for describing the setting as "max-in-flight" ... it's named differently for different client libraries :)

**Comment by bmcinnovasionstudio** [comment]
Hi Ploxilin,

Thank you for your prompt support.
I have one more request.

By default, Consumer thread will active to monitor the channel until getting a message. 
I want a process to initiate a consumer, check messages in the channel, read message if available and stop the consumer thread.
If the channel is empty stop the consumer thread instead of waiting for message.

What configuration changes need be applied in the below code. Please advice.

```` 
```
package main

import (
"github.com/nsqio/go-nsq"
"log"
"sync"
)

func main() {
wg := &sync.WaitGroup{}
wg.Add(1)

decodeConfig := nsq.NewConfig()
decodeConfig.MaxInFlight = 1
c, err := nsq.NewConsumer("Topic", "Channel", decodeConfig)
if err != nil {
	log.Panic("Could not create consumer")
}
c.ChangeMaxInFlight(1)//MaxInFlight defaults to 1

c.AddHandler(nsq.HandlerFunc(func(message *nsq.Message) error {
	log.Println("NSQ message received:")
	log.Println(string(message.Body))
	c.Stop()
	message.Finish()
	wg.Done()
	return nil
}))

err = c.ConnectToNSQD("127.0.0.1:4150")
if err != nil {
	log.Panic("Could not connect")
}

log.Println("Awaiting messages from NSQ topic \"My NSQ Topic\"...")
wg.Wait()
}

```
````

**Comment by ploxiln** [comment]
There is no built-in option for that, sorry.

You could try to build some custom handling that could work well enough. One idea: after finishing a message, set a timer for a few seconds. (Cancel timer when next message is received.) If no further message received after a few seconds, exit. Or, after that timer, make an http request to the nsqd to at `/stats?format=json&topic=Topic&channel=Channel` and confirm depth is zero.

**Comment by bmcinnovasionstudio** [comment]
Thanks Ploxiln.

It worked as per your solution.


Best Regards,

Sujan
