### ISSUE TITLE
build failure with "go get"

### ISSUE THREAD

**Issue by tvitcom** [nsqio/nsq#1382]
go1.15.11 linux/amd64
After: go get github.com/nsqio/nsq/...
Return:
```
# github.com/nsqio/nsq/apps/nsqd
../../github.com/nsqio/nsq/apps/nsqd/main.go:96:9: undefined: svc.ErrStop
```

**Comment by ploxiln** [comment]
This appears to be because nsq currently uses a fork of github.com/judwhite/go-svc

We do not claim to support building with just "go get" though. Please download a binary release, or follow the build instructions here: https://nsq.io/deployment/installing.html#building-from-source
