### ISSUE TITLE
Is the order of messages with the same defer time preserved?

### ISSUE THREAD

**Issue by yanghva** [nsqio/nsq#1389]
Referring to the [DPUB](https://nsq.io/clients/tcp_protocol_spec.html#dpub) command, is there any guarantee on message delivery order? For example, imagine a system with one producer, one nsqd, one consumer. On producer side, if I
```
DPUB sample_topic 1000 [SIZE] msg1
DPUB sample_topic 1000 [SIZE] msg2
```
Can I expect to receive messages in that order on the consumer side?

FYI I am using this php client library [wk30/phpnsq](https://github.com/wk30/phpnsq)

**Comment by ploxiln** [comment]
The order is not guaranteed, and your application should not depend on that. It is often true that you will happen to get messages in the original order through a single nsqd. If you need a guaranteed order, you should put a sequence number inside your messages, and then either:
 * use a sufficiently high max-in-flight on the consumer, so it can receive all the out-of-order messages before processing and finishing them in-order
 * have the consumer defer messages (again) for a second or two if it knows other messages should be processed first

or you could use a different queuing system like Kafka
