### ISSUE TITLE
when set mem-queue-size=0, maybe lost a message.

### ISSUE THREAD

**Issue by syz521** [nsqio/nsq#1391]
![图片](https://user-images.githubusercontent.com/16085221/145357716-d4dd237a-508f-4e9f-ac0c-9dd21bc2439e.png)
![图片](https://user-images.githubusercontent.com/16085221/145357801-21abfc95-84f6-4d37-a05d-e91fcb5fe954.png)

**Comment by syz521** [comment]
when get first message from memoryMsgChan and still  if nsqd crash , it will lost

**Comment by ploxiln** [comment]
Correct, mem-queue-size=0 is not a 100% guarantee, and is not generally recommended because most of nsqd was not designed for that mode of operation, so it has some weird edge-cases and inefficiencies.

See also:
 * https://github.com/nsqio/nsq/pull/625
 * https://github.com/nsqio/nsq/issues/1375

**Comment by ploxiln** [comment]
see also https://github.com/nsqio/nsq/issues/1386
