### ISSUE TITLE
How to limit the queue size and expire out-dated messages?

### ISSUE THREAD

**Issue by wxiaoguang** [nsqio/nsq#1396]
Some AMQP brokers can set `max-length` for a queue, and set `expiration/TTL` for a message.

Overflowed/expired messages will be deleted.

In some cases, users only need limited/recent messages.

Is this feature available for NSQ?

**Comment by ploxiln** [comment]
No, this is not a feature built-in to NSQ.

You can embed an "expires-at" timestamp in the body of the message, and the (custom) consumer can check for expiry, and if expired, mark the message finished without processing it.

(I can't think of any practical way to limit number of queued messages by discarding the oldest.)

**Comment by wxiaoguang** [comment]
`discarding the oldest`: yup, that's what some other brokers (like rabbit) do, they discard all the overflowed and expired messages (or move them into dead-letter queue).

Such feature could be useful in cases the resources (storage/memory) are limited while the logs are generated very quickly and users doesn't care about losing some old logs.
