### ISSUE TITLE
How long is the longest delay message of NSQ

### ISSUE THREAD

**Issue by hklinux2010** [nsqio/nsq#1397]
How long is the longest delay message of NSQ

**Comment by hklinux2010** [comment]
please, help me. Thanks!

**Comment by ploxiln** [comment]
Hey, sorry for taking so long to respond.

`nsqd` has a `--max-req-timeout` option (which defaults to 1 hour). When a client requeues a message it can specify a delay, and if the delay is higher than this max-req-timeout, then it is reduced to this limit. You can configure this limit higher or lower in nsqd.

There isn't really a limit to how many times a message can be retried. (Message attempts is an unsigned 16-bit counter, so it will go up to 65535, then wrap around to zero, nsq currently does not check/protect against that.) Finally, a message could wait in the (normal) queue an indefinite amount of time, before a consumer is available to receive it. So a message could ultimately be delayed indefinitely. Depending on what you mean :)

**Comment by hklinux2010** [comment]
Thank you very much for your answer
