### ISSUE TITLE
will timed-out messages be retried indefinitely

### ISSUE THREAD

**Issue by fengcunwu** [nsqio/nsq#1398]
If the consumer does not return any information to nsqd within the msg-timeout timeout period after receiving the message, the message will continue to be written to memory or disk, and will it fall into an infinite loop?

**Comment by ploxiln** [comment]
yes

**Comment by ploxiln** [comment]
... but typically the consumer client library will check the attempt count first, and if it exceeds the max attempts configured for the consumer, it will "finish()" the message immediately instead of trying to process it. (this effectively discards the message)
