### ISSUE TITLE
nsq_stat: why is egress negative

### ISSUE THREAD

**Issue by hklinux2010** [nsqio/nsq#1399]
![image](https://user-images.githubusercontent.com/72911366/161068447-2e7daab6-2d25-4815-87f8-e5ffc1db6d53.png)

After your last instruction, I modified NSQ_ The calculation method of egress in stat is still negative today. Why,

`		fmt.Printf("%7d %7d %7d| %7d %7d %7d %5d %5d | %7d %7d %12d %7d\n",
			int64(float64(c.MessageCount-o.MessageCount)/interval.Seconds()),
			int64(float64(c.MessageCount-o.MessageCount-(c.Depth-o.Depth))/interval.Seconds()),
			int64(float64((c.MessageCount-o.MessageCount)-(c.Depth+c.InFlightCount+c.DeferredCount)-(o.Depth+o.InFlightCount+o.DeferredCount))/interval.Seconds()),
			c.Depth,
			c.MemoryDepth,
			c.BackendDepth,
			c.InFlightCount,
			c.DeferredCount,
			c.RequeueCount,
			c.TimeoutCount,
			c.MessageCount,
			c.ClientCount)`

**Comment by ploxiln** [comment]
this appears to be a continuation of https://github.com/nsqio/nsq/issues/1392

**Comment by hklinux2010** [comment]
I have modified the calculation method, but there is still a negative number, and I do not consume, but simply input data into the queue

**Comment by ploxiln** [comment]
It would be more helpful to post a git diff of your changes (in a multi-line code-quote).

Your screenshot shows 2 columns for ingress/egress, but your code has 3 columns, so they do not correspond:

 * `int64(float64(c.MessageCount-o.MessageCount)/interval.Seconds())` : ingress
 * `int64(float64(c.MessageCount-o.MessageCount-(c.Depth-o.Depth))/interval.Seconds())` : "naive egress"
 * ` int64(float64((c.MessageCount-o.MessageCount)-(c.Depth+c.InFlightCount+c.DeferredCount)-(o.Depth+o.InFlightCount+o.DeferredCount))/interval.Seconds())` : what you think should have been the "fixed" egress

One issue is that `-(c.Depth+...)-(o.Depth+...)` should be `-((c.Depth+...)-(o.Depth+...))` (which would be equivalent to `-(c.Depth+...)+(o.Depth+...)`)

**Comment by hklinux2010** [comment]
You can ignore the second one. I didn't delete the original one for comparison，This is the method of calculation，
int64(float64((c.MessageCount-o.MessageCount)-(c.Depth+c.InFlightCount+c.DeferredCount)-(o.Depth+o.InFlightCount+o.DeferredCount))/interval.Seconds())

**Comment by ploxiln** [comment]
... even with that fixed you'll probably still see one message popping up or down in the rates occasionally, because I think messages are not moved from "queued" to "in flight" in a single atomic operation, or a single "transaction". So at some millisecond instant a message is not included in any of the counts, and then it returns in another count. :shrug:

**Comment by hklinux2010** [comment]
It's just a display problem. In fact, the message is not consumed
