### ISSUE TITLE
nsq什么时候出官方的java客户端

### ISSUE THREAD

**Issue by qq2429979710** [nsqio/nsq#1400]
nsq什么时候出官方的java客户端

**Comment by ctlove0523** [comment]
不如我们一起给NSQ贡献一个

**Comment by ploxiln** [comment]
We cannot understand chinese, sorry.

**Comment by qq2429979710** [comment]
When will NSQ release an official Java client

**Comment by ploxiln** [comment]
Never, sorry.

**Comment by ploxiln** [comment]
The only client libraries we really know about are listed in https://nsq.io/clients/client_libraries.html and it looks like the most recently updated java client is https://github.com/sproutsocial/nsq-j
