### ISSUE TITLE
nsq_to_file: invalid cross-device link when moving from work-dir to output-dir

### ISSUE THREAD

**Issue by dselivanov** [nsqio/nsq#1404]
I'm trying to use `nsq_to_file` to sync messages to S3. 
So I use `--work-dir` option: `--work-dir=/nsq_logs/nsq_logs_workdir`  to store intermediate messages to local disk and
and `--output-dir=/nsq_logs/nsq_logs_store` where `/nsq_logs/nsq_logs_store` is S3 an bucket mounted as locally using [s3fs](https://github.com/s3fs-fuse/s3fs-fuse).

Logs however can't be moved to `/nsq_logs/nsq_logs_store` and I'm getting following FATAL exception `invalid cross-device link`. I believe this is due how [exclusiveRename](https://github.com/nsqio/nsq/blob/a1da1173d3bfa0ea41b73a3b75ec447a32287c52/apps/nsq_to_file/file_logger.go#L377) works.

Would it makes sense to catch such exceptions and use file copy instead of `os.Link`?

EDIT: Something like [here](https://github.com/idoall/gocryptotrader/blob/afb2b8d045f245bc879906ec0b0f1e455633df32/common/file/file.go#L40-L88)

**Comment by mreiferson** [comment]
We use `os.Link` to ensure atomicity for filesystems that support it. My recommendation here would be to have something else responsible for uploading to S3 and cleaning up the `--output-dir`.

**Comment by dselivanov** [comment]
Thanks Matt, I've switched to external script for now. Do you think it worth to handle cross-device file copy/move within `nsq_to_file`?

**Comment by mreiferson** [comment]
I don't think so — we would have to rethink the behavior of other parts of the code given the lack of atomicity. However, we could consider at least documenting the fact that this expects `--work-dir` and `--output-dir` to be on the same device.
