### ISSUE TITLE
POST /channel/create

### ISSUE THREAD

**Issue by qaqhy** [nsqio/nsq#1409]
Why can't we use the method of submitting the form to call the API, we must append the parameters to the url?
error:  http -f POST 127.0.0.1:4161/topic/create topic=test
success: http -f POST 127.0.0.1:4161/topic/create?topic=test
![image](https://user-images.githubusercontent.com/45985955/175496377-e62601b5-3558-4a2c-be83-5e0f52162c61.png)

**Comment by mreiferson** [comment]
If my memory serves me well, it's because we wanted a basic set of parameters to be visible in request logs.
