### ISSUE TITLE
protocol.go SendResponse return format 

### ISSUE THREAD

**Issue by CmderQ** [nsqio/nsq#1410]
hi， I open nsq code by Goland;When  review file app/internal/protocol/protocol.go,
 The SendResponse(w io.Writer, data []byte) function end line, code：
`return (n + 4), nil`
It alter：`Unwrap parentheses`
Click,  refactor the code：`return (n + 4), nil`

**Comment by mreiferson** [comment]
I think this is suggesting to remove the parentheses. Feel free to open a PR.

**Comment by CmderQ** [comment]
> I think this is suggesting to remove the parentheses. Feel free to open a PR.

OK！Next time I would do it!
