### ISSUE TITLE
Topic message with http

### ISSUE THREAD

**Issue by ericklodion** [nsqio/nsq#1412]
I'm creating a harness tool and need to get messages from topic without consumming it, only for debug.

There is anyway to get topic message with http ? 

I didn't found it on documentation :
https://nsq.io/components/nsqd.html
https://nsq.io/components/nsqlookupd.html

Is it possible ?

**Comment by ploxiln** [comment]
Nope, not possible, sorry.

You could create a `debug#ephemeral` channel, next to all the other channels that need to get the topic's messages. Of course, as soon as any channel is created, the topic will begin to empty, so usually you want to ensure all needed channels are created before messages begin to be added (or before topic is un-paused).
