### ISSUE TITLE
NSQ machine downtime

### ISSUE THREAD

**Issue by hklinux2010** [nsqio/nsq#1414]
Help  me：
    What is the impact of a machine downtime in the NSQ cluster and what should I do

**Comment by mreiferson** [comment]
The answer depends on the nature of the failure - any messages held in memory would be lost, and if that `nsqd` instance does not come back online and it had messages written to diskqueue and that data was not recoverable there would be additional data loss.

IOW, today, there is no built in replication.

see #510
