### ISSUE TITLE
How to encrypt NSQ TCP traffic? 

### ISSUE THREAD

**Issue by susanxyz** [nsqio/nsq#1418]
I don't find setting to config TLS for TCP.

**Comment by ploxiln** [comment]
For the TCP protocol for publishing and consuming messages, nsqd listens on a single -tcp-address` port, and it can upgrade to using TLS on that port. There is also a command-line flag `-tls-required` such that the TCP connection protocol can't be used without the TLS upgrade. As for the other TLS settings which apply to the TCP protocol, it's the same ones:

```
$ nsqd --help 2>&1 | grep tls-
  -tls-cert string
  -tls-client-auth-policy string
  -tls-key string
  -tls-min-version value
  -tls-required
  -tls-root-ca-file string
```

The nsq client library you use may or may not support TLS. If you happen to use the go client library, it has some TLS options: https://pkg.go.dev/github.com/nsqio/go-nsq?utm_source=godoc#Config

If you're curious where nsqd switches the TCP protocol to TLS, during the IDENTIFY command:
https://github.com/nsqio/nsq/blob/master/nsqd/protocol_v2.go#L453
and where it optionally enforces TLS requirement before all other TCP protocol commands:
https://github.com/nsqio/nsq/blob/master/nsqd/protocol_v2.go#L174
