### ISSUE TITLE
How to use "-config" option

### ISSUE THREAD

**Issue by cui3093** [nsqio/nsq#1422]
Dear community, as the title.
Is there any way to use the -config optition for nsqd and other command?
Is there any doucment for that?
Is there any example for that?

**Comment by ploxiln** [comment]
The `-config` flag is for passing the path/name of a config file. An example nsqd config file can be found here: https://github.com/nsqio/nsq/blob/master/contrib/nsqd.cfg.example

**Comment by cui3093** [comment]
Thank you very much.
