### ISSUE TITLE
NSQ REST API security

### ISSUE THREAD

**Issue by Misiu** [nsqio/nsq#1426]
I have NSQ running as a part of larger solution.
It is used to send messages from server to client applications.
I'm using `-auth-http-address` and tls certs, so communication between application and server is secure, but I was searching a way to monitor NSQ health and I noticed that there is HTTP API (https://nsq.io/components/nsqd.html#http-api) and I can call each endpoint (for example topic/create) without any authorization.

How can I secure that API? an X-API-KEY header would be enough.

**Comment by jehiah** [comment]
It's expected that the HTTP API for nsqd/nsqlookupd/nsqadmin all are privileged and access control to them is built separately as a reverse proxy/dedicated solutions. 

You might get some ideas on how to approach that using something like `nsqauthfilter` from https://github.com/jehiah/nsqauth-contrib or by using https://github.com/buzzfeed/sso to provide access control to nsqadmin.

**Comment by Misiu** [comment]
Thank you for fast reply.
I'll take a look at both links.
