### ISSUE TITLE
Can we consume a new topic after nsq fully running?

### ISSUE THREAD

**Issue by ghazimuharam** [nsqio/nsq#1431]
We have a use case to publish a message to a topic dynamically, but we want to make sure the consumer will be consuming to the new topic too, is it possible to do so?

**Comment by ploxiln** [comment]
The usual consumer libraries do not have options to discover new topics, you typically configure which topic to consume.

I suppose you could write custom code to periodically poll nsqlookupd (via http api) for all available topics, check for new ones matching a pattern, and create new consumer instances for them, whether in the same process, or as subprocesses, or services managed by another system ...

... but this is generally not how nsq is designed to be used. Generally topics are more pre-planned and "fat". So you wouldn't create a new topic for every regular user that signs up, instead you'd have a user-events or user-actions topic that would be used for all users, and consumers can quickly filter-out many messages that are not relevant to them.
