### ISSUE TITLE
nsqd: panic when statsd enabled and memstats disabled with no topics

### ISSUE THREAD

**Issue by carl-reverb** [nsqio/nsq#1435]
https://github.com/nsqio/nsq/blob/master/internal/writers/spread_writer.go#L32

If a nsqd instance is configured to publish statsd metrics without memory stats (defaults to true) and there are no topics on the instance, the length of the buffer at flush interval will be zero, resulting in a divide by zero error.

Workaround by publishing memory stats, or creating a topic.

**Comment by mreiferson** [comment]
good catch, interested in submitting a PR to fix?
