### ISSUE TITLE
nsqadmin: how to setup on kubernetes with ingress nginx

### ISSUE THREAD

**Issue by cristiztara** [nsqio/nsq#1438]
i have created 1 pod in the same namespace for each service (nsqd, nsqlookoutd and nsqadmin) with helm, i added to my ingress nginx a path called /admin that points to nsqadmin on port 4171, but when i access it ( ex: test.mydomain.com/admin) i get an empty page with the text: {"message":"NOT_FOUND"}
Btw, i have multiple services that talk to each other and i'm using nsq as a message queue for them.
Any idea what could be wrong?

**Comment by mreiferson** [comment]
Closing. This is most likely an issue with the Kubernetes configuration vs an issue with `nsqadmin` itself. But, perhaps someone might be able to help if you provided logs.
