### ISSUE TITLE
protocol v2: `RDY` message seems to be useless

### ISSUE THREAD

**Issue by magniff** [nsqio/nsq#1440]
Recently I've been digging into `protocol v2` and I was puzzled by the `RDY` command spec. According to the [documentation](https://nsq.io/clients/tcp_protocol_spec.html#rdy), in order for the server to start sending messages to the client, the client must send a `RDY` command with a non-zero value to the server, for example `RDY 100` - it means I'm ready to receive `100` messages, as soon as I receive them, do not send me anything until the next update. However, in reality, it turns out that clients either do not update this state at all, or update only at the beginning of the reading session, setting the value to `1`.

So, upon getting the `RDY` message the clients atomic `ReadyCount` field gets update, which eventually finds its way to the [IsReadyForMessages](https://github.com/nsqio/nsq/blob/master/nsqd/client_v2.go#L392-L407) function, which decides whether the client is ready to get a new batch of messages. The only problem, that this `ReadyCount` is never decreased (except while performing the client's disconnection [here](https://github.com/nsqio/nsq/blob/master/nsqd/client_v2.go#L460-L465)) on the server's side, making the `RDY` command basically useless.

Am I missing something?

**Comment by magniff** [comment]
Ahh, interesting, according to this [thread](https://github.com/nsqio/nsq/pull/404), the `RDY` is indeed kind of useless and only left for the client's compatibility. So, it doesn't do much, but also the client cannot just quit sending the `RDY` command, because `ReadyCount` must be at least `1` to get the messages from the server. Maybe it's time to update the spec? =)

**Comment by ploxiln** [comment]
Clients don't always send `1`, it is fairly common to send a larger value like `100`, and this does make a difference: it is how many messages can be in-flight to that consumer. Clients just don't have to re-send it all the time - only when changing the max-in-flight. Which they do change if they run into errors processing messages and decide to "back-off" processing for a short period.
