### ISSUE TITLE
What NSQ stands for? this question bugs me hard 

### ISSUE THREAD

**Issue by daominah** [nsqio/nsq#1443]

**Comment by ploxiln** [comment]
It does not have a strict/specific meaning anymore, I think. But as noted at https://nsq.io/overview/design.html it was created as a successor to "simplequeue" at Bitly, so while starting the project it was called "not simplequeue" - nsq

**Comment by daominah** [comment]
oh, so "new simple queue" makes more sense

**Comment by ploxiln** [comment]
Ah, yes, "new simple queue" is the more common meaning :)
