### ISSUE TITLE
PUB message too big?

### ISSUE THREAD

**Issue by Nyx2022** [nsqio/nsq#1444]
when i publish a bytes to nsq,it occurs the error:
E_BAD_MESSAGE PUB message too big 1293055 > 1048576
so i wanna know how to adjust the limit value of 1048576 to a larger value

**Comment by jehiah** [comment]
You can run `nsqd --help` to see the configurable options, or visit the docs page at https://nsq.io/components/nsqd.html

```
-max-msg-size int
    maximum size of a single message in bytes (default 1048576)
```
