### ISSUE TITLE
nsqd: topic with suffix #ephemeral does not auto-delete when there is no channel

### ISSUE THREAD

**Issue by kayazinc** [nsqio/nsq#1447]
## Version: 1.2.1

Based on the doc (https://nsq.io/overview/design.html)
>Note, a topic/channel whose name ends in the string #ephemeral will not be buffered to disk and will instead drop messages after passing the mem-queue-size. This enables consumers which do not need message guarantees to subscribe to a channel. These ephemeral channels will also disappear after its last client disconnects. For an ephemeral topic, this implies that at least one channel has been created, consumed, and deleted (typically an ephemeral channel).

## Issue:
Topic still shown / available with any channel existed.
![xx0fHFd](https://user-images.githubusercontent.com/19774010/235414758-9d96d15d-42b2-4cfe-a14d-0f67ac142011.png)

## Expected behaviour:
A topic with suffix #ephemeral will disappeared / deleted if there are no channel.

Possible duplication: #1395 (but i am using default --mem-queue-size)

**Comment by mreiferson** [comment]
Can you provide `nsqd` logs? My guess is that the ephemeral topic was re-created (it has messages in the queue) after the last channel was deleted...

**Comment by mreiferson** [comment]
```nsqd-1  | [nsqd] 2023/05/08 06:32:24.834003 INFO: TOPIC(ESM3.quote#ephemeral): deleting
nsqd-1  | [nsqd] 2023/05/08 06:32:24.834637 INFO: TOPIC(ESM3.quote#ephemeral): closing ... messagePump
nsqd-1  | [nsqd] 2023/05/08 06:32:24.835754 INFO: LOOKUPD(nsqlookupd:4160): channel UNREGISTER ESM3.quote#ephemeral client#ephemeral
nsqd-1  | [nsqd] 2023/05/08 06:32:24.836167 INFO: LOOKUPD(nsqlookupd:4160): channel UNREGISTER order client#ephemeral
nsqd-1  | [nsqd] 2023/05/08 06:32:24.836698 INFO: LOOKUPD(nsqlookupd:4160): topic UNREGISTER ESM3.quote#ephemeral
nsqd-1  | [nsqd] 2023/05/08 06:32:29.747131 INFO: TOPIC(ESM3.quote#ephemeral): created```

You can see here that the last client disconnects and the topic `EMS3.quote#ephemeral` is deleted, then ~ 5s later the topic is recreated, presumably due to a message being published to that topic...

**Comment by mreiferson** [comment]
A (new) ephemeral topic that has no channels (and thus no clients consuming), e.g. one that was created as a result of publishing a message, will not get cleaned up until a client connects (creating a channel, presumably ephemeral) and then disconnects (triggering the ephemeral channel cleanup and then the ephemeral topic cleanup).
