### ISSUE TITLE
missing gophercon slide presentation

### ISSUE THREAD

**Issue by bitlyraccoon** [nsqio/nsq#1449]
going to https://nsq.io/talks_and_slides.html then clicking on the video link of the 8th bulletpoint ("2014-04-24 - GopherCon 2014 video slides (@imsnakes of Torando Labs)" should link to the slides presentation at https://www.confreaks.com/videos/3429-gophercon2014-spray-some-nsq-on-it but produces a 404

**Comment by bitlyraccoon** [comment]
![Screen Shot 2023-05-19 at 1 38 30 PM](https://github.com/nsqio/nsq/assets/112977867/4e1e7820-4be1-4cf8-ac07-195e0573cb75)

**Comment by mreiferson** [comment]
Still on youtube at: https://www.youtube.com/watch?v=CL_SUzXIUuI, I'll fix this is the docs.
