### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by Zhou-TheSeeker** [nsqio/nsq#1453]
Docker deployment succeeded. When I connected to the public IP for look consumption, I received an error message saying 'error connecting to nsqd - dial TCP: lookup nsqd node1: i/o timeout'

**Comment by mreiferson** [comment]
You'll have to provide more details around your configuration and what commands you're running for us to be able to help.

**Comment by Zhou-TheSeeker** [comment]
Sorry, I only saw it now
Configuration information:
version: '3'
services:
  nsqlookupd:
    restart: always
    container_name: nsqlookupd
    image: nsqio/nsq:latest
    command: /nsqlookupd --broadcast-address=nsqlookupd
    networks:
      - nsq-network
    ports:
      - "4160:4160"
      - "4161:4161"     
  nsqd-node1:
    restart: always
    container_name: nsqd-node1
    image: nsqio/nsq:latest
    command: /nsqd --lookupd-tcp-address=10.0.12.12:4160  --broadcast-address=nsqd-node1 --tcp-address=0.0.0.0:4150 --http-address=0.0.0.0:4151 --data-path=/data 
    depends_on:
      - nsqlookupd
    networks:
      - nsq-network  
    ports:
      - "14150:4150"
      - "14151:4151"
    volumes:
      - "/data/nsq-node1:/data"
  nsqd-node2:
    restart: always
    container_name: nsqd-node2
    image: nsqio/nsq:latest
    command: /nsqd --lookupd-tcp-address=10.0.12.12:4160  --broadcast-address=nsqd-node2  address=0.0.0.0:4250 --http-address=0.0.0.0:4251 --data-path=/data
    depends_on:
      - nsqlookupd
    networks:
      - nsq-network  
    ports:
      - "14250:4250"
      - "14251:4251"
    volumes:
      - "/data/nsq-node2:/data"  
  nsqadmin:
    restart: always
    container_name: nsqadmin
    image: nsqio/nsq:latest
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "14171:4171"
    networks:
      - nsq-network  
      
networks:
  nsq-network:
    driver: bridge

**Comment by Zhou-TheSeeker** [comment]
I attempted to configure node address resolution in my host file and it succeeded
