### ISSUE TITLE
query nsqlookupd errors

### ISSUE THREAD

**Issue by jeefs** [nsqio/nsq#1456]
I started a nsqd, a nsqlookupd, and a nsqadmin in my local environment, and the first time I connect through the consumer, it creates the topic and channel, but now it gives me error logs, and both topics are the same ip address, can anyone help me to solve the problem?

error log:   2023/07/13 15:34:23 ERR    3 [uploadFileToQiniuTask/c1] error querying nsqlookupd (http://127.0.0.1:4161/lookup?topic=uploadFileToQiniuTask) - got response 404 Not Found "{\"message\":\"TOPIC_NOT_FOUND
\"}"

**Comment by jeefs** [comment]
Additional note:   I use the go-nsq client to create producer and comsumer

**Comment by mreiferson** [comment]
Can you provide the commands and logs you're running?

**Comment by jeefs** [comment]
I run the following command to start the nsq daemon:
./nsqd -broadcast-address=127.0.0.1 -lookupd-tcp-address=127.0.0.1:4160
 ./nsqlookupd
./nsqadmin -lookupd-http-address=127.0.0.1:4161

3 daemon logs:
![微信图片_20230717104000](https://github.com/nsqio/nsq/assets/11971390/a53d0ae6-5ae2-48bb-8e5d-ace25fcc5f9c)
![微信图片_20230717104032](https://github.com/nsqio/nsq/assets/11971390/61f9a68e-cfa5-4381-8a33-e7c1a3b03e02)
![微信图片_20230717104050](https://github.com/nsqio/nsq/assets/11971390/a0137683-a8ab-430f-801d-36da4e4b8cea)
![微信图片_20230717104211](https://github.com/nsqio/nsq/assets/11971390/259a36c4-7e2c-479b-bed4-a11becc57944)

error logs:
C:\Users\mike\AppData\Local\Temp\GoLand\___5go_build_main_go.exe
producer ready
producer ready
2023/07/17 10:41:15 INF    3 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 INF    5 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 INF    4 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 INF    6 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 INF    1 (127.0.0.1:4150) connecting to nsqd
2023/07/17 10:41:15 INF    7 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 INF    8 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    7 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12"
2023/07/17 10:41:15 ERR    5 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    5 [testTask1/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    5 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 INF    7 [testTask2/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 ERR    6 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    6 [testTask2/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    6 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    3 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    3 [testTask1/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    3 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 ERR    5 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    5 [testTask1/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    7 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    4 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    4 [testTask1/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 ERR    8 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    8 [testTask2/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    8 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    6 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    6 [testTask2/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    6 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 INF    5 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 ERR    3 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    3 [testTask1/c1] retrying with next nsqlookupd
2023/07/17 10:41:15 INF    3 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 ERR    8 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    8 [testTask2/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    8 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    7 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 ERR    5 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 1 ready2023/07/17 10:41:15 INF    4 [testTask1/c1] querying nsqlookupd 
http://127.0.0.1:4150/lookup?topic=testTask1
2023/07/17 10:41:15 ERR    6 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 1 ready2023/07/17 10:41:15 ERR    3 [testTask1/c1] error querying nsqlo
okupd (http://127.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:415
0/lookup?topic=testTask1": net/http: HTTP/1.x transport connection broken: malfo
rmed HTTP response "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 2 ready2023/07/17 10:41:15 INF    7 [testTask2/c1] retrying with next n
sqlookupd
2023/07/17 10:41:15 INF    7 [testTask2/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask2
2023/07/17 10:41:15 ERR    4 [testTask1/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask1": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
2023/07/17 10:41:15 INF    4 [testTask1/c1] retrying with next nsqlookupd       
2023/07/17 10:41:15 INF    4 [testTask1/c1] querying nsqlookupd http://127.0.0.1
:4150/lookup?topic=testTask1
2023/07/17 10:41:15 ERR    8 [testTask2/c1] error querying nsqlookupd (http://12
7.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:4150/lookup?topic=t
estTask2": net/http: HTTP/1.x transport connection broken: malformed HTTP respon
se "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 3 ready2023/07/17 10:41:15 ERR    7 [testTask2/c1] error querying nsqlo
okupd (http://127.0.0.1:4150/lookup?topic=testTask2) - Get "http://127.0.0.1:415
0/lookup?topic=testTask2": net/http: HTTP/1.x transport connection broken: malfo
rmed HTTP response "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 2 ready2023/07/17 10:41:15 ERR    4 [testTask1/c1] error querying nsqlo
okupd (http://127.0.0.1:4150/lookup?topic=testTask1) - Get "http://127.0.0.1:415
0/lookup?topic=testTask1": net/http: HTTP/1.x transport connection broken: malfo
rmed HTTP response "\x00\x00\x00\x12\x00\x00\x00\x01E_BAD_PROTOCOL"
consumer 3 ready


My idea was to use nsq for asynchronous tasks, so I wrapped my own layer based on the go-nsq client：
[https://github.com/jeefs/nsq-task](https://github.com/jeefs/nsq-task)



push message:

```golang
package main

import (
	"log"
	"nsqTask"
	"os"
)

func main() {

	nsqTask.SetUp() //initialization,Generally at the framework entry file
	producer := nsqTask.GetProducer(nsqTask.TestTask1)
	msg := "msg 1"
	//push data,Generally in business logic
	file, err := os.OpenFile("./error.log", os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer func() {
		file.Close()
	}()
	log.SetOutput(file)
	//push message
	err = producer.Publish(nsqTask.TestTask1, []byte(msg))
	if err != nil {
		log.Printf("push message failed:%v", err.Error())
	} else {
		log.Printf("push message successful")
	}
	msg = "msg 2"
	err = producer.Publish(nsqTask.TestTask2, []byte(msg))
	if err != nil {
		log.Printf("push message failed:%v", err.Error())
	} else {
		log.Printf("push message successful")
	}
}```
