### ISSUE TITLE
topic Message to channel

### ISSUE THREAD

**Issue by trash-boy** [nsqio/nsq#1463]
Hello, in the code I read, the message is sent to the channel through a for loop, but if a certain channel fails to send the task, the remaining channels will not fall back. My idea is whether I can use the generated pointer, set the message pointer to a special value to avoid consumer consumption.

**Comment by jehiah** [comment]
When a message is put onto a topic, all channels on that topic get a copy of it.

https://nsq.io/overview/design.html#simplifying-configuration-and-administration

![img](https://f.cloud.github.com/assets/187441/1700696/f1434dc8-6029-11e3-8a66-18ca4ea10aca.gif)

**Comment by trash-boy** [comment]
> When a message is put onto a topic, all channels on that topic get a copy of it.
> 
> https://nsq.io/overview/design.html#simplifying-configuration-and-administration
> 
> ![img](https://camo.githubusercontent.com/e07d60c481271ce0fbe8254a04ac454b819bedf2e95a07ecf1403b86c2affb19/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3138373434312f313730303639362f66313433346463382d363032392d313165332d386136362d3138636134656131306163612e676966) [ ![img](https://camo.githubusercontent.com/e07d60c481271ce0fbe8254a04ac454b819bedf2e95a07ecf1403b86c2affb19/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3138373434312f313730303639362f66313433346463382d363032392d313165332d386136362d3138636134656131306163612e676966) ](https://camo.githubusercontent.com/e07d60c481271ce0fbe8254a04ac454b819bedf2e95a07ecf1403b86c2affb19/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3138373434312f313730303639362f66313433346463382d363032392d313165332d386136362d3138636134656131306163612e676966) [ ](https://camo.githubusercontent.com/e07d60c481271ce0fbe8254a04ac454b819bedf2e95a07ecf1403b86c2affb19/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3138373434312f313730303639362f66313433346463382d363032392d313165332d386136362d3138636134656131306163612e676966)


What I mean is that when the message in the topic is copied to a certain channel, an error occurs, but there is no error in other channels, then only the channel where the error occurred does not have this message.

**Comment by jehiah** [comment]
Can you clarify what type of error you are describing? Like when a consumer disconnects in the middle of processing a message?

**Comment by trash-boy** [comment]
Thanks for your explanation, I found something wrong with my thinking.
