### ISSUE TITLE
 nsqd health check duplicate

### ISSUE THREAD

**Issue by trash-boy** [nsqio/nsq#1481]
```ruby
func (s *httpServer) pingHandler(w http.ResponseWriter, req *http.Request, ps httprouter.Params) (interface{}, error) {
	//todo 健康检查这个地方可以直接利用health的值来判断健康的程度不需要两次调用
	health := s.nsqd.GetHealth()
	if !s.nsqd.IsHealthy() {
		return nil, http_api.Err{500, health}
	}
	return health, nil
}
```
可以通过health的值来判断健康状态，不需要再次调用s.nsqd.Healthy()函数

**Comment by dudleycarr** [comment]
`s.nsqd.GetHealth()` and `s.nsqd.IsHealthy` both check for the existence of an error, but they do two different things. `IsHealthy` returns whether the error exists or not. `GetHealth` returns a formatted string, which can include the error message.

While it's possible to rely just on `GetHealth`, that would break the abstraction and would be an ugly hack. It is possible to change the interface to return a struct that contains both the boolean value and the health message. However, the ping handler is hardly a critical path, and eliminating the overhead of checking the error reference twice doesn't seem like a significant performance issue.
