### ISSUE TITLE
Is there a way to peek all messages in queued?

### ISSUE THREAD

**Issue by zhanglinqiang** [nsqio/nsq#1482]
Hi, I'm using nsq-j client to pub/sub messages. I want to know if some data is still in the queue to be processed. I only know the ids of these data. Therefore I want to determine whether these data have be processed by foreach all queue data.

nsq server version: v1.3.0

nsq-j client servsion: 1.4.2

**Comment by mreiferson** [comment]
No, that is not a feature of the current protocol, unfortunately.
