### ISSUE TITLE
chore: cleanup error handling code for Accept

### ISSUE THREAD

**Issue by andrewvo148** [nsqio/nsq#1483]
https://github.com/nsqio/nsq/blob/2127c0a1ce50a66d61d78496033b15ef5cb5e250/internal/protocol/tcp_server.go#L27C4-L35C5

**Comment by mreiferson** [comment]
Yea, we can probably clean this up now that there's a better standard API, feel free to submit a PR!

**Comment by mreiferson** [comment]
fixed in #1500
