### ISSUE TITLE
NSQ remote hosting issue

### ISSUE THREAD

**Issue by iqra-shams** [nsqio/nsq#1490]
I want to remotely host the NSQ on fly.io. Could not find any guide or reference for hosting NSQ remotely with each app running on separate machine.

I have created 3 different apps for NSQD , NSQLOOKUPD and NQSADMIN. But the NSQD expects the NSQLOOKUPD app to also be running on the same machine. Specifying the --lookupd-tcp-address arg as domain_name:port gives error "port is missing". 

Here is my Dockerfile for nsqd
https://gist.github.com/iqra-shams/213ecbd45f648f3cf618538bbaedcce3

When i load LOOKUPD_TCP_ADDRESS value from the ENV in CMD, it gives the missing port error although i had provided the port in LOOKUPD_TCP_ADDRESS value.

 When i hard code the LOOKUPD_TCP_ADDRESS value in CMD  with port 80 it gives the error that response body size exceed the limit .

When i increase the response body size it gives **memory run out** error 

Kindly provide the guide for NSQ remote hosting

**Comment by sravzpublic** [comment]
Hi @iqra-shams  I have this working docker compose file: https://github.com/sravzpublic/training/blob/master/docker-compose.yaml#L99 see please see if that is helpful.

**Comment by mreiferson** [comment]
I'm not able to reproduce the "port is missing" that you're seeing just running `nsqd` locally with a FQDN + port. I don't see anything in the code that would prevent being able to specify a name that needs resolution and would connect over the WAN.
