### ISSUE TITLE
Rebuild because of Docker base image because of security fixes for stdlib required

### ISSUE THREAD

**Issue by janbaer** [nsqio/nsq#1495]
![screenshot-20240814-151313](https://github.com/user-attachments/assets/22b187d0-91a7-4700-a358-d207503e6f71)

This is the output for the Trivy scan of the current Docker image. There are some security issues in the version of the Go stdlib which was used for building the current version of NSQ 1.3.0. The security issues are fixed in Go in the meantime, so just a rebuild of the Docker container would fix the security issue. So it would be great, if a rebuild of the Docker image could be triggered once and it would also be better to establish an automated build process that is triggering builds automatically when a security fix for the used Go version was released.

I think the rebuild would also be necessary for the binaries. I'm not asure, if a tool like [dependabot](https://github.com/dependabot) could be used for that.

**Comment by mreiferson** [comment]
Agreed, will push out a new release.
