### ISSUE TITLE
 nsqd：Why do we pre-allocate such a large slice space to just a topic?

### ISSUE THREAD

**Issue by fengjun2016** [nsqio/nsq#1496]
When I read this code, I found that a large slice is pre-allocated for the statistics of a topic, but I didn't really understand the intention of doing this. Please take a moment to answer, thank you.

![截屏2024-08-14 22 58 38](https://github.com/user-attachments/assets/29f44916-8fc1-44cf-acbf-313486f99d03)

**Comment by mreiferson** [comment]
As identified in #1492, this looks like a bug!
