### ISSUE TITLE
nsqd: arbitrary 1 hour limit for REQ timeout

### ISSUE THREAD

**Issue by AlekSi** [nsqio/nsq#348]
May it be increased?

**Comment by liaojianqi** [comment]
@mreiferson Execuse me, but would you mind to explain why one hour is a "a sane default"?

**Comment by jehiah** [comment]
@liaojianqi the use-case nsq targets is a "A realtime distributed messaging platform".

p.s. please use forums other than 5 year old closed issues to discuss details of nsq.
