### ISSUE TITLE
nsqadmin: removal of data confirmation

### ISSUE THREAD

**Issue by tj** [nsqio/nsq#401]
either by default or as an option it would be nice to require a very explicit removal confirmation, similar to how GitHub does it. Maybe an input pops and says `type "delete <topicname>" to confirm`. I just accidentally removed 5 million of the wrong messages hahaha, not a big deal in this case at all, I can reload it but at other points in the system that could be reallllll bad

**Comment by ploxiln** [comment]
it seems we got this feature in the web-ui SPA re-design a couple years back
<img width="1039" alt="Screen Shot 2019-09-20 at 2 57 09 PM" src="https://user-images.githubusercontent.com/649835/65351797-fe63e080-dbb6-11e9-98c2-e28cc5d0a3b8.png">
