### ISSUE TITLE
nsqd: websocket support

### ISSUE THREAD

**Issue by ghost** [nsqio/nsq#450]
I need nsqd support websocket, thanks !

**Comment by tritone11** [comment]
I am going to re-open this because 4 years passed, did something changed in plans to add websockets to core NSQ?

This would be an amazing thing to develop web clients without a secondary application

**Comment by penhauer-xiao** [comment]
@tritone11  How is progress, can it support it now?

**Comment by tritone11** [comment]
> @tritone11 How is progress, can it support it now?

Nope.

**Comment by ar-hao** [comment]
NSQ  websocket support，WEB  pub/sub  nsq-http-js   websockets  NSQ！！！

**Comment by ar-hao** [comment]
@tritone11 How is progress, can it support it now?

**Comment by tritone11** [comment]
> @tritone11 How is progress, can it support it now?

No, and as @mreiferson said, they weren't planning to add it to core NSQ

> This isn't something we'll be adding to core NSQ though, so I'm going to close.

**Comment by metrue** [comment]
Build `nsq_to_websocket` like `nsq_to_http` maybe insteresting, and it would not be that. hard.

**Comment by Lercher** [comment]
I guess, it’s not done by building a websocket server alone. It needs an extension to the language client implementation as well, b/c the subscription is the critical element. (@metrue)

—

I found this ticket while searching for a solution to this use case: Suppose you need to exchange messages between two data centers A and B with restrictive firewalls in between that only allow initiating outgoing http/s connections at A and only incoming http/s at B. Publishing A->B is no issue b/c there’s http/s post, but subscribing to messages A->B is only available with nsq‘s own non-http protocol and that’s forbidden at both data centers. Also the other side at B is problematic, b/c the only accepted way of publishing services is opening an http/s endpoint, but for the client a plain TCP connection is required.

Here, using ws seems to be a suitable approach, b/c a probably allowed, established ws connection could support nsq‘s documented protocol for subscription (and of course for publishing).

Therefor a +1 from me for natively supporting ws as a transport besides TCP in nsqd and the client libraries. Thanks.
