### ISSUE TITLE
nsqd: remove use of unsafe package from protocol

### ISSUE THREAD

**Issue by iand** [nsqio/nsq#504]
As explained in the internals doc, currently the unsafe package is used to avoid allocations when parsing message IDs. From [protocol_v2.go](https://github.com/bitly/nsq/blob/365d60c2b5c707915db7fecedff9221d4bf4f49f/nsqd/protocol_v2.go#L888):

```
(*MessageID)(unsafe.Pointer(&p[0]))
```

The internals doc references Go issue [3512](https://code.google.com/p/go/issues/detail?id=3512) as a potential fix. This issue was implemented and closed over 6 months ago and is part of Go 1.3. It might be possible to remove this use of unsafe and replace it with a string conversion, which now does not allocate when used in a map key.

**Comment by mreiferson** [comment]
Going through some old issues...

I looked into this a bit more and it looks like the only case that is optimized away is specifically:

```go
v, ok := m[string(b)]
```

Which isn't going to work without more invasive changes.  Furthermore, beyond academic motivations, I'm not sure what we would even gain by "cleaning" this up.  I suppose the package would be buildable on appengine?

Going to close.  If anyone feels really strongly about this, PRs for review are welcome.
