### ISSUE TITLE
docs: docker shell expansion

### ISSUE THREAD

**Issue by paddycarver** [nsqio/nsq#546]
We should update our Docker docs with examples of how to auto-configure the services using shell expansion and container linking to pull things like IP addresses and ports automatically.

I'd be happy to take this on, but am leaving for a few days so I won't get to it until next weekend at the earliest.

**Comment by mreiferson** [comment]
gonna just leave this one for you @paddyforan :)

**Comment by paddyforan** [comment]
I would've assigned it to me if I could. I have evey expectation that I'll be writing them. :)

**Comment by roderik** [comment]
Is there any documentation available on this? We are trying to deploy nsq with docker on a multiple host system and the port mapping and ip configuration in the docs is not viable

**Comment by mreiferson** [comment]
I'm not actually sure what @paddyforan had in mind for this one, there shouldn't be anything "special" on the NSQ side or in the way we're building the Docker image.

**Comment by mreiferson** [comment]
merging this into #1073
