### ISSUE TITLE
nsqadmin: MemoryDepth is always 0?

### ISSUE THREAD

**Issue by kgdev** [nsqio/nsq#644]
MemoryDepth  int64           `json:"memory_depth"`

It seams that in the admin website, the memory depth is always 0. Could it be fixed?

**Comment by mreiferson** [comment]
do you have a screenshot?  I can't reproduce this.

**Comment by kgdev** [comment]
Here you are. Please take a look. Thanks.

![image](https://cloud.githubusercontent.com/assets/6348456/9707400/017c2d7a-553a-11e5-9784-8801241a855e.png)

**Comment by mreiferson** [comment]
Ahh, I see, what version of `nsqadmin` are you running?

**Comment by kgdev** [comment]
v0.3.6-alpha

**Comment by mreiferson** [comment]
thanks, I've reproduced and I'm fixing this in #421 (fff2944)
