### ISSUE TITLE
nsq_to_nsq: support multiple topics

### ISSUE THREAD

**Issue by ChengHuaUESTC** [nsqio/nsq#648]
When I  run "nsq_to_nsq -nsqd-tcp-address=127.0.0.1:4150 -topic=test1 -destination-nsqd-tcp-address=192.168.22.191:4150", I could in 192.168.22.191 receive message with topic test1.
Now, I want to send and receive multiple topics on only one nsq_to_nsq.
Does nsq_to_nsq support? If it could, how should I do?

**Comment by mreiferson** [comment]
@ChengHuaUESTC `nsq_to_nsq` doesn't currently support multiple topics, however we recently made changes like this to `nsq_to_file` (see https://github.com/nsqio/nsq/pull/334).

If you'd like to make similar changes to `nsq_to_nsq` we would consider them.

Thanks!

**Comment by dash1291** [comment]
@ChengHuaUESTC @mreiferson Is this being worked upon at the moment?

**Comment by mreiferson** [comment]
no, are you interested?

**Comment by dash1291** [comment]
Yeah, would like to give it a shot

**Comment by elvarb** [comment]
Did the shot work?

**Comment by zieckey** [comment]
I like this feature.

**Comment by mreiferson** [comment]
resolved in #912 and #945
