### ISSUE TITLE
E_FIN_FAILED FIN 08fbbf41920a2000 failed ID not in flight

### ISSUE THREAD

**Issue by boneyao** [nsqio/nsq#660]
mutil finish raise error

"E_FIN_FAILED FIN 08fbbf41920a2000 failed ID not in flight"
and close conn
why close conn?

**Comment by mreiferson** [comment]
@boneyao this typically means that the message timed out before your consumer was able to respond with `FIN` or `REQ`.

This isn't the specific reason why the connection was closed, however it's probably related in that your consumer wasn't answering heartbeats either.
