### ISSUE TITLE
nsq_to_file: inconsistent timezones

### ISSUE THREAD

**Issue by ashleymiller** [nsqio/nsq#668]
`nsq_to_file.go` uses a system's local timezone when naming a file by date. This introduces a possible inconsistency where a system is in local time but the timestamps on messages are in GMT. In this case, the file names do not match the timestamps of the messages they contain. For example, a machine running in eastern will contain hours with a timestamp 4 hours ahead of the filename.

**Comment by jehiah** [comment]
@ashleymiller nsq_to_file is intended to create filenames based on when the messages are received by nsq_to_file and written to disk, not when the messages are created and sent to NSQ. This is to allow for scenarios where you pause a channel/topic, etc and keep it deterministic as to when a file is done being written to.

If you need to group messages by file based on the timestamps in your messages you will need to write your own code to do that archiving based on the contents of your message, or post-process the archive files from nsq_to_file.

hope that helps!

**Comment by ploxiln** [comment]
You should consider setting your servers to UTC, but you can also set a single process to UTC, by setting the TZ environment variable:

```
$ date
Wed Oct  7 13:02:33 EDT 2015
$ TZ=UTC date
Wed Oct  7 17:02:34 UTC 2015
```

That said, jehiah's point is that you can't in general depend on the timestamps in the messages matching the period of the file written by nsq_to_file, with a high message rate you'll likely get a few in the period following the one you'd expect. So your other services/systems need to be able to handle that: look in adjacent files, look at the timestamps in the messages to check they're from the desired period, etc.

**Comment by mreiferson** [comment]
This issue isn't about changes to use timestamps from messages but rather being able to adjust the timezone that `nsq_to_file` uses to produce dates for its files.  In any event, `TZ=UTC` is a much simpler solution on a per-process basis, h/t to @ploxiln.

> You should consider setting your servers to UTC

That would be way too reasonable :grin:!
