### ISSUE TITLE
(newbie) I have an embedded kamailio nsq module that I need to subscribe to a topic

### ISSUE THREAD

**Issue by justingbanks** [nsqio/nsq#669]
My embedded kamailio module needs to register for a topic from an external nsqd, and that part seems to work, but the callbacks never seem to be called. The embedded module uses ev loops to handle comms. Here's (what I think) is the relevant bit of code

        rdr = new_nsq_reader(loop, consumer_topic.s, consumer_channel.s, (void *)ctx, NULL, NULL, NULL);
        nsq_reader_connect_to_nsqd(rdr, "12.0.0.100", 4150);
        if (!ev_default_loop (0)) {
                return -1;
        }

**Comment by mreiferson** [comment]
Hi @justingbanks, I think this issue is better opened on the https://github.com/weave-lab/kamailio-nsq repo, as it's unlikely that this has anything to do with `nsqd` (it's possible that it has something to do with https://github.com/nsqio/libnsq though).
