### ISSUE TITLE
Does NSQ support cluster function?

### ISSUE THREAD

**Issue by wangxingge** [nsqio/nsq#678]
I mean when message in the queue and client havn't pop message yet, but server crashed, so the message in this queue will lost, that's why I need nsq cluster.

**Comment by mreiferson** [comment]
see https://github.com/nsqio/nsq/issues/510

**Comment by wangxingge** [comment]
you response so fast.....Nice Man.

**Comment by wangxingge** [comment]
Seems nsqd just resolve the message deliver success when node down, but my question is how to keep the message in the node memory safe, and the message could be fetch from consumer.
