### ISSUE TITLE
nsq_to_http: lack of touch

### ISSUE THREAD

**Issue by hcj116** [nsqio/nsq#681]
In nsq_to_http, set http-timeout=120s, if a request message delivered to sub endpoint need a long term to process, such as 100s, nsqd will requeue this message. Hope **touch** action would be added to support such operation.

**Comment by mreiferson** [comment]
@hcj116 it is unlikely for us to implement `TOUCH` in these apps, but you can set `--consumer-opt=msg_timeout,120s` instead
