### ISSUE TITLE
Message situation

### ISSUE THREAD

**Issue by esk1989** [nsqio/nsq#682]
Is there any way to see the message of the situation on the list (by id) trough the api?
Example know the position in list...

**Comment by mreiferson** [comment]
Unfortunately no, there's no state kept to be able to answer that question.

**Comment by esk1989** [comment]
Nor based on the message's position?

**Comment by mreiferson** [comment]
Because of some of the features NSQ supports like requeues, defers, etc. it is only possible to reference a message by ID.
