### ISSUE TITLE
one topic must have one nsq_to_http to consumer?

### ISSUE THREAD

**Issue by guojun1992** [nsqio/nsq#686]
i have two server,how i use nsq cluster?

i use nsq on the two server (the two server are same nsq),but i test i send 4 times,only 2 times has recived.

./nsq_to_http --topic=test22 --lookupd-http-address=xxx --get

**Comment by mreiferson** [comment]
`nsq_to_http` is currently 1:1 with topics, so you would run more than one `nsq_to_http` instance.
