### ISSUE TITLE
nsqlookupd: frequent HTTP 599s with pynsq

### ISSUE THREAD

**Issue by gtaylor** [nsqio/nsq#687]
We're seeing frequent HTTP 599s from lookupd on our application running pynsq:
```
[backlog:the_channel] lookupd http://queue-0:4161/lookup?topic=backlog query error: HTTP 599: Timeout
```

![image](https://cloud.githubusercontent.com/assets/75556/11228846/a20bb85e-8d44-11e5-9feb-0841aad07c6f.png)
As you can see, this isn't the highest of volume in terms of NSQ setups. We have one VM right now running nsqlookupd, nsqd, and nsqadmin. The gap in the graphs you are seeing is us upgrading to 0.3.6 (still seeing the HTTP 599s after upgrade).

Any ideas on what might be happening?

**Comment by jehiah** [comment]
If you are seeing timeouts from your client querying nsqlookupd, that could be related to resource (CPU) contention on the client. Do you have similar visibility there?

**Comment by mreiferson** [comment]
What is the actual CPU usage on the host (_not_ load)?

**Comment by gtaylor** [comment]
The nsqd VM tends to hover around 1-3%. Insignificant.

The consumers tend to sit around 50% (15 minute load avg of 0.50) of an 8-core VM. Minimal memory usage, no other signs of duress.

**Comment by mreiferson** [comment]
Do the consumers perform any operations that might block the IOloop?

**Comment by gtaylor** [comment]
There are some numpy calculations, but they don't block for any extended period of time. We're using pynsq on Python 2.7.3.

It looks like we are seeing that warning sent here (line 583 of nsq/reader.py):

```python
    def _finish_query_lookupd(self, response, lookupd_url):
        if response.error:
            logger.warning('[%s] lookupd %s query error: %s',
                           self.name, lookupd_url, response.error)
            return
```

I can move this to the pynsq issue tracker if it ends up being more of a client issue, but I wasn't sure on which side it'd be. I'm seeing the HTTP 599s in the server logs.

**Comment by mreiferson** [comment]
> There are some numpy calculations, but they don't block for any extended period of time. We're using pynsq on Python 2.7.3.

Are you sure?  Blocking the IOloop could absolutely be contributing to this.  Are other consumers on this cluster experiencing the same issues?  If not, it might implicate the the work this specific consumer is doing.

> I can move this to the pynsq issue tracker if it ends up being more of a client issue, but I wasn't sure on which side it'd be. I'm seeing the HTTP 599s in the server logs.

What server logs?

**Comment by jehiah** [comment]
good thoughts @mreiferson. The more i think about it, stalling the `IOloop` (with any blocking cpu intensive tasks, or any non-tornado network IO like mysql, etc) would look exactly like a `599` error which is the client side timing out before it's done anything on the request.

**Comment by gtaylor** [comment]
I'm not super familiar with Tornado. Any tips for confirming or working around this?

**Comment by mreiferson** [comment]
Well, I'd still like to see those "server logs"?  Did you mean the `nsqlookupd` server logs?

Do you have any other consumers running?  Are they having issues making requests to `nsqlookupd`?  If not, it would implicate the consumer having problems (or the host it's running on, etc.).

**Comment by gtaylor** [comment]
I think I may have been confused in seeing "HTTP 599", which caused me to assume that we were actually getting a 599 from the server. By "server logs", I was looking at the consumer. I can't find the 599s in nslookupd's logs, so it appears that tornado may just be using 599 (which is super weird).

I'll look into this later, but maybe we can adjust the timeout for our nsqlookupd requests somehow. I think tornado has support for this, but I'll see if pynsq exposes it.

**Comment by mreiferson** [comment]
Cool, closing.
