### ISSUE TITLE
nsq cannot bind ipv4 port in CentOS 7.1

### ISSUE THREAD

**Issue by hebl** [nsqio/nsq#688]
In CentOS 7.1,

```
$./nsqlookupd &

$netstat -lantp | grep 4160

tcp6       0      0 :::4161                 :::*                    LISTEN      25556/./nsqlookupd
```
Only ipv6, not ipv4.

But in CentOS 6.x, nsq can bind ipv4.

**Comment by mreiferson** [comment]
@hebl you should be able to specify explicit address and port on the `nsqlookupd` command line, e.g.:

`./nsqlookupd --http-address=127.0.0.1:4160`
