### ISSUE TITLE
more nsqd may have more nsqlookupd?

### ISSUE THREAD

**Issue by guojun1992** [nsqio/nsq#689]
hi all, I have more nsqd server,one nsqlookupd,but once the only one nsqlookupd not work,the cluster will not be heathly,I think nsqlookupd may have more than one server? how can I do?

**Comment by yuanyangen** [comment]
guolaishi bangbangda

**Comment by ploxiln** [comment]
```
[pierce@plo-pro dockerdev]$ nsqd --help
Usage of nsqd:
...
  -lookupd-tcp-address value
    	lookupd TCP address (may be given multiple times)
...
```

**Comment by guojun1992** [comment]
thanks for your reply.
