### ISSUE TITLE
How to deploy and configure nsq in distributed enviroment?

### ISSUE THREAD

**Issue by gzliudan** [nsqio/nsq#692]
Sorry to trouble you again. Should I run nsqd on every server of producer, run nsqlookupd on every server of comsumer? And how to configure them, so they can find each other? There's no examples in http://nsq.io/deployment/production.html

**Comment by gzliudan** [comment]
And how to make some topics save to disk first, make it 100% safe. And how to make other some topics never save to disk for high performance, since user don't care lost some messages?

**Comment by ploxiln** [comment]
http://nsq.io/deployment/topology_patterns.html#distributed-systems

**Comment by gzliudan** [comment]
I tested it,  it must run nsqd as below formats in distributed enviroment:
nsqd --lookupd-tcp-address=host1:4160 --lookupd-tcp-address=host2:4160 --lookupd-tcp-address=host3:4160
