### ISSUE TITLE
How to connect nsq with golang?

### ISSUE THREAD

**Issue by gzliudan** [nsqio/nsq#694]
Below is my test code, the problem is:
1. producer can't connect to nsqd port 4151
2. consumer can't connect to nsqd port 4151
3. consumer can't connect o nsqlookupd port 4160
4. how does comsumer connect to nsqd or nsqlookupd TCP port with long term TCP connection?

package main

import (
  "log"
  "sync"
  "github.com/bitly/go-nsq"
)

func main() {
  config := nsq.NewConfig()
  // w, _ := nsq.NewProducer("master56:4150", config) // can work
  w, _ := nsq.NewProducer("master56:4151", config) // not work
  err := w.Publish("test", []byte("hello"))
  if err != nil {
      log.Panic("Could not connect")
  }

  w.Stop()

  wg := &sync.WaitGroup{}
  wg.Add(1)
  config = nsq.NewConfig()
  q, _ := nsq.NewConsumer("test", "ch", config)
  q.AddHandler(nsq.HandlerFunc(func(message *nsq.Message) error {
      log.Printf("Got a message: %s", message.Body)
      wg.Done()
      return nil
  }))
  // err = q.ConnectToNSQD("master56:4150") // can work
  // err = q.ConnectToNSQD("master56:4151") // not work
  // err = q.ConnectToNSQLookupds([]string{"master56:4161"}) // can work
  err = q.ConnectToNSQLookupds([]string{"master56:4160"}) // not work
  if err != nil {
      log.Panic("Could not connect")
  }
  wg.Wait()
}

**Comment by jehiah** [comment]
@gzliudan this type of question is better suited to the mailing list http://nsq.io/community.html

Consumers and producers make persistent connections to nsqd port 4150. The nsqd http port (4151) is for administrative actions, and HTTP publishing.

Clients poll nsqlookupd via HTTP port 4161, they do not make persistent connections. nsqd makes persistent TCP connections to nsqlookupd over port 4160.
