### ISSUE TITLE
Weird behaviour when publishing / consuming Go structs which contain an int value and have been serialized using encoding/gob

### ISSUE THREAD

**Issue by justphil** [nsqio/nsq#695]
Hello everybody!

First of all thank you for this very interesting piece of software. :)

I'm about to evaluate nsq for a new project which makes extensive use of golang. And I was curious how nsq performs when publishing / consuming larger Go structs. Therefore I wrote a simple producer app that produces corresponding structs which are serialized by [encoding/gob](https://golang.org/pkg/encoding/gob/) and afterwards published to nsq. On the other side there is a consumer app which takes the bytes and tries to recreate the original struct - again by using [encoding/gob](https://golang.org/pkg/encoding/gob/). Generally speaking everything works as expected, but there seems to be an issue with int values that are part of the struct. Here is a minimal example which reproduces the problem.

This is the producer code:
~~~ go
func main() {
	pub, err := nsq.NewProducer("192.168.99.100:4150", nsq.NewConfig())
	if err != nil {
		log.Fatalln("couldn't connect to nsq due to", err)
	}
	log.Println("successfully connected to nsq!")

	Publish(pub, 0)
	Publish(pub, 1)
	Publish(pub, 2)
	Publish(pub, 0)

	pub.Stop()
}

func Publish(pub *nsq.Producer, i int) {
	c := &Container{i}
	buf := new(bytes.Buffer)
	enc := gob.NewEncoder(buf)
	enc.Encode(c)
	err := pub.Publish("nsq-int-bug", buf.Bytes())
	if err != nil {
		log.Fatalln("couldn't publish container due to:", err)
	} else {
		log.Println("published container", c)
	}
}

type Container struct {
	Int int
}
~~~

This is the consumer code:
~~~ go
func main() {
	log.Println("connecting to nsq...")
	q, err := nsq.NewConsumer("nsq-int-bug", "ch", nsq.NewConfig())
	if err != nil {
		log.Fatalln("couldn't create nsq consumer due to", err)
	}

	container := &Container{}
	q.AddHandler(nsq.HandlerFunc(func(m *nsq.Message) error {
		buf := bytes.NewBuffer(m.Body)
		dec := gob.NewDecoder(buf)
		err = dec.Decode(container)
		if err != nil {
			log.Println("error while decoding container:", err)
		}

		log.Printf("received container: %v\n", container)
		return nil
	}))

	if err := q.ConnectToNSQLookupd("192.168.99.100:4161"); err != nil {
		log.Fatalln("couldn't connect to nsq due to", err)
	}

	select {} // quick and dirty blocking call
}

type Container struct {
	Int int
}
~~~

Output producer:
```
2015/12/07 21:25:32 successfully connected to nsq!
2015/12/07 21:25:32 INF    1 (192.168.99.100:4150) connecting to nsqd
2015/12/07 21:25:34 published container &{0}
2015/12/07 21:25:34 published container &{1}
2015/12/07 21:25:34 published container &{2}
2015/12/07 21:25:34 published container &{0}
```

Output consumer:
```
2015/12/07 21:25:09 connecting to nsq...
2015/12/07 21:25:09 INF    1 [nsq-int-bug/ch] querying nsqlookupd http://192.168.99.100:4161/lookup?topic=nsq-int-bug
2015/12/07 21:26:14 INF    1 [nsq-int-bug/ch] (192.168.99.100:4150) connecting to nsqd
2015/12/07 21:26:14 received container: &{0}
2015/12/07 21:26:14 received container: &{1}
2015/12/07 21:26:14 received container: &{2}
2015/12/07 21:26:14 received container: &{2} // Why 2?!
```

It seems that the consumer always receives the highest int value that has ever been published.
Is this a bug or am I missing something?

Btw.: This only happens if an int value is part of a struct. This does NOT happen when I publish sole int values.

Environment:
```
[nsqlookupd] 2015/12/07 16:30:47.834255 nsqlookupd v0.3.6 (built w/go1.5.1)
[nsqd] 2015/12/07 16:39:07.047213 nsqd v0.3.6 (built w/go1.5.1)
Both running within Docker containers (official image for nsq)
My producer / consumer apps have been compiled with go1.5.2 darwin/amd64 on Mac OSX 10.10.5.
```

Thank you!
Phil

**Comment by mreiferson** [comment]
@justphil my assumption is that this has to do with the code in your consumer (and Go's gob decoding w/r/t "zero values") and not NSQ.

Specifically, you're reusing the `container` variable from the outer scope.  Does it exhibit this behavior if you create a new `Container` _inside_ the message handler?

**Comment by justphil** [comment]
Thank you for the hint, @mreiferson!
Putting the `Container` creation into the message handler solves the problem. So in fact this has to do with gob's decoding behavior when dealing with zero values.

False alarm! Issue can be closed. :)

Bye,
Phil
