### ISSUE TITLE
nsqd: more 'ESTABLISHED' tcp connection than expected and maybe lead to ERROR "failed to read command ... i/o timeout"

### ISSUE THREAD

**Issue by slvher** [nsqio/nsq#696]
Dear,

I use nsq as message queue about three months ago and the following ERROR occurs more and more recently:
```
[nsqd] 2015/12/22 09:11:35.143346 ERROR: client(a1.b1.c1.d1:51971) - failed to read command - read tcp a0.b0.c0.d0:4150->a1.b1.c1.d1:51971: i/o timeout 

NOTE: I replaced ip string of tcp peers in above log with a0.b0.c0.d0 and a1.b1.c1.d1 (they stands for nsqd side and producer side, respectively)
:)
```
nsqd is started with the following args:
```
/home/work/tools/bin/nsqd --lookupd-tcp-address=a0.b0.c0.d0:4160 --data-path=/home/work/tools/nsq/datas --broadcast-address=a0.b0.c0.d0 --http-address=a0.b0.c0.d0:4151 --tcp-address=a0.b0.c0.d0:4150
```

At the meaning time, time-out error also exists at the producer side.

Producer is tornado-based web application and [AsyncHTTPClient](http://www.tornadoweb.org/en/stable/httpclient.html) is used when pub item to nsq via HTTP API, request_timeout is 2s and max_clients is 100.

here is the result of 'netstat -tnp | awk '{print $6}' | sort | uniq -c':
1) the nsqd side: about 6000 'ESTABLISHED' tcp connections exist between a0.b0.c0.d0 and a1.b1.c1.d1
2) the producer side: about 300 'ESTABLISHED' tcp connections exist between a0.b0.c0.d0 and a1.b1.c1.d1

I diffed the above results and it showed that there are many 'unexpected' tcp connections which exists at the nsqd side while not exists at the producer side at all !

at the nsqd side, the result of 'lsof'  also showed the 'unexpected' connections indeed exists.

more weirder case:
those unexpected tcp connections seems would keep-alive for a very long time !

but...
**where are they from?
why those connections seems not consistent between nsqd side and producer side?**

To resolve the "i/o timeout" error,  the nsqd process was restarted. 

At the beginning after restart, the tcp connection between nsqd and producer seems consistent and the "i/o timeout" error log disappeared nealy.

However, a few hours later, the same situation reoccured:
netstat about 'ESTABLISHED' TCP connection between nsqd and producer became inconsistent again.

Thank you for reading the long description above, and my problem are:
**1) why inconsistent of netstat result exists between nsqd and producer ?
2) if potential "connection leak" exists in nsqd ?
3) if this 'connection leak' leads to 'i/o timeout' error ?**

Maybe the above problem can be avoid by using pynsq.writer or sync http client when pub item to nsq, but I wonder the root reason caused the problem. 

Any reply is grateful ~
Thank you very much !

Best Regards.

**Comment by mreiferson** [comment]
There are way too many variables to really debug this for you, specifically how the environment is configured that you're running `nsqd` and these applications in.

I don't _think_ the `I/O timeout` is necessarily related and we don't know of any connection leaks that exist inside `nsqd`.

We have many large scale deployments that utilize Python/Tornado/HTTP to publish messages to `nsqd` with long-term stability.
