### ISSUE TITLE
nsqd: hitting consumer limit of 30K messages

### ISSUE THREAD

**Issue by carlfn** [nsqio/nsq#697]
We have  a service pumping 200K messages per second onto the queue, but are unable to consume that number.

With one consumer, we pull of 30K messages per second.  When we add a second consumer, they each pull off 18K per second.  The third consumer causes them all to pull off 12K per second, and so forth.  It seems like there is a hard limit to the number of messages you can pull off regardless of the number of consumers and how they're distributed.  Has this been a common issue?

This test was done while another process was publishing too the queue.  With nothing publishing, the speeds too increase, but the overall problem still exists.

**Comment by mreiferson** [comment]
What is the configuration and topology of this cluster?  How are the `nsqd` configured and run, what version?  What client library are you using to consume the data, can we see that code?  What is the CPU/memory/disk util for the `nsqd` hosts?

**Comment by carlfn** [comment]
We had NSQ running on a 32core 60GB ec2 instance with a 10000 iops drive and a 10 gbit ethernet.  We were dumping approximately 250,000 messages/sec on the queue but were only able to read off messages at approximately 30-40K messages/sec from a similar machine as the one above. Adding more readers/machines didn't help. It just slowed all the readers down to a total of 30K messages per second.  Stopping the publishing job increased the speed slightly, but not significantly.  Each message size is approximately 1-2K
CPU and mem usage was low.  Ran NSQ with a riduculously high mem-queue-size to eliminate disk as the issue.

**Comment by jehiah** [comment]
@carlfn Can you clarify what client you are using to consume data, and specifically how long per-message processing takes, and how you have max_in_flight configured? Do you see the same results if you use `nsq_tail ... >/dev/null` or `nsq_to_file` ?

If you can share some screenshots of `nsqadmin` showing your channel, and the client connections when you are observing this, that would also be helpful for troubleshooting.

**Comment by carlfn** [comment]
@jehiah Updated my comment above.  

Won't be able to do a run again for a bit, but will update you with these details when I can.

**Comment by mreiferson** [comment]
@carlfn what is the value of `n.numConcurrent`?  You probably want a really high `MaxInFlight` but number of handlers == number of cores on the consumer host.

**Comment by mreiferson** [comment]
@carlfn I've recently confirmed the ["Distributed Performance" benchmarks](http://nsq.io/overview/performance.html#distributed-performance) so, if anything, this is a [`go-nsq`](https://github.com/nsqio/go-nsq) issue.  Notably, those benchmarks _do not_ use a `go-nsq` based consumer by design, which means it can't be something fundamental to `nsqd`.

Let's continue the conversation there if you're still experiencing performance issues.

Thanks!
