### ISSUE TITLE
[nsqd] Does a 'detect dead peer' mechanism enabled by default in nsqd to handle 'half-open' connections ?

### ISSUE THREAD

**Issue by slvher** [nsqio/nsq#698]
Dear,

First of all, Merry Christmas ~

I deploy nsqd process and msg producer process on different boxes, and a third-party client is used to pub msg from producer to nsq via http. 

Recently, I found there are many 'ESTABLISHED' tcp connections existed on the box where nsqd is deployed on, while those connections did not exist on the producer side at all. These half-open connections seem to would last forever and not be closed automatically.

The values of net.ipv4.tcp_keepalive_time, net.ipv4.tcp_keepalive_intvl & net.ipv4.tcp_keepalive_probes is tuned via sysctl already, but it seemed they did not take effect because the number of half-open connections didn't decrease to less.

I realized later that maybe the "SO_KEEPALIVE" socket option should be set to make sure the server process (here is the nsqd process) could detect a dead tcp peer and close the broken connection actively. And I found the built-in net/http package is used by nsqd and SO_KEEPALIVE option is disabled by default when TCPConn is created by [tcpServer](https://github.com/nsqio/nsq/blob/master/nsqd/tcp.go) or [newHTTPServer](https://github.com/nsqio/nsq/blob/master/nsqd/http.go), is it right ?

Thus, I wonder if nsqd can detect the dead peer of a TCP connection and close such half-open connection automatically to avoid potential "connection leak" ? 
If yes, should I must modify nsqd's source code to call TCPConn.SetKeepAlive() explicitly to achieve that purpose ?  

Looking forward to your reply.
Best Regards.

**Comment by mreiferson** [comment]
Thanks for your question.

As I mentioned in the last issue #696, this is really hard for us to debug for you.  Since it seems like an isolated incident and we haven't seen other wide spread reports of this or similar issues, it seems most likely the result of your particular environment/configuration.  Turning on `SO_KEEPALIVE` would only mask the problem, you need to figure out why `nsqd` isn't getting the close of the socket from the client (I suggest looking at some tcpdumps).

**Comment by slvher** [comment]
I also think the root cause is from the producer side, maybe the http client we used.
I will try to use tcpdump to trace some connection traffic.

Thank you very much for the reply and the suggestion. 
:)

**Comment by darrengeek** [comment]
We also encountered such a fake connection. The client is abnormally closed and FIN is not sent, resulting in the server still in the ESTABLISHED state, but the server should also have a keep-alive mechanism to clean up fake connections.
nsq version：nsq-1.0.0
