### ISSUE TITLE
v0.3.2 nsqd：  NOTICE: temporary Accept() failure - accept tcp [::]:4160: too many open files

### ISSUE THREAD

**Issue by zhang8h** [nsqio/nsq#711]
v0.3.2  
NOTICE: temporary Accept() failure - accept tcp [::]:4160: too many open files
Cause cup to reach 100%

**Comment by mreiferson** [comment]
@zhang8h you need to update the file descriptor limit for the account you're running `nsqd` under

**Comment by zhang8h** [comment]
@mreiferson    Which command line option is

**Comment by ploxiln** [comment]
It's not an option for nsqd - it's an option for the environment it runs in. You can set the open-file-limit of your shell with the (shell-builtin) command `ulimit -n 1024`, and you can see what it currently is with `ulimit -n`. But there's a limit above which it can't go higher (the "hard limit"), unless you have root permissions, or you configure it elsewhere in the operating system.

**Comment by zhang8h** [comment]
@ploxiln Thank you for your reply.I checked the value of this setting is 65535
This error has prompted the emergence of a few days.Thank you

**Comment by zhang8h** [comment]
![Uploading aa.png…]()

**Comment by mreiferson** [comment]
@zhang8h this still isn't something we can really debug for you, look at how many open files `nsqd` has and confirm that it's actually running under those increase limits.

**Comment by zhang8h** [comment]
Thank you very much for the reply and the suggestion.

**Comment by zhang8h** [comment]
The problem has been solved, it is supervisor's problem.

**Comment by renodesper** [comment]
I'm sorry to ask this in closed issue, but my problem is related to this issue. How can we know the total of opened files by nsq? My ulimit is 1024 and I don't use supervisor to run nsq on my system.
