### ISSUE TITLE
nsqadmin: config endpoint similar to nsqd

### ISSUE THREAD

**Issue by harlow** [nsqio/nsq#714]
re: the new `/config` endpoint in for `nsqd` #601

Wanted to put a note in here before submitting a PR. Are nsq maintainers on board with adding a `/config` endpoint to `nsqadmin` so it can also be dynamically configured via HTTP PUT?

**Comment by jehiah** [comment]
`nsqd` has specific motivations against restarting it (you don't want to disrupt receiving messages). `nsqadmin` on the other hand is stateless so restarting it doesn't have quite the same concerns.

`nsqd`'s http interface is designed to be on a trusted network; `nsqadmin` again isn't quite the same, and while it does expose administrative actions, changing configuration via the same interface feels somewhat different.

All that to say, i'm not sure at the moment how i feel about a `/config` endpoint for nsqadmin. @mreiferson thoughts?

**Comment by harlow** [comment]
@jehiah thanks for the note -- I think that all makes sense. I'll play around with a script that simply restarts `nsqadmin` if I see a change in `nsqlookupd` addresses.

**Comment by mreiferson** [comment]
@jehiah makes some good points.  OTOH, it would provide some symmetry for a deployment that might be beneficial.

@harlow let's see how that restart script works out in practice.  Let us know how that goes!

**Comment by harlow** [comment]
> OTOH, it would provide some symmetry for a deployment that might be beneficial.

After poking around a little with a restart I'm feeling the same way. With a `/config` endpoint on Admin I could run the same discovery sidecar w/ an Admin URL and it could be configured at runtime the same way i'm doing with nsqd.

```
"http://<nsqd>:<port>/config/nsqlookupd_tcp_addresses"
```
and
```
"http://<admin>:<port>/config/nsqlookupd_tcp_addresses"
```

In the short term I can def get the restart to work without a config endpoint, but would be nice if both services could be configured the same way.

Happy to close this issue for now if we want to wait until NSQ team decides on a discovery mechanism.

**Comment by mreiferson** [comment]
ping @jehiah :)

**Comment by ernoaapa** [comment]
Would be awesome to get @harlow suggested API because then running NSQ on Kubernetes would be hassle free :)

**Comment by kenjones-cisco** [comment]
I think #775 resolves this one as well.

**Comment by mreiferson** [comment]
Heh, forgot about this one - seems like we were originally on the fence and I probably should have given @jehiah a chance to review the PR that just landed 🚨 .

Closing.
