### ISSUE TITLE
nsqd: --tls-required option resolution failure

### ISSUE THREAD

**Issue by IceiceFire** [nsqio/nsq#724]
```
[cloud@localhost bin]$ ./nsqlookupd 
[nsqlookupd] 2016/03/07 20:40:10.220187 nsqlookupd v0.3.7 (built w/go1.6)
[nsqlookupd] 2016/03/07 20:40:10.220457 TCP: listening on [::]:4160
[nsqlookupd] 2016/03/07 20:40:10.220552 HTTP: listening on [::]:4161

[cloud@localhost bin]$ ./nsqd --lookupd-tcp-address=127.0.0.1:4160
2016/03/07 20:41:01 ERROR: option resolution failed to coerce 0 for TLSRequired (0) - invalid int64 value type main.tlsRequiredOption
```

**Comment by mreiferson** [comment]
@IceiceFire what version of NSQ?

**Comment by IceiceFire** [comment]
v0.3.7

**Comment by mreiferson** [comment]
```
$ nsqd --lookupd-tcp-address=127.0.0.1:4160
[nsqd] 2016/03/08 09:56:18.455126 nsqd v0.3.7 (built w/go1.6)
[nsqd] 2016/03/08 09:56:18.455563 ID: 292
[nsqd] 2016/03/08 09:56:18.455618 NSQ: persisting topic/channel metadata to nsqd.292.dat
[nsqd] 2016/03/08 09:56:18.464998 TCP: listening on [::]:4150
[nsqd] 2016/03/08 09:56:18.465028 HTTP: listening on [::]:4151
[nsqd] 2016/03/08 09:56:18.465812 LOOKUP(127.0.0.1:4160): adding peer
[nsqd] 2016/03/08 09:56:18.465836 LOOKUP connecting to 127.0.0.1:4160
```

Cannot reproduce?

**Comment by ambarket** [comment]
@IceiceFire If you're still looking for an answer, the problem for me was that it was attempting to run a version of nsqd that was automatically compiled from the source when I imported the nsq package into my $GOPATH. Using the binaries downloaded directly from the nsq.io site works great.

**Comment by IceiceFire** [comment]
@ambarket  

Problem solved, thank you

**Comment by honsty** [comment]
@IceiceFire   what caused it？

**Comment by jinhao** [comment]
@IceiceFire what caused it？ I also got this error。

**Comment by ploxiln** [comment]
Don't use go-get for nsqd. Use one of the pre-compiled binary releases, or use gpm before building (see http://nsq.io/deployment/installing.html#building-from-source).

Just "go get" doesn't work:

```
[pierce@plo-pro scratch]$ export GOPATH=$PWD/newgopath
[pierce@plo-pro scratch]$ export PATH=$GOPATH/bin:$PATH
[pierce@plo-pro scratch]$ mkdir -p $GOPATH
[pierce@plo-pro scratch]$ go get github.com/nsqio/nsq/apps/nsqd
[pierce@plo-pro scratch]$ which nsqd
/Users/pierce/scratch/newgopath/bin/nsqd
[pierce@plo-pro scratch]$ nsqd --lookupd-tcp-address=127.0.0.1:4160
2016/03/24 16:13:52 ERROR: option resolution failed to coerce 0 for TLSRequired (0) - invalid int64 value type main.tlsRequiredOption
```

The problem is that a dependency changed in an in-compatible way. Likely github.com/mreiferson/go-options is the one. Godeps specifies for each dependency a recent-enough version which should definitely work.

(How versioning dependencies would work in a more perfect world is a separate issue :)

**Comment by Chong-Li** [comment]
Just give "TLS" related parameters some value. For example, start the daemon like the following:
./nsqd -tls-required=false -tls-min-version='ssl3.0'

The reason for this error seems like options (in github.com/mreiferson/go-options) does not accept the default value (for tls_required and tls_min_version) provided by nsqd.
