### ISSUE TITLE
nsqadmin: JSON warning messages

### ISSUE THREAD

**Issue by gjohnson** [nsqio/nsq#727]
How would one make these go away? 

![screen shot 2016-03-16 at 9 46 21 am](https://cloud.githubusercontent.com/assets/67717/13814423/93100c8a-eb5c-11e5-9f83-5859e96d0a1e.png)

**Comment by mreiferson** [comment]
hey @gjohnson I'm ... very confused.

What page are you looking at when you see those messages?

**Comment by mreiferson** [comment]
anything more interesting in the `nsqadmin` logs?

**Comment by mreiferson** [comment]
@gjohnson is this still happening, were you able to get any logs?

**Comment by mreiferson** [comment]
I've seen this from time to time, hopefully next time I'll remember to grab some logs.

**Comment by ploxiln** [comment]
I think this was fixed
