### ISSUE TITLE
ERROR: failed to read protocol version - EOF

### ISSUE THREAD

**Issue by whatisgolang** [nsqio/nsq#728]
I checked nsqd  and nslookup all OK,but nsqd and nslookup logging ERROR: failed to read protocol version - EOF ,how handle this error, thinks

**Comment by jehiah** [comment]
@whatisgolang can you provide some exactly logs from nsqd and nsqlookupd, and your configuration for both?

**Comment by whatisgolang** [comment]
@jehiah Thank you for your reply
the nsqd logs: real ip changed X
4160): sending heartbeat
[nsqd] 2016/03/18 23:17:33.179962 LOOKUPD(x.x.x.135:4160): sending heartbeat
[nsqd] 2016/03/18 23:17:33.976228 TCP: new client(x.x.x2.124:37408)
[nsqd] 2016/03/18 23:17:33.976252 ERROR: failed to read protocol version - EOF
[nsqd] 2016/03/18 23:17:36.598805 200 GET /stats?format=json (x.x.x.136:35342) 36.875µs
[nsqd] 2016/03/18 23:17:48.179256 LOOKUPD(x.x.x.133:4160): sending heartbeat
[nsqd] 2016/03/18 23:17:48.179757 LOOKUPD(x.x.x.134:4160): sending heartbeat
[nsqd] 2016/03/18 23:17:48.180040 LOOKUPD(x.x.x.135:4160): sending heartbeat

**Comment by jehiah** [comment]
So it looks like nsqd got a connection from `x.x.x2.124` and that connection didn't complete the handshake, so it ended w/ failure to read protocol. That's a totally normal response to a connection that doesn't finish handshake. 

If you can provide any indication why you think that's a unexpected result please re-open w/ more context about the client making connections from that IP, and logs from the client perspective.

**Comment by kant111** [comment]
Same error here And it happens a lot.

**Comment by robinwangrubin** [comment]
Same error here And it happens a lot.

**Comment by Ghilteras** [comment]
we get spammed by this for no reason whatsoever

**Comment by Ghilteras** [comment]
@jehiah you really should reopen this issue tbh

**Comment by mreiferson** [comment]
This log message represents a client failing to complete a connection, are you proposing it be a "warning" or that it not get logged at all?
