### ISSUE TITLE
docs: offer a standard License

### ISSUE THREAD

**Issue by randomchance** [nsqio/nsq#735]
While I personally appreciate the simple and permissive License that the project currently has, having a custom License makes it much more difficult to use in a large corporate environment. 

We have certain Licenses on an approved list (*MIT, FreeBSD, etc...*) and anything else has to be run through legal, which unfortunately can add enough overhead to make some projects non-viable. 

I'm not sure what the best way to ease the licensing friction is ... reading the current license, it seems like it would be possible to dual license the project, keeping the current license but also allowing use under the MIT license or something similar.

Obviously this is not a massive problem, but it would make it easier to use in my company so I assume it would help others as well. 

Thanks!

**Comment by ploxiln** [comment]
The current license text *is* the MIT license.

**Comment by randomchance** [comment]
ugh, this is what I get for trying to juggle too many things...

Would it be possible to add this portion:

```
The MIT License (MIT)
Copyright (c) <year> <copyright holders>

<License Text>
```

To the top of the existing license file? That would allow me to check the appropriate boxes and satisfy legal, and hopefully help others from looking quite as silly as I feel right now.

**Comment by mreiferson** [comment]
If you want to submit a PR, I'm fine with that.

**Comment by mreiferson** [comment]
(thanks @ploxiln too)

**Comment by randomchance** [comment]
Cool, I will see if I can do it from work, if not I'll do it from home. I really appreciate the fast responses!
