### ISSUE TITLE
nsqadmin: root_url

### ISSUE THREAD

**Issue by freeseacher** [nsqio/nsq#737]
Please add support for root_url in nsqadmin. to make it work with reverse proxy better. 
tnx!

**Comment by mreiferson** [comment]
sounds fine to me, PRs welcome!

**Comment by jhowtan** [comment]
Hey we need this too! Seems like there's a PR in for it, https://github.com/nsqio/nsq/pull/856
Could we get this in?

**Comment by mreiferson** [comment]
@jhowtan looks like there's some discussion on that PR about approach. If you're interested in taking a pass at it please do!

**Comment by mreiferson** [comment]
closing in favor of some resolution in #856
