### ISSUE TITLE
Max number of concurrent connections

### ISSUE THREAD

**Issue by an0sv** [nsqio/nsq#744]
It is possible to control the connection backlog size for nsqd? We get connection occasional connection refused from nsqd when issuing many simultaneous http pub:s

**Comment by jehiah** [comment]
@an0sv it's unlikely we'll implement special socket listen options like changing the backlog size. You should look into adjusting your client to re-using HTTP connections, or upgrade to publish messages over the more performant TCP protocol. I'd also make sure you are using v0.3.7 or later.
