### ISSUE TITLE
nsq_pubsub and message separation

### ISSUE THREAD

**Issue by an0sv** [nsqio/nsq#745]
How can one robustly  separate the incoming stream of messages written by the nsq_pubsub utility?  looks like it only separates the messages with a single newline '\n'. But the messages can contain newlines which makes it hard to separate messages.

**Comment by jehiah** [comment]
@an0sv If your messages contain newlines, the convenience utilities `nsq_pubsub`, `nsq_to_file` and `nsq_tail` won't be of as much use to you and you'll need to consume using one of the [client libraries](http://nsq.io/clients/client_libraries.html).
