### ISSUE TITLE
nsqadmin: error under moderate load

### ISSUE THREAD

**Issue by an0sv** [nsqio/nsq#748]
When putting a bit of a load on one of our NSQ instances we get this when accessing the NSQ web gui. The load is not that high a just couple of thousand messages per second. We are running version 3.7 on CentOS 7 128 GB, 32 Core server (E5-2630 v3)

>>
PSTREAM_ERROR: Failed to query any nsqd: Get http://127.0.0.1:4251/stats?format=json: dial tcp 127.0.0.1:4251: connect: cannot assign requested address
>>

**Comment by ploxiln** [comment]
Is it possible that there are many (many) client connections to nsqd, either http or tcp, and local ephemeral ports are exhausted? Look in netstat output

**Comment by an0sv** [comment]
Ok, it seems that we have peaks of quite a lot of connections. Its likely that this is the cause. 
Thanks for the quick response and help!
