### ISSUE TITLE
Is it possible to return a result to procedure after consumer handled it in queue?

### ISSUE THREAD

**Issue by vincentruan** [nsqio/nsq#749]
Hi, 
As the title said, I wanna use NSQ to implement a remote method call, so is it possible to send a result to procedure in the same channel after consumer handled it? Looking forward for your answer.
Best regards.

**Comment by judwhite** [comment]
no, if want that functionality you could publish to a reply topic.

**Comment by vincentruan** [comment]
But it is hard to redirect the reply message to the procedure's machine in distributed system.

![image](https://cloud.githubusercontent.com/assets/3647894/14701148/4ff5343e-07d6-11e6-8511-208119de2520.png)

**Comment by mreiferson** [comment]
That's intentional, it wasn't designed for RPC
