### ISSUE TITLE
nsqd: topic producer stats

### ISSUE THREAD

**Issue by blakesmith** [nsqio/nsq#754]
Hey everyone,

We run an nsq topology with dozens of nsqd processes, and roughly ~20 or so unique producers. Several of our topics have multiple producers (EG: producers that fetch data from a streaming API vs. our poll oriented producers that fetch from a REST API).

One common request from our teams is: "What are the producer hostnames for this topic?". This helps us in many scenarios: Tracking down bad producers, tracking down old producers, etc. I can point people at the nsqadmin and they can see all the nsqd processes that produce on that topic, but because we don't always run nsqd locally (sometimes we do depending on the producer), we don't always know where messages are coming from.

My proposal: I'd like to add hostname tracking on the nsqd at the topic level, similar to how it's done at the channel level. I'd like to add more detailed stats into the existing nsqd `/stats` call, and add a something like a `clients` array at the topic level like so:

```json
            {
                "backend_depth": 0,
                "clients": [
                    {
                        "name": "my-producer-host",
                        "count": 1234,
                    }
                ],
                "channels": [],
                "depth": 0,
                "e2e_processing_latency": {
                    "count": 0,
                    "percentiles": null
                },
                "message_count": 5542112,
                "paused": false,
                "topic_name": "test_topic"
            },
```

Because messages are produced at the topic level, this counter would be incremented every time a PUB message is sent, which would also cover the HTTP publisher case (since those connections are not necessarily persistent).

Thoughts? Feedback? This might be redundant to another feature, but I couldn't find one. I'd like to start working on a patch, but wanted to run this by everyone to get feedback on issues.

Thanks, still loving NSQ!

Blake

**Comment by ploxiln** [comment]
Why do you only sometimes run nsqd locally on all servers that run producers?

**Comment by blakesmith** [comment]
@ploxiln It's a tradeoff, depending on the topic and where it's produced from.

For example: Some of our front-end API servers produce messages, but we don't want to attach nsqd processes to these nodes because it would also require us to attach bigger disks for message buffering, especially since we don't want our HTTP API servers to fill lots of disks if a slow channel crops up. In other cases, for very critical producers, we choose to attach big disks in case of backup and accept that buffering might happen in the case of mis-behaving channels.

Does that make sense?

**Comment by ploxiln** [comment]
That does make sense, disk (or mem) queue management is a reasonable reason to run nsqd on a separate server.

**Comment by mreiferson** [comment]
@blakesmith I'm pretty sure all of the metrics you're interested in already exist at the topic level in `/stats`, combined with `nsqlookupd` data you have everything you need?

What version of `nsqadmin` are you running? We recently added some visual improvements to provide a more human-readable topic producer list.

**Comment by blakesmith** [comment]
Thanks @mreiferson, we're on 0.3.5 at the moment.

I already dug into the `nsqlookupd` data, and correct me if I'm wrong: But it looks like 'producer' at that level maps back to an actual `nsqd` processes, rather than a client that actually `PUB`d that data to the nsqd itself. Is this assumption incorrect?

**Comment by mreiferson** [comment]
Sorry, I misunderstood, we're using "producer" differently (your definition is probably correct, I'm just used to thinking that within the NSQ context a "producer" is the `nsqd` instance itself).

**Comment by blakesmith** [comment]
@mreiferson Yeah, naming things is hard. Any more thoughts or suggestions before I undertake the feature? Is there a better place where this would fit?

**Comment by blakesmith** [comment]
After spending some more time thinking about this feature and going through the code, there are definitely quite a number of tradeoffs and problems that must be considered:

1. **Adding hostnames at the `Topic` level**: Right now the `Topic` struct only tracks an aggregate `messageCount` variable for each `topic.PutMessage` call, which could perhaps be disaggregated to count messages per publisher by originating hostname. There are some considerations about memory footprint of this, given that the aggregated `uint64` per topic is very lightweight. In reality, I wouldn't be too concerned about big memory growth here, but wanted to raise it as a potential tradeoff. The other downside is that the `topic.PutMessage` call would have to become hostname aware. When `PUB` messages originate from a `client`, I would use the `client.Hostname` variable. When `PUB` calls originate from the http interface, I would use the `httpRequest.Host`. When calls originate from an unknown hostname, we could bucket these calls to an "unknown" hostname of some kind.
2. **Adding hostname stats at the `clientV2` level**: Putting these stats at the `clientV2` level will not cover the case where publishers are coming in through the http interface. We don't use the http interface at SproutSocial to publish (yet), but I'm still hesitant to add code here given that we wouldn't have visibility into http publishers.

When stats are queried, in order to support existing clients, we could still sum the `messageCount`s from each hostname, but also expose the additional hostname level tracking. I want to spend some more time fleshing this out once I get your feedback.

**Comment by mreiferson** [comment]
@blakesmith thanks for putting design time into this. I think we first need to figure out if this is something NSQ should be responsible for at all, before we go down the implementation path. It feels like it's something that could be handled outside of NSQ and might not be justified as part of core functionality.

Let's have that discussion and work through the pros and cons?

**Comment by blakesmith** [comment]
Thanks @mreiferson. The question I have is: If this code doesn't go into nsqd itself, where else does it fit? I've thought of two different models that all don't seem as elegant:

1. Track this data in the client itself. We're transitioning to our own NSQ client anyway that gives us better fleet level instrumentation and visibility, but we only really plan on exposing a JMX interface for our client - this leaves all sorts of other plumbing code (graphite, etc.) that other users would have to integrate to get value from. Plus, this will still only cover the case where we're using our java client, and not any of our python code.
2. Write a pcap / tcpdump like daemon that instruments this at the network interface level. Downsides of this is that it'd basically have to reimplement the nsq protocol just to sniff for data. Upside is it's completely out of the normal message flow for the production system, but there are other overhead tradeoffs like running another daemon process on every machine that also runs an nsqd.

Are there other options you can think of? I'm not a big fan of either one of them, but having this kind of producer visibility is going to be important for our teams.

**Comment by mreiferson** [comment]
I was simply thinking of your applications that publish being instrumented with statsd.

I am sympathetic to your point about it being outside of nsqadmin, but this proposal implies you're already running statsd and graphite.

My concern is what complexity (code, performance, coordination) it might add to the publishing code path.

**Comment by blakesmith** [comment]
@mreiferson Good points. I'm going to close this for now, and do some more thinking and have more discussions with our teams. We'll see if we can find another place to put this, and if I can come up with a simpler solution that makes sense for nsq itself, I'll open another issue.

Thanks for taking the time to think through this with me!
