### ISSUE TITLE
nsqd: can't recover after crash?

### ISSUE THREAD

**Issue by hicqu** [nsqio/nsq#755]
I test this case:
I start 1 nsqlookupd, 2 nsqd, and 1 nsqadmin. Then I publish message to both nsqd.
Then I type ctrl + C to stop one nsqd, and run it again.
But after that nsqd restart success, I can't see any message in nsqadmin web site.
So, nsqd can not recovery messages haven't be consumed by readers after restart?
Here is my nsqd startup command:
```
bin/nsqd -data-path $ddir \
	-broadcast-address 192.168.56.200 \
	-tcp-address $p1 \
	-http-address $p2 \
	-mem-queue-size 0 \
	-lookupd-tcp-address 192.168.56.200:4160 -verbose
```

**Comment by jehiah** [comment]
@hicqu can you share full logs from both nsqd's?

**Comment by jinhao** [comment]
@hicqu  i test it ok, you can see the meta file of your topic, nsqd will persist data to the disk if the message not consumed.

**Comment by ploxiln** [comment]
nsqd has a `--mem-queue-size` option which defaults to 10000 messages. If the memory queue depth exceeds this size, the overflow is saved to the disk-queue. Also, if nsqd is terminated gracefully, it saves all messages to the disk-queue. But if nsqd crashes, all messages in the memory queue are lost.

This is a trade-off for performance - avoiding the disk-queue enables better performance. You can set the `--mem-queue-size` much lower, even to 0 ... but I haven't tested that configuration and it may not work reasonably well. It is mentioned here: http://nsq.io/overview/design.html#bounded-memory-footprint

**Comment by hicqu** [comment]
I have done a new test with adding sequence number to all messages. And I found that the consumers recieved all messages correctly. Sorry for my mistake wasting your time. And thanks a lot for your helps.
But I realy hope that the nsqadmin web site could detect  this situation:
after I stop nsqd with ctrl + C, the count of all messages that have not been consumerd turn to 0 so I can't monitor the cluster status correctly using nsqadmin web site. 
English is not my mother tongue. So if I'm not clearly, @ me here please. Thanks!
