### ISSUE TITLE
nsqd: channel, RequeueMessage should check exitFlag before doRequeue

### ISSUE THREAD

**Issue by judwhite** [nsqio/nsq#760]
It looks like [this code](https://github.com/nsqio/nsq/blob/bf6cbc3c087e8ed3abd7d7e657da42508c77ad8a/nsqd/channel.go#L360-L362) should check `c.Exiting()`. This changed in https://github.com/nsqio/nsq/commit/de57a276b503550feab246dedd24e618bd79d49e in #701.

What do you think?

**Comment by jehiah** [comment]
@judwhite Yes, i believe you are correct. There still needs to be a check against `c.exitFlag` inside the lock, the lock is just a more narrow `exitMutex` instead of the broader channel lock.

**Comment by judwhite** [comment]
What do you think about giving the embedded `sync.RWMutex` a name now that there are multiple in `channel`?

**Comment by mreiferson** [comment]
Yep, it should, thanks for finding this @judwhite 

I _think_ this is fairly benign as the message would have been persisted to disk as part of `flush` (it must have been in flight if it's being requeued) and would result in a message ending up on the memory message channel (which was just flushed). However, if `--mem-queue-size` were set to zero, it would mean you'd end up writing an extra message to disk.

@judwhite Want to update?

**Comment by judwhite** [comment]
@mreiferson Yep will do. Stumbled on this while looking at 743.

**Comment by mreiferson** [comment]
see #843
