### ISSUE TITLE
Getting FIN failures

### ISSUE THREAD

**Issue by an0sv** [nsqio/nsq#762]
From time to time we see this in our NSQ log

[nsqd] 2016/05/13 07:28:33.935495 ERROR: [127.0.0.1:58597] - E_FIN_FAILED FIN 0632eb19de09b007 failed ID not in flight - ID not in flight

What could be the cause of this? I have double checked that we really are using a correct number. We are using RDY = 1 on our connections.

**Comment by ploxiln** [comment]
see #729 - it's probably timing out

Do you have evidence that the message that fails was processed fast enough?

**Comment by an0sv** [comment]
I will try to ensure that.
