### ISSUE TITLE
Cant set outputBufferSize

### ISSUE THREAD

**Issue by Yao-The-Beast** [nsqio/nsq#763]
Hi,

I have a problem in setting the OutputBufferSize correctly. In my consumer, I have the following code:
```
config := nsq.NewConfig()
config.MaxInFlight = 1000
config.OutputBufferSize = 2 * 1024
config.OutputBufferTimeout = 10
sub, _ := nsq.NewConsumer(topic, channel, config)
```
 Yet, the console output of the nsqd told me that the OutputBufferTimeout is 0 while the OutputBufferSize was set to 2048 correctly. I have no idea what can be wrong. Here is the console output:

[nsqd] 2016/05/17 13:06:48.350367 [10.0.0.26:51792] IDENTIFY: {ShortID:s1 LongID:s1.localdomain  ClientID:s1 Hostname:s1.localdomain HeartbeatInterval:30000 OutputBufferSize:2048 OutputBufferTimeout:0 FeatureNegotiation:true TLSv1:false Deflate:false DeflateLevel:6 Snappy:false SampleRate:0 UserAgent:go-nsq/1.0.5 MsgTimeout:0}

Thank you in advance!

**Comment by mreiferson** [comment]
`OutputBufferTimeout` should be specified in `time.Duration`, I think that might be the issue here.
