### ISSUE TITLE
Running nsq as non-root user in a container

### ISSUE THREAD

**Issue by jchauncey** [nsqio/nsq#767]
I keep getting the following error:

```
nsq@51f0acf12ebd:/$ nsqd
[nsqd] 2016/06/13 21:54:59.993288 nsqd v0.3.8 (built w/go1.6.2)
[nsqd] 2016/06/13 21:54:59.993390 ID: 196
[nsqd] 2016/06/13 21:54:59.993414 NSQ: persisting topic/channel metadata to nsqd.196.dat
2016/06/13 21:54:59 ERROR: failed to persist metadata - open nsqd.196.dat.4870068411280174143.tmp: permission denied
```

**Comment by jchauncey** [comment]
You need to set `WORKDIR` to get around this error

**Comment by Somesh** [comment]
May be try running the binary from its path.

`which nsqd` 
in my case it was located at `/usr/local/bin/nsqd`

and then 
`nsqd --lookupd-tcp-address=127.0.0.1:4160`

**Comment by judwhite** [comment]
@Somesh @jchauncey 

You can also use the `--data-path` arg of `nsqd`:

```
  -data-path string
        path to store disk-backed messages
```

**Comment by Cryptophobia** [comment]
I can confirm that setting the WORKDIR in the Dockerfile works:

We put nsq in `/opt` so the fix was:

```
WORKDIR /opt/nsq
```
