### ISSUE TITLE
nsqadmin: [question] reset statistic 

### ISSUE THREAD

**Issue by alileza** [nsqio/nsq#768]
Is there anyway we can reset statistics on NSQAdmin without affecting ongoing queue? My cases is, i expect requeued & timeout number on my spesific topic decreasing, so by reseting the statistic i can see how's fast the number grows. 

or is there any topic monitoring tools that can produce metrics per topic, i think it could be useful.

**Comment by ploxiln** [comment]
nsqd can send these statistics to statsd / graphite, and you can view/analyze them there, or even view the graphs of them back in nsqadmin:
![screen shot 2016-06-14 at 11 03 09](https://cloud.githubusercontent.com/assets/649835/16047850/b726ebde-321f-11e6-8ad5-a645afabf664.png)

**Comment by alileza** [comment]
nice, thanks. Since there's no statsd on my stack, is there any plan
integrating with prometheus?

**Comment by ploxiln** [comment]
#732

**Comment by ploxiln** [comment]
(also, nsqd currently works best with "statsdaemon", an alternative implementation of statsd written in go)
