### ISSUE TITLE
nsqadmin: configuration update API

### ISSUE THREAD

**Issue by kenjones-cisco** [nsqio/nsq#769]
Currently nsqd has an API for updating the configuration attribute `nsqlookupd_tcp_addresses`. The same feature is needed for nsqadmin.

Also each component nsqd, nsqadmin, and nsqlookupd all support a configuration file option `config`, add support for SIGHUP to trigger reloading the configuration file and continue processing with the updated configurations.

**Comment by mreiferson** [comment]
@kenjones-cisco our thinking was it's much safer to restart `nsqadmin` so using some wrapping service that `TERM`s the process on config changes would be reasonable.

What do you think?

**Comment by kenjones-cisco** [comment]
I'm currently using containerpilot (https://www.joyent.com/containerpilot) that handles registering each instance of nsqd, nsqlookupd, and nsqadmin into consul. For nsqd, when the registered service "nsqlookupd" changes the onChange event is triggered and and I use the API to update the configurations. That allows each nsqd to show up within each nsqlookupd.

For nsqadmin, I need a similar option that doesn't result is shutting down admin to restart it. So either an API like nsqd or the ability to send a signal to reload. Otherwise it would cause the entire container to shutdown and then that results in being dependent on the container scheduler to restart or recreate the container for nsqadmin.

Because of the investment in service discovery, being able to auto configure any component as instances go up and down within the environment.

I've used consul-template in other places where there are many configurations that will change, but for something like nsqadmin that seems overkill.

**Comment by mreiferson** [comment]
@kenjones-cisco thanks for the explanation.

> I've used consul-template in other places where there are many configurations that will change, but for something like nsqadmin that seems overkill.

I guess this feels like the perfect use case for `nsqadmin`, since it feels reasonably low risk to restart as a mechanism for receiving configuration updates.

In any event, I'm fine with adding a config API similar to `nsqd`. Are you interested in taking a pass at this?

**Comment by mreiferson** [comment]
see #773 / #775
