### ISSUE TITLE
Unable to get hostname open /proc/sys/kernel/hostname

### ISSUE THREAD

**Issue by renodesper** [nsqio/nsq#771]
Is it necessary to open _/proc/sys/kernel/hostname_ ? Because nsqlookupd sometimes return an error message indicating that it has open too many files. When this happen, nsqadmin also showing an alert and nsq stop functioning. 

This is the error message in nsqlookupd:
`ERROR: unable to get hostname open /proc/sys/kernel/hostname too many open files`

**Comment by ploxiln** [comment]
If you've hit the file descriptor limit for the nsqd process, you have bigger problems.

You asked in a closed issue how to list the open file descriptors of nsqd. That's OS dependent. It seems you're using linux, so something like this should work:

```
sudo ls -l /proc/$(pgrep nsqd)/fd
```

**Comment by ploxiln** [comment]
Just to be clear, `pgrep nsqd` should print out a list of PIDs of processes with the basename "nsqd". The above command assumes that there's only one.

You can see the file descriptor limit for the process with something like

```
cat /proc/$(pgrep nsqd)/limits
```

(look at the "Max open files" line)
