### ISSUE TITLE
nsq_to_file: could use some saner defaults

### ISSUE THREAD

**Issue by elubow** [nsqio/nsq#789]
Currently when `nsq_to_file` is run with no options, it automatically connects to every topic with a non-ephemeral channel and starts writing to disk. It would be more sane if the initialization was an ephemeral channel.  It would also be more sane if the default wasn't to connect to every topic and that was an option.  Was this a design decision made intentionally?

**Comment by mreiferson** [comment]
Hah, I can't even imagine what happened after you ran it @elubow 
🔥 👊 😵

**Comment by jehiah** [comment]
funny. not funny. consuming with a `nsq_to_file` channel made sense when topic was a required option (before nsq_to_file gained the ability to archive more than one at a time). I'd be ok if we just made that a required option again. Archiving with an ephemeral channel by default seems worse.

Thoughts?

**Comment by elubow** [comment]
@mreiferson I had to go through every single topic and delete the nsq_to_file channel. And on the topics that were supposed to be collecting data and waiting for a consumer, I had to reload all those topics again with the data from disk. Needless to say it took a while and caused some issues. 

@jehiah I think what would make sense is adding a '-all' option which would accomplish the same thing and not make it a default to connect to everything. And I agree that archiving with an ephemeral channel is a bad idea, but if the default is connect to everything, then ephemeral is a safer choice. If the default is single topic, then I agree that ephemeral makes little sense.

**Comment by ploxiln** [comment]
just chiming in from the peanut gallery ... I agree that some topic option should be required, and it's likely someone out there really wants the all-topics functionality, but I think they can get that with something like `--topic-pattern=".*"`

**Comment by mreiferson** [comment]
Agreed, default shouldn't connect to all.

@elubow care to write a little Go my friend?

**Comment by elubow** [comment]
I've been writing plenty of Go lately.  I'm not averse. I just didn't want to submit a PR that changes the default behavior of anything if there was a legitimate reason for having it behave the way it does in the first place.  I like @ploxiln idea of using `--topic-pattern` way better than mine of using `-all`.  I'd have to defer to one of the more seasoned folks to know if that's reasonably easy to code up.

As for the ephemeral piece, should that be an option (boolean similar to `--gzip`) that tags the channel name with `#ephemeral`? Or is it left as an exercise to the user to add the `#ephemeral` to the channel name.  I personally think it would be better as option that would append the `#ephemeral` since I don't believe it's common knowledge that just adding that to a channel name makes it so.

Thoughts?

**Comment by mreiferson** [comment]
> I've been writing plenty of Go lately. I'm not averse. I just didn't want to submit a PR that changes the default behavior of anything if there was a legitimate reason for having it behave the way it does in the first place. I like @ploxiln idea of using --topic-pattern way better than mine of using -all. I'd have to defer to one of the more seasoned folks to know if that's reasonably easy to code up.

Shouldn't be too bad?

> As for the ephemeral piece, should that be an option (boolean similar to --gzip) that tags the channel name with #ephemeral? Or is it left as an exercise to the user to add the #ephemeral to the channel name. I personally think it would be better as option that would append the #ephemeral since I don't believe it's common knowledge that just adding that to a channel name makes it so.

I'm 👎  on this — given that we're addressing this unexpected default behavior I don't think it's necessary to create _another_ flag to append `#ephemeral`, just override `--channel`.

**Comment by elubow** [comment]
As an aside, I'm concerned that channel name doesn't work properly in `nsq_to_file`. This most recent few times I've run it, the channel name consistently ends up `nsq_to_file` regardless of what I input as a channel name.  I'm planning on investigating that when I get a chance to dive in to changing the default behavior here as well.

**Comment by judwhite** [comment]
@elubow If you're archiving a topic you _probably_ don't want to drop messages, or at least you don't want that to be the default behavior. `#ephemeral` channels do this when `mem-queue-size` is exceeded instead of buffering to disk.

I'm up for making this change.

**Comment by judwhite** [comment]
> As an aside, I'm concerned that channel name doesn't work properly in nsq_to_file. This most recent few times I've run it, the channel name consistently ends up nsq_to_file regardless of what I input as a channel name.

@elubow I tested this scenario and wasn't able to reproduce. Looking at the code it seems unlikely unless you typo'd `--channel`. While testing I also messed up the args and wished it complained.

**Comment by mreiferson** [comment]
see #794
