### ISSUE TITLE
nsqd: pass TLS CN= to auth API

### ISSUE THREAD

**Issue by devicenull** [nsqio/nsq#793]
We already have a TLS CA and cert architecture set up, and would like to reuse that with nsq.  This setup was all built out for Puppet, which uses the Subject of the cert to determine which machine is which.  I'd like to see nsq pass the 'Subject CN' to the auth api, so we can determine what permissions a connection should have based on it's cert.

Combined with -tls-client-auth-policy require-verify, this would give us strong authentication without needing to maintain a separate list of shared secrets.

**Comment by mreiferson** [comment]
this is a cool idea, I think I'm 👍

**Comment by mreiferson** [comment]
see #1119
