### ISSUE TITLE
docs: DPUB

### ISSUE THREAD

**Issue by deoxen0n2** [nsqio/nsq#795]
Hi, I checked the docs and couldn't see information about Deferred PUB introduced by this PR #293 . Should it be on this http://nsq.io/components/nsqd.html and http://nsq.io/clients/tcp_protocol_spec.html pages?

Best regards.

**Comment by mreiferson** [comment]
@deoxen0n2 yes! would you like to submit a PR?

**Comment by deoxen0n2** [comment]
@mreiferson I can do PR, but I will get to know more of it first. Thanks you for fast reply.

**Comment by mreiferson** [comment]
addressed in nsqio/nsqio.github.io#21
