### ISSUE TITLE
why authd desgined for one client connection not for all nsqd?

### ISSUE THREAD

**Issue by denofiend** [nsqio/nsq#800]
why authd desgined for one client connection not for all nsqd?

if client connection close after pub message, every pub query pass nsqd, authd once

**Comment by mreiferson** [comment]
I'm not quite sure what you're asking here, can you try to elaborate or rephrase? Also, this is a better question for the [mailing list](https://groups.google.com/forum/#!forum/nsq-users).

**Comment by denofiend** [comment]
I can try
