### ISSUE TITLE
nsq_to_file: updates

### ISSUE THREAD

**Issue by judwhite** [nsqio/nsq#802]
See PR #794 for discussion.
- [x] `--topic` and `--topic-pattern` should be mutually exclusive options
- [x] ~~`--topic` and `--topic-pattern` should work for both `nsqd` and `nsqlookupd`~~
- [x] Report unrecognized arguments, don't silently ignore them; see [`flag.Args`](https://golang.org/pkg/flag/#Args)

**Comment by mreiferson** [comment]
The second item on this was completed by the fact that we fatally exit if `nsq_to_file` is provided no `--topic` or `--lookupd-http-address` arguments.

The last item is being addressed in #1117.

Closing!
