### ISSUE TITLE
nsqadmin: timeout settings

### ISSUE THREAD

**Issue by mschneider82** [nsqio/nsq#803]
Hi, 

I justed upgraded my infrastructure (~120 nsqd's, ~20 topics, serval channels) from 0.2.9 to 0.3.8 and now the nsqadmin is always failing because of timeout settings:

## Example1:

clicking on a topic: `http://nsqadmin.local/topics/exampletopic`

`ERROR: failed to decode JSON - Unexpected token in JSON at position 132`

### Browser inspect:

Headers:
```
Request URL:http://nsqadmin.local/api/topics/exampletopic
Request Method:GET
Status Code:502 Bad Gateway
```

Response:
```
{"message":"UPSTREAM_ERROR: Failed to query any nsqlookupd: Get http://nsqlookupd02.local:4161/lookup?topic=exampletopic: dial tcp: i/o timeout
Get http://nsqlookupd01.local:4161/lookup?topic=exampletopic: dial tcp: i/o timeout"}
```

this also happens when i browse to `/nodes`,  I have about ~120 nsqd listed some may be on high load servers.

## Example2:

sometimes when i click on a topic it works but not all nsqd's are listed, a WARNING is displayed at the top that some of the servers cannot be reached:

```
WARNING: Get http://server1.local:4151/stats?format=json: dial tcp: i/o timeout Get http://server2.local:4151/stats?format=json: dial tcp: i/o timeout Get 
...20 more servers...
```

i manuelly checked all of them all nsqd's are working fine, also the json response is OK
This issue also happens in v0.3.7

**Comment by mschneider82** [comment]
i just saw https://github.com/nsqio/nsq/commit/454cf2f56a35bbd5c9179d2921ee204d822b9f20

is `http-client-connect-timeout` also a commandline parameter? I cant find it with `--help`

**Comment by jehiah** [comment]
FWIW display of errors in the nsqadmin UI when it fails to connect to nsqlookupd or nsqd is new as of #657 (0.3.6) so versions before that may have allowed errors to passed undetected.

As of #776 nsqadmin does have `-http-client-connect-timeout duration` and `-http-client-request-timeout duration`. You'll need to build a copy of nsqadmin from master to get that.

**Comment by mreiferson** [comment]
Yea, probably time for a release?

**Comment by mschneider82** [comment]
i compiled it and its working with a 20s timeout setting :+1: 
a new stable release would be great. maybe enlarge the default parameters?
