### ISSUE TITLE
confusion about the statistics

### ISSUE THREAD

**Issue by sdbaiguanghe** [nsqio/nsq#806]
I used **DPUB** cmd to publish a few defered message. I get the statistics through nsqadmin and if found the **Channel. Requeued** increased but **Channel. Messages** didn’t increase.
And when a message time out the **Channel.Requeued** and **Channel.TimedOut** both increase.
I do not think it's logical. So i [pulled a request](https://github.com/nsqio/nsq/pull/805
) to 
slove it.

**Comment by mreiferson** [comment]
@sdbaiguanghe thanks, let's continue the conversation on #805
