### ISSUE TITLE
UPSTREAM_ERROR: Failed to query any nsqd: Get http://MyServer:4151/stats?format=json: dial tcp: lookup MyServer on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by cmlanche** [nsqio/nsq#810]
what is problem, help!

**Comment by jehiah** [comment]
nsq expects hosts to have resolvable hostnames. If you do not have a routable hostname (i.e. it's not in DNS or `/etc/hosts` on every machine) then you can set `-broadcast-address` to the IP address you use to connect to nsqd.

**Comment by ettalhi** [comment]
**I am getting the same error message from my virtual machine :**

`root@debian:~/.kube/certs# kubectl version
go package net: built with netgo build tag; using Go's DNS resolver
go package net: hostLookupOrder(devkb.ile.montreal.qc.ca) = files,dns
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp: lookup devkb.ile.montreal.qc.ca on 8.8.8.8:53: no such host
root@debian:~/.kube/certs#
`


**However, the same command works fine from PowerShell on the same computer where VM is installed :**
`PS C:\Users\noureddine.ettalhi> kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b8
8c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/a
md64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcce
b0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd6
4"}
PS C:\Users\noureddine.ettalhi>`

**can you please tell the steps I should follows to get kubectl  work from my VM.**

**Comment by Chira-G** [comment]
Seems like the domain name which you are using for your private repo is expired, that is why it is not resolving through global DNS 8.8.8.8 . Check with your Domain name provider.
