### ISSUE TITLE
bad protocol magic 'GET '

### ISSUE THREAD

**Issue by TUTUBIG** [nsqio/nsq#811]
hi guys! i visit the nsqadmin via the browser and i get
 `ERROR: failed to decode JSON - Unexpected token \ in JSON at position 124`  
 and i find it comes from the nsqlookupd which give the error message 
` bad protocol magic 'GET '` 
what's wrong ?

**Comment by jehiah** [comment]
@TUTUBIG This is likely a configuration issue with missing TCP and HTTP protocol ports in your configuration.

This type of question is more appropriate for the mailing list http://nsq.io/community.html

**Comment by TUTUBIG** [comment]
@jehiah ok  i will read this document again ,thank you
