### ISSUE TITLE
Can i use NSQD as a push service?

### ISSUE THREAD

**Issue by wangxingge** [nsqio/nsq#812]
for example, there are more than 100000 clients connect to the nsqd.
and i want use nsqd push message to each client, can i do that?

I've use nsq for one year, not very young user  :), and i need a push service now, i've test thrift and grpc, they are works and very nice. but i need to change my current design. So i want to use nsq as my push service. 

Do you have any suggestion on that? Or NSQ just a message queue, don't use it like a push service.

**Comment by zieckey** [comment]
If you need to push a message to only several clients, I think that's OK. But if you push a message, and want all the clients (more than 100000) received this message, I thinks that's impossible.
Your clients are the comsumer of NSQD, one message is pushed to all the clients, it needs all the clients registered in deferent NSQD's channels, and NSQD will clone the message more 100000 times for every client (one client for one message), that will cause huge server CPU load and potential IO load. That's the problem it is.
If you really want to do this, please modify the codes of NSQD where it dispatch messages to comsumers.

**Comment by mreiferson** [comment]
@wangxingge a typical architecture for this with NSQ would be to build an application that consumes from a channel and maintains long lived connections with clients for delivery.

**Comment by wangxingge** [comment]
Thanks for mrerferson and zieckey response.
I'll check it.
