### ISSUE TITLE
nsqd: deferred message lost

### ISSUE THREAD

**Issue by gewentao** [nsqio/nsq#813]
I published 3 deferred messages (one hour duration) and then stopped the docker container of nsqd.

channel stats before stopping docker container:
![](http://ww4.sinaimg.cn/large/61400a92jw1f9sttsevm2j21kw0a5taf.jpg)

then I restarted the container:
![](http://ww2.sinaimg.cn/large/61400a92jw1f9stw8yhigj21kw09dgnc.jpg)

It seems the number of messages in disk queue (e.g. 2) is always one less than the number of published messages (e.g. 3).

After restarting nsqd, the message handler function should have been called for three times as expected (actually two).

**Comment by judwhite** [comment]
@gewentao which version of nsqd are you running?

**Comment by gewentao** [comment]
@judwhite Thanks for your reply. I'm using the nsqio/nsq docker image.

**Comment by gewentao** [comment]
Just FYI: I built the source code and ran an instance of nsqd in localhost rather than a docker container, it works good. All the deferred messages were flushed to disk. Maybe stopping a docker container of nsqd directly is not graceful that causes the message lost issue?

**Comment by mreiferson** [comment]
That would either implicate the version of `nsqd` running in the container or the fact that it's running in a container to begin with. Can you provide the exact command(s) you're using and which version of the image?

**Comment by gewentao** [comment]
`  nsq:`
`    image: nsqio/nsq`
`    command: /nsqd`
`    container_name: nsq_server`
`    ports:`
`      - "4150:4150"`

This is the configuration in my docker compose file.

**Comment by mreiferson** [comment]
@gewentao what version of the container?

**Comment by gewentao** [comment]
vagrant@vagrant-ubuntu-trusty-64:~$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

**Comment by mreiferson** [comment]
@gewentao I meant the NSQ docker container's version...

**Comment by gewentao** [comment]
@mreiferson I'm using the image named 'nsqio/nsq', so I think it's the latest version of nsq socker image...

**Comment by ploxiln** [comment]
```
~$ sudo docker images | grep nsq
nsqio/nsq                                                                   latest              2a82c70fe5e3        5 months ago        70.68 MB
~$ sudo docker run --rm nsqio/nsq nsqd --version
nsqd v0.3.8 (built w/go1.6.2)
```

The "version" of the docker image is the "hash" `2a82c70fe5e3`, and you can ask nsqd inside what version it is.

**Comment by gewentao** [comment]
@ploxiln thanks, the version is:  nsqd v0.3.8 (built w/go1.6.2)

**Comment by mreiferson** [comment]
I haven't been able to validate this inside or outside a docker environment, closing.

If you can provide a reproducible test, please re-open.

Thanks!
