### ISSUE TITLE
nsqadmin improve: HomePage add messages and depth count

### ISSUE THREAD

**Issue by pedia** [nsqio/nsq#814]
First login into nsqadmin, we got all topics. Can we add topic's message, depth count, client count?
like:
topics:
|A | client count | depth count | fly count | message count|

**Comment by jehiah** [comment]
I think i understand the desire, but in the past when we have dug into possible implementations we come up short.

While technically messages can queue at the topic level under situations of resource starvation (or if no channels exist yet) in practice the depth you want is from channels. There are many channels per topic so there is no reasonable way to compress that information to a usable format on the topics page.

The same is true for client count. Client counts only apply to channels, and there are many possible per topic.

There is also an added complication in how it scales if you have to fetch all topic and all channel information for everywhere to render the index page. If you run larger deployments this becomes a bottleneck.

based on all that, I'm unfortunately going to close this request =( but i really appreciate you writing it @pedia
