### ISSUE TITLE
Nsqadmin fails to load node data with IPv6 broadcast addresses

### ISSUE THREAD

**Issue by magnetised** [nsqio/nsq#815]
When nsqd instances are configured with IPv6 addresses e.g. `broadcast-address=fdeb:5ba3:18b3::1` then when nsqadmin attempts to load the node stats it does a naive mapping of the broadcast address to an HTTP/TCP address which gives invalid results.  In the above case it would attempt to fetch from `http://fdeb:5ba3:18b3::1:4151/stats` which fails at the URI parsing stage.

Note that if you set the broadcast address to `[fdeb:5ba3:18b3::1]` this fixes nsqadmin behaviour but breaks nsq behaviour on the node as the address gets double-bracketed at some point and ends up trying to connect to `[[fdeb:5ba3:18b3::1]]:4150`.

**Comment by mreiferson** [comment]
> Note that if you set the broadcast address to [fdeb:5ba3:18b3::1] this fixes nsqadmin behaviour but breaks nsq behaviour on the node as the address gets double-bracketed at some point and ends up trying to connect to [[fdeb:5ba3:18b3::1]]:4150.

@magnetised does #816 address this or should we keep this issue open to track the above? Can you elaborate on this, too?

**Comment by magnetised** [comment]
@mreiferson I don't actually think that there is a bug around the handling of the broadcast address. Wrapping broadcast addresses in `[..]` was a hack I tried and it didn't work, but I think it's right that it didn't work. Nsq's behaviour is correct IMHO.

**Comment by mreiferson** [comment]
@magnetised so then we can close this?
