### ISSUE TITLE
nsqd: stopping without any error in logs

### ISSUE THREAD

**Issue by gthmac** [nsqio/nsq#818]
We have been running nsqv0.3.8 for a while now and it works very well. We are only facing one issue with it, which is that the nsqd daemon ceases to run, i. e. stops without any indication why so. 

Our setup is: 
2 nodes, each of which runs 1 nsqlookupd and 1 nsqd
1 of them also runs nsqadmin

On node1, nsqd is started as such:
```
nsqd --lookupd-tcp-address=127.0.0.1:4160 --lookupd-tcp-address=iospush2.watercoins.io:4160 &>/tmp/nsqd.log &
```
One node2, vice versa:
```
nsqd --lookupd-tcp-address=127.0.0.1:4160 --lookupd-tcp-address=iospush1.watercoins.io:4160 >& /tmp/nsqd.log &
```

The log-files after both nsqd stopped, looked as such:

```
node1: tail /tmp/nsqd.log 
[nsqd] 2016/12/01 11:15:17.449486 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:17.449682 LOOKUPD(iospush2.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:32.449468 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:32.449694 LOOKUPD(iospush2.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:47.449480 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:47.449692 LOOKUPD(iospush2.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:02.449488 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:02.449682 LOOKUPD(iospush2.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:17.449500 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:17.449706 LOOKUPD(iospush2.watercoins.io:4160): sending heartbeat
```

node2: tail /tmp/nsqd.log 

```
[nsqd] 2016/12/01 11:15:11.432427 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:11.436098 LOOKUPD(iospush1.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:26.432568 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:26.432933 LOOKUPD(iospush1.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:41.432497 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:41.432665 LOOKUPD(iospush1.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:56.432502 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:15:56.432693 LOOKUPD(iospush1.watercoins.io:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:11.432538 LOOKUPD(127.0.0.1:4160): sending heartbeat
[nsqd] 2016/12/01 11:16:11.432730 LOOKUPD(iospush1.watercoins.io:4160): sending heartbeat
```

ps shows on both machines that nsqlookupd is still running, but both nsqd's are gone:

```
node1:
ps aux | grep nsq
centos    1023  0.1  0.2  23248  9176 ?        Sl   Nov30   2:42 nsqlookupd
centos    1047  0.0  0.1  20928  4920 ?        Sl   Nov30   0:01 nsqadmin --lookupd-http-address=127.0.0.1:4161 --lookupd-http-address=iospush2.watercoins.io:4161
```

```
node2:
ps aux | grep nsq
centos     996  0.1  0.2  23248  9444 ?        Sl   Nov30   2:35 nsqlookupd
```

Syslog does not show any strange condition on the machine, disks are fine etc.
Any idea of what might be causing this?

Thanks much in advance,
Gunther

**Comment by jehiah** [comment]
Can you add some information about how are you running nsqadmin and nsqlookupd? Are you just running from a bash shell? If so you will need to use something like `nohup nsqd ... &` so it continues running after you close your terminal session.

**Comment by gthmac** [comment]
Thanks for the immediate reply. Am running it as a centos service, not from a terminal.
Is there any conditions when nsqd stops servicing? E. g. too many channels etc?

I am asking this as I had to increase the max_open_files already, but when it stopped servicing for that specific reason then nsqd gave an appropriate error message.

**Comment by mreiferson** [comment]
@gthmac one plausible explanation is that the process is being killed (`-9`) which wouldn't show up in the `nsqd` logs. Possible explanations for this might be the OS killing it due to OOM (out of memory).

Can you look at your `syslog` to see if there's any indication of that?

**Comment by mreiferson** [comment]
@gthmac gonna close this as it seems unlikely for this to be a bug in `nsqd`. If you have any more information that indicates otherwise please re-open.
