### ISSUE TITLE
Batching efficiency

### ISSUE THREAD

**Issue by iameugenejo** [nsqio/nsq#819]
I developed a service using nsq, 

and what it does is, each service clients accumulate messages, process them then store the result.

It is always efficient if a client can batch as many messages as possible within a limit.

For batching efficiency, I do not want the messages to be spread out across the multiple clients, rather I want the messages to fill up a client at time.

Is there a way of achieving this with current version of nsq?

If not, may I ask for the feature request?

**Comment by jehiah** [comment]
This is a a good question for the mailing list http://nsq.io/community.html

In general NSQ allows the client to control how many messages you get from NSQ at a time with max-in-flight. It's then up to the client when it chooses to complete the messages.

The built in utility `nsq_to_file` for example uses this strategy to write messages to disk immediately but only send the FIN back to nsqd when the file has been successfully sync'd to disk.

**Comment by iameugenejo** [comment]
I think you didn't understand what I want. I have multiple clients, and I don't want them to be queued for taking messages. I don't want the messages to be distributed fairly. Anyway I'll move the question to mailing list.

**Comment by iameugenejo** [comment]
And this was more of a feature request than a question. So I don't know if mailing list is a good fit. I'll just try to implement this in the service.

**Comment by jehiah** [comment]
nsq doesn't dictate how a client does or doesn't batch operations, so I think the mailing list is the right spot for discussing strategies around that. There may well be possible features to add related to this, but it's unclear from your issue here exactly what that is.
