### ISSUE TITLE
nsq.io is serving wrong certificate

### ISSUE THREAD

**Issue by szank** [nsqio/nsq#820]
When I tried to open `nsq.io` website, I got HTTP error from Chrome. The server have presented cert for `*.github.com`.

**Comment by ploxiln** [comment]
nsq.io is hosted by github. You can't use https://nsq.io/, you need to use http://nsq.io/.

Note that https://nsqio.github.com/ works and redirects to http://nsq.io/, and that various links in the github README and elsewhere use http:// for nsq.io.

**Comment by szank** [comment]
Hi, 
I have no idea how did I end up with https://nsq.io. Maybe google, maybe just editing the address bar. 

Either way, telling people that they can't use https if the website is available via https is silly. I am well aware that nsq.io is hosted on github.  Also, I am well aware of the redirection. 

If grabbing a cert from letsencrypt is too much work, than fine, you can close this bug. Still serving a https site with invalid certs rubs me the wrong way.

**Comment by ploxiln** [comment]
I agree, https for nsq.io would be better, I was just trying to be overly clear. But I failed to mention that it's not possible to just set up working https for github-hosted sites using custom domains. The website would need to be hosted elsewhere. (Or Cloudflare, a company/service separate from github, would need to be set up as a reverse proxy for the website.)

**Comment by szank** [comment]
Fair enough, 
I would have expected that github servers did support SNI. 
I am closing this bug, as there is no easy fix for the current situation.

**Comment by strugee** [comment]
@szank they support (require?) SNI, IIRC. That doesn't mean that they actually _use_ SNI to support custom domains.
