### ISSUE TITLE
How to install nsq offline

### ISSUE THREAD

**Issue by dengjunwen** [nsqio/nsq#824]

**Comment by jehiah** [comment]
@dengjunwen this sounds like a question for the mailing list. It's also unclear what issues you ran into when trying to install nsq, so any more context you can provide will help.

http://nsq.io/community.html

**Comment by dengjunwen** [comment]
Thanks!  I want to install nsq to a vps。 But the vps can not connect to internet, it is connected in Local Area Network。    Now I find the way to install nsq。   Thank you！
