### ISSUE TITLE
nsqlookupd is missing a bunch of http api documentation

### ISSUE THREAD

**Issue by stephensearles** [nsqio/nsq#827]
Unless I'm missing something, I think there's a bunch of extremely handy functionality that's not called out on the website. Specifically, nsqlookupd seems to support a handful of the same HTTP API that nsqd does, though with a couple minor differences. (e.g. /channel/create on nsqlookupd will implicitly create a nonexistent topic, but nsqd will not)

**Comment by jehiah** [comment]
Can you re-open this issue the docs repo https://github.com/nsqio/nsqio.github.io ?
