### ISSUE TITLE
nsqd: gc stop the world 5-8 seconds

### ISSUE THREAD

**Issue by denofiend** [nsqio/nsq#842]
Hi,
   My nsqd gc is issues, stop the world 5-8 seconds:

```
gc 26161 @102840.374s 0%: 0.010+5655+0.48 ms clock, 0.25+1.9/6.3/11+11 ms cpu, 15->15->11 MB, 16 MB goal, 24 P
gc 24934 @100740.501s 0%: 0.14+4183+0.35 ms clock, 3.4+3.5/9.1/1.9+8.6 ms cpu, 13->14->9 MB, 14 MB goal, 24 P
```

How to solve?

**Comment by jehiah** [comment]
@denofiend I have a few follow up questions for you so we can help

- What nsqd version are you using (`nsqd -version`) 
- Can you share a little about your configuration? Particularly what sorts of message throughput and message size is your workload.
- What is resource availability on the host (is it CPU starved)
- How are you measuring these GC metrics (Are you using the built in statsd metrics, or ...)

**Comment by mreiferson** [comment]
I don't see the STW in that output?

According to the `GCTRACE` docs, it looks like that time is spent in the (concurrent) mark-and-sweep phase:

```
gctrace: setting gctrace=1 causes the garbage collector to emit a single line to standard
error at each collection, summarizing the amount of memory collected and the
length of the pause. Setting gctrace=2 emits the same summary but also
repeats each collection. The format of this line is subject to change.
Currently, it is:
	gc # @#s #%: #+#+# ms clock, #+#/#/#+# ms cpu, #->#-># MB, # MB goal, # P
where the fields are as follows:
	gc #        the GC number, incremented at each GC
	@#s         time in seconds since program start
	#%          percentage of time spent in GC since program start
	#+...+#     wall-clock/CPU times for the phases of the GC
	#->#-># MB  heap size at GC start, at GC end, and live heap
	# MB goal   goal heap size
	# P         number of processors used
The phases are stop-the-world (STW) sweep termination, concurrent
mark and scan, and STW mark termination. The CPU times
for mark/scan are broken down in to assist time (GC performed in
line with allocation), background GC time, and idle GC time.
If the line ends with "(forced)", this GC was forced by a
runtime.GC() call and all phases are STW.
```

**Comment by denofiend** [comment]
1. version nsqd v0.3.8
2.  conf
verbose = true
mem_queue_size = 0

here is config file:
[nsqd.txt](https://github.com/nsqio/nsq/files/681593/nsqd.txt)

3.  when gc pause, there is no log for 5 - 8 seconds, and produce client timeout for read message from nsq. the admin gc stats:
![gc](https://cloud.githubusercontent.com/assets/1941075/21598624/b000dcf0-d19a-11e6-9d20-0e5912a98068.png)


I use gctrace to get every gc result.

**Comment by denofiend** [comment]
I found the source code from go, the second time is tMarkTerm.
```

	// Print gctrace before dropping worldsema. As soon as we drop
	// worldsema another cycle could start and smash the stats
	// we're trying to print.
	if debug.gctrace > 0 {
		util := int(memstats.gc_cpu_fraction * 100)

		var sbuf [24]byte
		printlock()
		print("gc ", memstats.numgc,
			" @", string(itoaDiv(sbuf[:], uint64(work.tSweepTerm-runtimeInitTime)/1e6, 3)), "s ",
			util, "%: ")
		prev := work.tSweepTerm
		for i, ns := range []int64{work.tMark, work.tMarkTerm, work.tEnd} {
			if i != 0 {
				print("+")
			}
			print(string(fmtNSAsMS(sbuf[:], uint64(ns-prev))))
			prev = ns
		}
		print(" ms clock, ")
		for i, ns := range []int64{sweepTermCpu, gcController.assistTime, gcController.dedicatedMarkTime + gcController.fractionalMarkTime, gcController.idleMarkTime, markTermCpu} {
			if i == 2 || i == 3 {
				// Separate mark time components with /.
				print("/")
			} else if i != 0 {
				print("+")
			}
			print(string(fmtNSAsMS(sbuf[:], uint64(ns))))
		}
		print(" ms cpu, ",
			work.heap0>>20, "->", work.heap1>>20, "->", work.heap2>>20, " MB, ",
			work.heapGoal>>20, " MB goal, ",
			work.maxprocs, " P")
		if work.mode != gcBackgroundMode {
			print(" (forced)")
		}
		print("\n")
		printunlock()
	}
```

**Comment by mreiferson** [comment]
Given that you're setting `mem-queue-size` to `0`, is there a corresponding burst in disk IO around that time?

Can you try different values for that setting and see if the problem persists?

**Comment by denofiend** [comment]
I try set mem-queue-size = 100,  but the problem persists.

**Comment by mreiferson** [comment]
@denofiend OK, do you have a reproducible script? Is there anything else notable about your runtime environment (e.g. OS)?

**Comment by JensRantil** [comment]
Golang 1.7 and 1.8 both have come with quite a lot of GC improvements. Might be worth trying a newer version of compiler if you are using 0.3.8 release built using Go 1.6. Feel free to track releases with more modern compiler in #857.

**Comment by denofiend** [comment]
I use http tcp sdk to communication with nsqd. it is short tcp connection, after pub message success, close tcp connection.

**Comment by denofiend** [comment]
here is inused heap svg pic: 
![stop-world](https://cloud.githubusercontent.com/assets/1941075/24826368/398bb726-1c67-11e7-9e58-b334b42eecd4.png)

**Comment by denofiend** [comment]
Use  environment additions config：GODEBUG="gctrace=1,gcshrinkstackoff=1",GOGC=1000       ; process environment additions.

Relieve the gc stress, I get gc log:

gc 90 @9430.556s 0%: 0.028+2.1+0.48 ms clock, 0.67+0.14/9.3/17+11 ms cpu, 203->203->19 MB, 213 MB goal, 24 P
gc 91 @9516.017s 0%: 0.021+2.1+0.46 ms clock, 0.51+0.17/8.4/20+11 ms cpu, 203->204->19 MB, 213 MB goal, 24 P
gc 92 @9597.958s 0%: 0.017+1.9+0.43 ms clock, 0.43+0.17/8.0/21+10 ms cpu, 203->204->19 MB, 213 MB goal, 24 P
gc 93 @9684.967s 0%: 0.024+2.3+0.44 ms clock, 0.59+0.55/8.8/19+10 ms cpu, 205->205->19 MB, 214 MB goal, 24 P
gc 94 @9759.614s 0%: 0.018+2.1+0.44 ms clock, 0.43+0.14/9.2/16+10 ms cpu, 205->205->19 MB, 215 MB goal, 24 P

**Comment by mreiferson** [comment]
@denofiend can you try your original test on the [latest release of NSQ (`v1.0.0-compat`)](https://github.com/nsqio/nsq/releases/tag/v1.0.0-compat), which has been compiled with go1.8, and see if it's reproducible?

**Comment by ploxiln** [comment]
I strongly suspect that golang versions after 1.6 have "fixed" this by drastically improving worst-case GC latency - will close soon if no update.
