### ISSUE TITLE
docs: /put should now /pub in quick start

### ISSUE THREAD

**Issue by gr4finger** [nsqio/nsq#845]
Just wanted to inform you about an error in NSQ QUICK START guide
The example for publishing a message using curl says:
$ curl -d 'hello world 1' 'http://127.0.0.1:4151/put?topic=test'.

This results into an error. The right URL should be "pub" (not "put")
$ curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'.

Same error (copy&paste) also in "hello world 2" and "hello world 3".
cheers,
Andreas

**Comment by mreiferson** [comment]
@gr4finger would you mind opening a PR to fix on https://github.com/nsqio/nsqio.github.io?

**Comment by mreiferson** [comment]
cc @jehiah 

We actually need to remove a whole lot of deprecated references in the docs for `1.0`.

**Comment by mreiferson** [comment]
see https://github.com/nsqio/nsqio.github.io/issues/14
