### ISSUE TITLE
nsqd: expose memory stats under /stats

### ISSUE THREAD

**Issue by ruimarinho** [nsqio/nsq#846]
Currently the `/stats` endpoint exposes most stats that the `statsd` integration provides. However, it looks like memory stats are not exposed.

Enabling `--statsd-mem-stats` has no effect on the number of stats exposed.

Would you be open to expose these?

**Comment by mreiferson** [comment]
Sure, that seems fine to me.

**Comment by mreiferson** [comment]
done in #874
