### ISSUE TITLE
nsqd: Failed to publish an initial message

### ISSUE THREAD

**Issue by justintan** [nsqio/nsq#849]
Get and build nsq with src
**go get -u -v github.com/nsqio/nsq/...**

Start nsq following the document http://nsq.io/overview/quick_start.html

In the 5th step
curl -d 'hello world 1' 'http://127.0.0.1:4151/put?topic=test'

Get result:
{"message":"NOT_FOUND"}

nsqlookupd, nsqd and nsqadmin are running and seems no fault

**Comment by justintan** [comment]
I read the source code. 
It should be curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'
Official document needs update

**Comment by mreiferson** [comment]
see https://github.com/nsqio/nsqio.github.io/pull/15

**Comment by tasaddaq-rana** [comment]
Hi,

I also tried curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'
but same error
message not found, can anyone please help me?
