### ISSUE TITLE
how to build NSQ from source code?

### ISSUE THREAD

**Issue by loadasp** [nsqio/nsq#861]
When i tried to build NSQ from source code,like: nsqlookupd in app folder.
The following error occurred:
D:\GoWorkSpace\src\github.com\bitly\nsq\apps\nsqlookupd>go build
nsqlookupd.go:14:2: use of internal package not allowed

How to solve this?My Go version is 1.8

**Comment by ploxiln** [comment]
What's your `GOPATH` environment variable set to? Is it "D:\GoWorkSpace"? If it's not set, as of 1.8 it defaults to `%USERPROFILE%/go` on windows.

What exact version of the source are you trying to build?

Did you install/update all the dependencies using "gpm"?

see also http://nsq.io/deployment/installing.html#building-from-source

**Comment by loadasp** [comment]
Yes,the  GOPATH  environment variable is  "D:\GoWorkSpace".
My package management tool is godep。I'm using Windows8.1 and I can't find the windows version for gpm。Is this the problem?
I executed below command in cmd:
go get github.com/kr/godep          (done)
go get github.com/bmizerany/assert               (done)
godep get github.com/bitly/nsq/...       (this command failed with many "use of internal package not allowed" errors).
Then i tried to execute "go build" command in apps/nsqlookupd folder,the error just is same as above.
I also tried to get the v0.38 source code from git and execute “go build” directly,and there is no luck.

**Comment by ploxiln** [comment]
try making a brand new go path and just "go get", something similar to:

```
mkdir gopath2
export GOPATH="D:\gopath2"
go get github.com/nsqio/nsq/apps/nsqlookupd
dir "gopath2\bin"
```

(but translated from bourne shell to windows cmd of course)

**Comment by loadasp** [comment]
Thanks!That's very helpful.
I'm not really sure what happened.
I followed your advice, executed "go get github.com/nsqio/nsq/apps/nsqlookupd" ,then i can excute go build or other command in apps folder directly.
