### ISSUE TITLE
NSQ panic'd (ephemeral issue)

### ISSUE THREAD

**Issue by tejasmanohar** [nsqio/nsq#862]
NSQ crashed with this trace. It was fine after the docker image restarted. Unfortunately, I didn't get to capture the full trace :\

Anyhow, I thought it may be helpful anyways...

```
bufio.(*Reader).fill(0xc820440840)

    /usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:97 +0x1e9

bufio.(*Reader).ReadSlice(0xc820440840, 0xed059320a, 0x0, 0x0, 0x0, 0x0, 0x0)

    /usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:328 +0x21a

github.com/nsqio/nsq/nsqd.(*protocolV2).IOLoop(0xc820028178, 0x7fbda3b55750, 0xc8200281f8, 0x0, 0x0)

    /Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/protocol_v2.go:63 +0x2c1

github.com/nsqio/nsq/nsqd.(*tcpServer).Handle(0xc8201c40b0, 0x7fbda3b55750, 0xc8200281f8)

    /Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/tcp.go:43 +0x5c9

created by github.com/nsqio/nsq/internal/protocol.TCPServer

    /Users/mreiferson/dev/src/github.com/nsqio/nsq/internal/protocol/tcp_server.go:33 +0x6ac
```

**Comment by ploxiln** [comment]
unfortunately, no, I don't think that's enough to get anything useful out of

(You must have been using the 0.3.8 release?)

**Comment by mreiferson** [comment]
Bummer, thanks for letting us know.

Looking at https://github.com/nsqio/nsq/blob/master/nsqd/protocol_v2.go#L63, it's hard to imagine how that might have panicd other than an OOM situation? Any way to check metrics around that time for that process?

Gonna close this, please reopen if you see this again and are able to capture the whole trace.
