### ISSUE TITLE
Binary Releases v1.0.0-compat links broken

### ISSUE THREAD

**Issue by CodingMinds** [nsqio/nsq#864]
Links of v1.0.0.-compat at http://nsq.io/deployment/installing.html result in `Access Denied` messages.

E.g. https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F837743820346D4D</RequestId>
<HostId>
h9x/ht4DQsY2igOMUiPO+tQ7HdNou2H0KKwaOf5pk+ZPDNTSP4TaOVF7yYf927WSp2i1fix9zVo=
</HostId>
</Error>
```

**Comment by mreiferson** [comment]
I forgot to upload these!

**Comment by mreiferson** [comment]
done, sorry!
