### ISSUE TITLE
Documentation is not updated for Discovery.

### ISSUE THREAD

**Issue by vikash-tiwari** [nsqio/nsq#870]
Api call for discovery (/lookup?topic=XXX) has been changed in NSQ v1.0.0-compact 

`Response in NSQ prior to v1.0.0-compact
{
status_code: 200,
status_txt: "OK",
data: {
channels: [ ],
producers: [
{
remote_address: "127.0.0.1:39310",
hostname: "vikash.tiwari",
broadcast_address: "vikash.tiwari",
tcp_port: 4150,
http_port: 4151,
version: "0.3.8"
}
]
}
}`

`Response in NSQ v1.0.0-compact
{
channels: [
"emailChannel"
],
producers: [
{
remote_address: "127.0.0.1:40258",
hostname: "vikash.tiwari",
broadcast_address: "vikash.tiwari",
tcp_port: 4150,
http_port: 4151,
version: "1.0.0-compat"
}
]
}
`

**Comment by mreiferson** [comment]
can you open this issue on https://github.com/nsqio/nsqio.github.io and point out where the documentation references the old response format?

**Comment by vikash-tiwari** [comment]
https://github.com/nsqio/nsqio.github.io/issues/17

> can you open this issue on https://github.com/nsqio/nsqio.github.io and point out where the documentation references the old response format?
