### ISSUE TITLE
 nsqd: deferred messages persistence

### ISSUE THREAD

**Issue by eshizhan** [nsqio/nsq#871]
The deferred message is persistence?
My HandleMessage return error, the message should be requeue, and I restart nsqd, the deferred message not be recovered. I missing something?
```
func (th *tailHandler) HandleMessage(m *nsq.Message) error {
        if rand.Intn(99) < 1 {
                return errors.New("error message")
        }
        th.messagesShown++
        return nil
}
```

**Comment by mreiferson** [comment]
Hi @eshizhan — this is a known issue, see #34 and ultimately #510.
