### ISSUE TITLE
nsqd: E_INVALID AUTH invalid number of parameters

### ISSUE THREAD

**Issue by tttlkkkl** [nsqio/nsq#872]
Nsqio/nsqd/protocol_v2.go 502 line. If the number of arguments can only be one, I can't authorize the command successfully.
`	if len(params) != 1 {
		return nil, protocol.NewFatalClientErr(nil, "E_INVALID", "AUTH invalid number of parameters")
	}
 `

**Comment by jehiah** [comment]
@tttlkkkl can you describe what you are trying to do?

[AUTH](http://nsq.io/clients/tcp_protocol_spec.html#auth) is centered around a single secret value (typically something like an OAuth Access Token).

**Comment by tttlkkkl** [comment]
I would like to do a license before the TCP connection, in accordance with the TCP communication protocol provided by you, AUTH command message format like this：

AUTH\n

[ 4-byte size in bytes ][ N-byte Auth Secret ]


I'm sure I've packed it in the right format, but NSQ is continuing to return error messages. A good proof is that the PUB command and the AUTH command command format are roughly the same. However, the same packaging method AUTH can not succeed.
I analyzed the source code, in the 502nd line of the file (Nsqio/nsqd/protocol_v2.go ) found an error. The length of the variable params is 2, not equal to 1. The revised code should look like this
`if len(params) != 2 { return nil, protocol.NewFatalClientErr(nil, "E_INVALID", "AUTH invalid number of parameters") }`

I like this to modify the source code and run, really successful. Please confirm that the version is 0.3.8.


My English is too poor, may not be able to describe clearly, you can run through the authorization process, and the right way to tell me, thank you.

**Comment by jehiah** [comment]
@tttlkkkl can you re-test against version, 1.0 and provide example client code and nsqd configuration to reproduce the error you are seeing?

**Comment by ploxiln** [comment]
@tttlkkkl it sounds like you are implementing the nsq tcp protocol yourself, from scratch. Before deciding that the problem with AUTH is in nsqd, you should see if the stock go client applications, which use the go-nsq library for the tcp connection to nsqd, can do AUTH correctly. For example, try:

```
nsq_tail --consumer-opt=auth_secret,supersecret --nsqd-tcp-address=127.0.0.1:4150 --topic=t1 --channel=c1
```

That works for me with nsqd 1.0.0-compat

**Comment by tttlkkkl** [comment]
Sorry, after checking, the reason for the error is that I have more than one space in the package. I have achieved my goal, and thank you again for your patience @jehiah @ploxiln
