### ISSUE TITLE
a question about NSQD's tcpListener field

### ISSUE THREAD

**Issue by fzbing** [nsqio/nsq#875]
In the source code, `NSQD` struct has three field that is `tcpListener`, `httpListener` and `httpsListener`.

Why need use a `RWMutex` when reading or writing.

Note:
In the source code, only `NSQD.Main` write that three field. So, we first assgin values to that three field, then start the services.

**Comment by mreiferson** [comment]
@fzbing I believe the lock is to prevent race conditions in tests

**Comment by langgo** [comment]
@mreiferson Can you provide an example? thanks。

**Comment by JoseFeng** [comment]
Because nsqlookupd / http_test.go?
go test found no problem to remove the lock.
