### ISSUE TITLE
Once A topic is deleted, could not be created.

### ISSUE THREAD

**Issue by vikash-tiwari** [nsqio/nsq#877]
I follow `getting started` and created a topic and message:
`$ curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'`

Now I delete that topic using REST call 
`http://localhost:4161/topic/delete?topic=test`

Now I am trying to create the same message on topic `test` again, there is no error but topics is not getting created.

**Comment by ploxiln** [comment]
This is an intended behavior, to avoid a problem where the topic is accidentally re-created by consumers. See http://nsq.io/components/nsqlookupd.html#deletion_tombstones
