### ISSUE TITLE
nsqd listen on 4151 for http client, but tell lookupd it listen on 80

### ISSUE THREAD

**Issue by dunixd** [nsqio/nsq#882]
There is a group of host that only 22, 80, 443 is opened, and nsqd is supposed to installed on.
Now 80 is used by nginx to proxy all http request, 443 is free. So I don't know if this is possible, nsqd listen on 443 for tcp port and 4151 for http, but it tell lookupd with 80 as http port. And let nginx proxy nsqd's http request properly, maybe after auth. Then other component can query nsqd through http protocol transparently.

So if it is useful to add a param to support what I describe when nsqd start?

**Comment by jehiah** [comment]
You can run any component of nsq on any port you want.
```
Usage of nsqd:
...
  -tcp-address string
    	<addr>:<port> to listen on for TCP clients (default "0.0.0.0:4150")
```

**Comment by ploxiln** [comment]
I think @dunixd knows he can make nsqd use a different http port, but he wants it to use listen on port 4151, while reporting that it uses port 80 when it registers with nsqlookupd. Then nsqadmin will make http requests to port 80, and nginx will proxy those requests to nsqd on localhost 4151.

Another way to solve this strange problem, is to run nsqd inside a container (e.g. with docker). It can listen on port 80 inside the container, have that mapped/forwarded from port 4151 outside the container, and nginx listening on port 80 outside the container and proxying to port 4151.

**Comment by ploxiln** [comment]
As a shorter explanation: he wants BroadcastHttpPort, which does for the port what BroadcastAddress does for the address - give the port/address to be used from other servers to contact this process, through port/address mappings.

**Comment by dunixd** [comment]
@ploxiln what you described is exactly what I want!
As I know, nsqd's AUTH will not check http request, maybe then it is too busy for the auth service.
But if nsqd is behind nginx by the BroadcastHttpPort, then auth for the http is possible.
Otherwise it is easy to modify data through http request if port is opened, or not so convenient if not expose http port.

**Comment by dunixd** [comment]
Will you consider to add such a param in the future?

**Comment by sujeshthekkepatt** [comment]
@dunixd  How did you address this auth problem? Using an Nginx as a reverse proxy?
