### ISSUE TITLE
nsqd/pynsq: Channels don't receive messages

### ISSUE THREAD

**Issue by checkraise** [nsqio/nsq#894]
Steps:

1. Creating a topic
2. Publishing some messages to the topic
3. Creating several channels
4. Reading simultaneously from all of these channels, handling messages asynchronously, then sending FIN for handled messages

What I expect: if I published N messages to the topic, then each channel should receive these N messages.

What really happens: only one channel receives all messages, other channels receives nothing.

UPD: nsqd version: nsqd v1.0.0-compat (built w/go1.8)
client: pynsq==0.8.0

**Comment by jehiah** [comment]
@checkraise Can you provide logs from your client and `nsqd` and possibly a script that can help us reproduce this?

I would also suggest using nsqadmin to get visibility of what the topic/channel topology and metrics are. Can you post a screenshot from nsqadmin between each of the steps you listed?

**Comment by mreiferson** [comment]
I think this is "working as intended".

If you want all channels to receive all messages for a topic before anything exists, you need to create the topic and channels up front, before publishing messages.

By doing (2) before (3) you'd see the behavior you've documented.
