### ISSUE TITLE
nsqd error not found

### ISSUE THREAD

**Issue by keaixiaou** [nsqio/nsq#895]
i use brew to install nsq in mac
when i do 【curl -d 'hello world' 'http://127.0.0.1:4151/put?topic=demo'】 this step ,it return 【{"message":"NOT_FOUND"}】, and nsqd shows 【404 POST /put?topic=demo (127.0.0.1:51524) 465ns】how should i do ?
my mac version is 10.12.2 (16C67)
and i see when nsqd start up ,it shows 【ERROR: no available nsqlookupd to query for channels to pre-create for topic test】

**Comment by jehiah** [comment]
@keaixiaou the correct API endpoint for the current nsqd version is `/pub` not `/put`.

http://nsq.io/components/nsqd.html#post-pub

**Comment by keaixiaou** [comment]
ok ,thanks!
