### ISSUE TITLE
./bench.sh failed

### ISSUE THREAD

**Issue by wangligang** [nsqio/nsq#902]
when i use ./bench.sh . it will report:
nsqd.go:19:9: use of internal package not allowed
nsqd.go:20:9: use of internal package not allowed
go version:go version go1.8 darwin/amd64

**Comment by ploxiln** [comment]
The nsq repo must be in the correct place in your `$GOPATH` e.g. `$GOPATH/src/github.com/nsqio/nsq`. You also have to use `gpm` to install the dependencies needed. See http://nsq.io/deployment/installing.html#building-from-source
