### ISSUE TITLE
*:struct field tag `json:'version'` not compatible with reflect.StructTag.Get: bad syntax for struct tag value (vet)

### ISSUE THREAD

**Issue by zouyee** [nsqio/nsq#906]
when using  `go vet`,I got much errors.such as
`struct field tag `json:'version'` not compatible with reflect.StructTag.Get: bad syntax for struct tag value (vet)`

**Comment by gocs** [comment]
use double quotes in the word version? because the linter exempts the warning.

```go
type Foo struct {
        Version string `json:"version"`
}
```

**Comment by ploxiln** [comment]
yes, that was done in #907

**Comment by Logicbloke** [comment]
Get rid of that space between the colon and the double quotes.
`Version string `json:"version"``
instead of
Version string `json: "version"`
