### ISSUE TITLE
Does nsq support push message by IP group, Department ?

### ISSUE THREAD

**Issue by AlexiaChen** [nsqio/nsq#908]
I want to broadcast message from server to client by specific "segment", such as, department in company and IPs.    I read all the most documents about NSQ and doest not find anything useful feature for my needs.

Does anyone have  solution to solve this ? Thank you.

**Comment by ploxiln** [comment]
You'll have to come up with a scheme that uses topics and channels to achieve what you want. You could write a consumer/reader application that filters the messages from a topic by some property, and sends them to a new topic, or to some other system. It's also possible that NSQ is not optimal for your use case.

**Comment by AlexiaChen** [comment]
@ploxiln    Thx,  maybe I will consider use ActiveMQ instead.
