### ISSUE TITLE
Sse

### ISSUE THREAD

**Issue by joeblew99** [nsqio/nsq#924]
I would like to publish events out as server side events. It seems a very logical approach for a message queue and am surprised it's not implemented.

I know edge does not support it but there is a polyfill for it.

So I was wondering if this is a useful addition ?

SSE is also a rather simple and well done protocol in golang so I expect it will be easy to do

**Comment by mreiferson** [comment]
@joeblew99 in order to support this, you would write an edge API that speaks SSE and then that would publish to `nsqd` via HTTP or NSQ's native protocol. Closing.

**Comment by BertHooyman** [comment]
> I would like to publish events out as server side events. It seems a very logical approach for a message queue and am surprised it's not implemented.
> 
> I know edge does not support it but there is a polyfill for it.
> 
> So I was wondering if this is a useful addition ?
> 
> SSE is also a rather simple and well done protocol in golang so I expect it will be easy to do

I agree with your observation from 2017. Did you ever realize this idea?
