### ISSUE TITLE
deflate level specified from client lib in IDENTIFY not work

### ISSUE THREAD

**Issue by DoraALin** [nsqio/nsq#926]
Greetings,
Upon identify with specified deflate level, nsqd does not accept it but using max deflate level in option.

in IDENTIFY(), identifyData.Deflate does not used to decide the deflate level, is it a bug here?
line #396, protocol_v2.go
`deflate := p.ctx.nsqd.getOpts().DeflateEnabled && identifyData.Deflate
	deflateLevel := 0
	if deflate {
		if identifyData.DeflateLevel <= 0 {
			deflateLevel = 6
		}
		deflateLevel = int(math.Min(float64(deflateLevel), float64(p.ctx.nsqd.getOpts().MaxDeflateLevel)))
	}`

besides, there is a typo in attribute of client connection in nsqadmin, when deflate apply.
![image](https://user-images.githubusercontent.com/6905536/29257715-df1a6e24-80e6-11e7-9759-e1146edf5efa.png)

**Comment by mreiferson** [comment]
see #927
