### ISSUE TITLE
nsq_to_file: --topic-pattern causes connection leaks

### ISSUE THREAD

**Issue by jxskiss** [nsqio/nsq#930]
When giving --topic-pattern argument, nsq_to_file create new connection to lookupd every "topicPollRate".

With about 10 topics in my deployment, I use --topic-pattern=".*" to archive messages, after about one day, the log file begins to be filled with "too many open files" errors.

"lsof | grep nsq_to_f" shows there are bunch of connections from nsq_to_file to lookupd servers.

I guess the problem is caused by "TopicDiscoverer.syncTopics", each time it runs, it create new http client object, but the "DisableKeepAlives" is not enabled for the transport, so they never get released.

**Comment by jxskiss** [comment]
Is there some other guys using the nsq_to_file utility?

**Comment by ploxiln** [comment]
Yes, it is commonly used for "archiving" a topic, but I suspect that heavy/core nsq users use it only for one topic at a time (a separate process for separate topics), instead of using `--topic-pattern`.

**Comment by jxskiss** [comment]
Thanks for the confirmation. Since each topic's messages are written to seperate files, the --topic-pattern is very convenient for archiving all topic or some selected topic in situation where workload is not that heavy.

**Comment by mreiferson** [comment]
@jxskiss thanks for the bug report, are you interested in submitting a PR to fix this?

**Comment by jxskiss** [comment]
@mreiferson Glad to do this, I will submit a PR as soon as possible.

**Comment by mreiferson** [comment]
thanks! see #935
