### ISSUE TITLE
nsqd: many zero-size .tmp files on disk

### ISSUE THREAD

**Issue by djmally** [nsqio/nsq#938]
nsqd is creating numerous files like `xyz.diskqueue.meta.dat.some_number.tmp`on disk, all of which have zero size. On one of my production machines, there are ~3000 of these files, all of which are 0 bytes in size, and have persisted for the last 10 days or so.

It's not clear to me where these files come from, what their purpose is, or how they get deleted, but it seems problematic to me that so many are generated. Have I stumbled across a bug here, or is it intentional that these files are persisting for so long on disk?

**Comment by ploxiln** [comment]
The `*.tmp` files are supposed to be immediately renamed over the `*.dat` files, they should not be left lying around. Are there any error messages in your nsqd logs? Something like `DISKQUEUE(...) failed to sync - ...`?

**Comment by djmally** [comment]
Yup, looks like the machines ran out of disk space for a period, I'm seeing a number of messages like this:
```
ERROR: diskqueue(xyz) failed to sync - write /mnt/data/nsq/xyz.diskqueue.meta.dat.#.tmp: no space left on device
```
...which is an obvious reason for this to fail. I don't think this happens under other conditions, since the disk usage spike was only for a day, and none of the `.tmp` files have last-modified dates other than the day of the spike.

**Comment by djmally** [comment]
Yup, looks like the machines ran out of disk space for a period, I'm seeing a number of messages like this:
```
ERROR: diskqueue(xyz) failed to sync - write /mnt/data/nsq/xyz.diskqueue.meta.dat.#.tmp: no space left on device
```
...which is an obvious reason for this to fail. I don't think this happens under other conditions, since the disk usage spike was only for a day, and none of the `.tmp` files have last-modified dates other than the day of the spike.

**Comment by mreiferson** [comment]
@djmally `nsqd` _tries_ to function as correctly as possible under conditions like this, in some cases it will also reject a `PUB` if a given message would have been written to a failing disk. Given what you're reporting, it seems like it's behaving as expected so I'm going to close.

Please re-open if you find any evidence to the contrary, thanks.
