### ISSUE TITLE
Kafka compatibility layer

### ISSUE THREAD

**Issue by mcandre** [nsqio/nsq#939]
Could we get an adapter for Kafka clients to use NSQ as a backend? Kafka is horribly flakey, so it would be helpful if NSQ could serve as a dropin replacement. In the long run, message busses should definitely convert to NSQ, but a compatibility layer would help to transition.

**Comment by andyxning** [comment]
IIUC, this requires implementation of Kafka protocol in both producer side and consumer side.

**Comment by mreiferson** [comment]
@mcandre Unfortunately, I don't think this is a realistic goal with the current (lack of) guarantees that NSQ provides.
