### ISSUE TITLE
nsqd and nsqlookupd syslog severity error

### ISSUE THREAD

**Issue by Thermi** [nsqio/nsq#941]
Hi,

I discovered that nsqd and nsqlookupd log rather mundane messages to syslog with severity error.
I saw that in StackDriver on GCP.
Excerpt:
```
{
 insertId:  "1kc45xyftu9xws"   
 labels: {…}   
 logName:  "projects/rimoto-171513/logs/nsqlookupd"   
 receiveTimestamp:  "2017-09-08T15:12:25.170756645Z"   
 resource: {…}   
 severity:  "ERROR"   
 textPayload:  "[nsqlookupd] 2017/09/08 15:12:19.822112 200 GET /ping (10.20.3.1:46944) 436ns
"   
 timestamp:  "2017-09-08T15:12:19Z"   
}
```

Due to a lack of other deployment or test environment, I can not check if the daemons  actually log with severity error that or if it is something another software (component) does. I would really appreciate this being confirmed and if it is, changed. The reason is, that messages like that are not errors. They are of rather informational nature (severity info). Having them log with severity info would make a log excerpt of messages with severity error much cleaner and actually display errors only (except if other software has problems like that, too).

**Comment by ploxiln** [comment]
nsqd and nsqlookupd do not log to syslog on their own, they only log to stdout. Whichever tool relays their stdout log lines to syslog is what must be setting the severity.

**Comment by Thermi** [comment]
Well, as the name implies, stderr is for errors. I'd expect informative output to be printed to stdout or not at all, unless verbose or debug mode is enabled. As of now, I can not easily figure out which of the logs are actual problems and which are just informative output.

**Comment by ploxiln** [comment]
FWIW, error messages have "ERROR:" in them. (More recently, since the last release, all info messages have "INFO:" in them.)

**Comment by ploxiln** [comment]
I should have mentioned that, after the last release, the ability to set logging level to e.g. warning and above was added.

**Comment by Thermi** [comment]
Ah, that is very helpful. I will rotate the docker containers in my deployments then. Thank you!

**Comment by mreiferson** [comment]
thanks everyone!

**Comment by Thermi** [comment]
Errr, the code with the changes hasn't been released yet. 1.0.0 was released in march. The code for the logger configuration was merged on may 20th (#892).

**Comment by ploxiln** [comment]
yeah that's what I was trying to say, *after* the last release, these changes were added, so they're not yet in a release

**Comment by Thermi** [comment]
Hmh. Meh. :/
