### ISSUE TITLE
 docker exec -it nsqd nsq_to_http --topic=test3  --lookupd-http-address=nsqlookupd:4161  --post=http://192.168.2.159:4151/put?topic=tes3

### ISSUE THREAD

**Issue by zhaochenglan** [nsqio/nsq#943]
2017/09/17 06:17:05 INF    1 [test3/nsq_to_http] querying nsqlookupd http://nsqlookupd:4161/lookup?topic=test3
2017/09/17 06:17:05 INF    1 [test3/nsq_to_http] (192.168.2.159:4150) connecting to nsqd
2017/09/17 06:17:06 ERR    1 [test3/nsq_to_http] (192.168.2.159:4150) error connecting to nsqd - dial tcp 192.168.2.159:4150: i/o timeout
2017/09/17 06:18:17 INF    1 [test3/nsq_to_http] querying nsqlookupd http://nsqlookupd:4161/lookup?topic=test3
2017/09/17 06:18:17 INF    1 [test3/nsq_to_http] (192.168.2.159:4150) connecting to nsqd
2017/09/17 06:18:18 ERR    1 [test3/nsq_to_http] (192.168.2.159:4150) error connecting to nsqd - dial tcp 192.168.2.159:4150: i/o timeout
2017/09/17 06:19:17 INF    1 [test3/nsq_to_http] querying nsqlookupd http://nsqlookupd:4161/lookup?topic=test3
2017/09/17 06:19:17 INF    1 [test3/nsq_to_http] (192.168.2.159:4150) connecting to nsqd
2017/09/17 06:19:18 ERR    1 [test3/nsq_to_http] (192.168.2.159:4150) error connecting to nsqd - dial tcp 192.168.2.159:4150: i/o timeout

**Comment by mreiferson** [comment]
If you're having trouble configuring NSQ to work in Docker containers, please use the mailing list for questions.

**Comment by zhaochenglan** [comment]
oh,thks
