### ISSUE TITLE
nsqd: when push the metric by UDP the nsq crashed

### ISSUE THREAD

**Issue by powxiao** [nsqio/nsq#944]
1. run nsqd by this command:
./nsqd --statsd-address=127.0.0.1:8125 --statsd-interval=1s

2. create a UDP server to receive the stats,

3.  after a  second, nsqd crashed with these info:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7ab7bc]

goroutine 40 [running]:
github.com/nsqio/nsq/nsqd.(*NSQD).statsdLoop(0xc4201600f0)
	/home/xxxx/gopath/src/github.com/nsqio/nsq/nsqd/statsd.go:126 +0x18ac

'lastMemStats' is a nil poniter and use it directly.
maybe should check this variable before  the first time.

**Comment by jehiah** [comment]
@powxiao Can you provide details on what nsqd version you are running?

**Comment by powxiao** [comment]
curl -X GET http://localhost:4151/info      
{"version":"1.0.0-compat","broadcast_address":"ubuntu","hostname":"ubuntu","http_port":4151,"tcp_port":4150,"start_time":1506678277}

**Comment by mreiferson** [comment]
Ahh, thanks.

This issue was fixed in #911, which will go out with the next release.
