### ISSUE TITLE
it seems that nsq can not support distributed deployment, as i have find the bug!!!

### ISSUE THREAD

**Issue by owey0312** [nsqio/nsq#947]
it seems that nsq can not support distributed deployment, as i have find the bug!!!
"no available nsqlookupd to query for channels to pre-create for topic"
the lookup peer created after the gettopic method, so we can not get nsqlookupd http address when call gettopic method.

**Comment by mreiferson** [comment]
That means that `nsqd` cannot connect to any of the configured `nsqlookupd` — that's not a bug, it's an error in your configuration.

**Comment by ploxiln** [comment]
I think that he's talking about this happening at startup. Most likely, he's worrying about these ERROR messages at startup which are actually expected and thus misleading:

```
$ ../build/nsqd --log-level=debug --lookupd-tcp-address=127.0.0.1:4160
[nsqd] 2017/10/20 10:46:23.561550 INFO: nsqd v1.0.1-pre3 (built w/go1.8.3)
[nsqd] 2017/10/20 10:46:23.561628 INFO: ID: 602
[nsqd] 2017/10/20 10:46:23.569789 INFO: TOPIC(t1): created
[nsqd] 2017/10/20 10:46:23.569814 ERROR: no available nsqlookupd to query for channels to pre-create for topic t1
[nsqd] 2017/10/20 10:46:23.570025 INFO: TOPIC(t1): new channel(c5)
...
[nsqd] 2017/10/20 10:46:23.570769 INFO: NSQ: persisting topic/channel metadata to nsqd.dat
[nsqd] 2017/10/20 10:46:23.571765 INFO: TCP: listening on [::]:4150
[nsqd] 2017/10/20 10:46:23.571864 INFO: HTTP: listening on [::]:4151
[nsqd] 2017/10/20 10:46:23.571904 INFO: LOOKUP(127.0.0.1:4160): adding peer
...
```

If he actually ran into a problem, then somehow the topic was created previously and was in the metadata when nsqd started up, but the channels were not created back when the topic was created (we've had a report about this once before). In this case I'd still consider it a config/usage issue.
