### ISSUE TITLE
building source install nsq-0.3.8, error: use of internal package not allowed

### ISSUE THREAD

**Issue by acyi** [nsqio/nsq#952]
hello, 
when I install the nsq-0.3.8 in the source building installation with http://nsq.io/deployment/installing.html , in the section compiling,  I encountered such a problem that "xxx  use of internal package not allowed".

I can't resolve this problem

**Comment by ploxiln** [comment]
This happens when nsq is not checked-out into your GOPATH (specifically `$GOPATH/src/github.com/nsqio/nsq`)
