### ISSUE TITLE
NSQD killed with SIGPIPE signal

### ISSUE THREAD

**Issue by beegmon** [nsqio/nsq#958]
Hello,

I am running nsqd 0.3.8. I need to upgrade but I haven't gotten around to it yet.

Anyways, I run nsqd on centos 7 under systemd. We noticed one of our services had failed and traced it to the fact that NSQD was not running at the time. 

NSQ has been super stable over the year we have been using it with varying work loads. I am still trying to determine if the system was under memory pressure and thus may have killed NSQD due to OOM, but I am curious if there are situations in which NSQD would die with a SIGPIPE signal.

SystemD didn't catch this failure either with Restart=on-failure, so I have changed that to Restart=always for now. 

From my understanding SIGPIPE only happens when a process tries to write to a socket that doesn't have a reader left, or when the write buffer is full. I am not sure if this applies to NSQD but I wanted to ask under what conditions, if any, NSQD would be killed with a SIGPIPE.

**Comment by ploxiln** [comment]
https://golang.org/pkg/os/signal/#hdr-SIGPIPE

> A write to a broken pipe on file descriptors 1 or 2 (standard output or standard error) will cause the program to exit with a SIGPIPE signal. A write to a broken pipe on some other file descriptor will take no action on the SIGPIPE signal, and the write will fail with an EPIPE error.

SIGPIPE should not cause nsqd to be killed
