### ISSUE TITLE
many connections vs one connection, about one machine writes massive messages to one NSQD

### ISSUE THREAD

**Issue by hotdust** [nsqio/nsq#959]
Hello, I'm go newbie, this maybe a stupid question:
Question 1:
when one machine writes massive messages to one NSQD, which is faster?
1), creating many producer, and multiple goroutine use these producers to write message.
2), creating one producer, and multiple goroutine use one producer to write message.

Question 2:
if using one machine writes to one NSQD, which approach is recommanded? 1) or 2)

my test ---------------------------------------
result:            1) is a little faster than 2)  
test sample:   50000 messages, 1) uses about 1.5s, 2) uses about 1.8s  
> when 100000 messages, 2) occurs write error 

```
1) source : this is a connections pool. It will generate 10 connections.

	pool, err := NewPool("127.0.0.1:4150", 10)
	if err != nil {
		log.Println("new pool error:", err)
		return
	}

	var waitgroup sync.WaitGroup
	poolSize := 50000
	start := time.Now()
	for i := 0; i < poolSize; i++ {
		waitgroup.Add(1)
		go func() {
			pool.Publish("test", "test performance msg")
			waitgroup.Done()
		}()
	}
	waitgroup.Wait()
	log.Printf("pool size(%d)  elapsed time:%v\n", poolSize, time.Since(start))
```

```
2) source
	pool, err := nsq.NewProducer("127.0.0.1:4150", nsq.NewConfig())
	if err != nil {
		log.Println("new pool error:", err)
		return
	}

	var waitgroup sync.WaitGroup
	poolSize := 50000
	start := time.Now()
	for i := 0; i < poolSize; i++ {
		waitgroup.Add(1)
		go func() {
			pool.Publish("test", []byte("test performance msg"))
			waitgroup.Done()
		}()
	}
	waitgroup.Wait()
	log.Printf("pool size(%d)  elapsed time:%v\n", poolSize, time.Since(start))
```

my thinking:
I read a little nsq source, and few articles, topic and channel are implemented by go chan. Besides writing chan, NSQD does same extra processes. Except extra processes, I think performance of 1) and 2)  should be same. Time difference of 1) and 2) maybe that extra processes.

**Comment by mreiferson** [comment]
I would expect (1) to be faster due to slightly less overhead and contention at high rates.
