### ISSUE TITLE
to_nsq consistently throws a runtime error

### ISSUE THREAD

**Issue by filipefigcorreia** [nsqio/nsq#962]
Running this example [provided in the docs](https://github.com/nsqio/nsq/tree/master/apps/to_nsq):
```
echo "one,two,three" | to_nsq -delimiter="," -topic="topic" -nsqd-tcp-address="127.0.0.1:4150"
```

Results in this error message:
```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.main()
	/private/tmp/nsq-20171012-47917-6v9sj4/nsq-1.0.0-compat/apps/to_nsq/to_nsq.go:71 +0x9b4
```

May this be caused by a bug? When I run the command with a different IP address (even a non-existent one) it still issues the same error.

**Comment by ploxiln** [comment]
I think this was fixed in #867
