### ISSUE TITLE
Spring (boot) connector?

### ISSUE THREAD

**Issue by prafulthakare** [nsqio/nsq#964]
Hi, Is there a spring or spring boot connector for NSQ? I have a use case where my producers will be on Spring 3.x and Spring boot 2.0 and consumer on Spring boot 2.0.
I couldn't find any info on spring support for nsq.

**Comment by ploxiln** [comment]
Nope. But you can publish with a generic http client, and there are a few java libraries you could peruse: http://nsq.io/clients/client_libraries.html

**Comment by prafulthakare** [comment]
thanks Ploxiln, yes JavaNSQClient looks interesting.
Is there any documentation on the effective use of executors?
Also, is it recommended to create and destroy the producer before and after producing the message? or it can be kept running since startup of app?

**Comment by ploxiln** [comment]
The "producer" is most likely intended to be kept alive and used to publish multiple messages.
