### ISSUE TITLE
Error on topic details

### ISSUE THREAD

**Issue by lifeRockss** [nsqio/nsq#965]
Hi,

I am able to publish and consume message on my nsq on docker but 
I am getting following error when I click on my TestTopic at http://127.0.0.1:4171/topics/TestTopic

`UPSTREAM_ERROR: Failed to query any nsqd: Get http://127.0.0.1:4151/stats?format=json: dial tcp 127.0.0.1:4151: getsockopt: connection refused`
But  http://127.0.0.1:4151/stats?format=json from my browser window works fine with following o/p

`{
"version": "1.0.0-compat",
"health": "OK",
"start_time": 1510144635,
"topics": [
{
"topic_name": "TestTopic",
"channels": [
{
"channel_name": "dustin",
"depth": 1,
"backend_depth": 0,
"in_flight_count": 0,
"deferred_count": 0,
"message_count": 6,
"requeue_count": 0,
"timeout_count": 0,
"clients": [],
"paused": false,
"e2e_processing_latency": {
"count": 0,
"percentiles": null
}
}
],
"depth": 0,
"backend_depth": 0,
"message_count": 6,
"paused": false,
"e2e_processing_latency": {
"count": 0,
"percentiles": null
}
}
]
}`
also http://127.0.0.1:4161/lookup?topic=TestTopic works fine with following output
`{
"channels": [
"dustin"
],
"producers": [
{
"remote_address": "172.18.0.3:34540",
"hostname": "636f34256a31",
"broadcast_address": "127.0.0.1",
"tcp_port": 4150,
"http_port": 4151,
"version": "1.0.0-compat"
}
]
}`

my yaml compose file looks like this

`version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160  --broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"`

If I remove the --broadcast-address=127.0.0.1 then my consumer code is unable to connect to the server with host not found exception on some some random host like '636f34256a31'

any pointers?

**Comment by lifeRockss** [comment]
bit weird but resolved the issue by changing  `--broadcast-address=127.0.0.1` to ` --broadcast-address=${HOST_NAME}` for 
command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
where ${HOST_NAME}  is set in shell as `export HOST_NAME=$HOSTNAME`

**Comment by mreiferson** [comment]
Thanks for the info.

I'm going to assume that this is more of a configuration issue than something that needs to be fixed in `nsqd`, closing.
