### ISSUE TITLE
fail to run dep ensure since golang.org is blocked in china

### ISSUE THREAD

**Issue by gzliudan** [nsqio/nsq#969]
dep ensure
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "golang.org/x/sys": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys?go-get=1": Get http://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:80: i/o timeout

ProjectRoot name validation failed

**Comment by ploxiln** [comment]
I think this is a bug in the Chinese government.

(I also think the Great Firewall would block github.com more often than golang.org so I don't think there's much point in working around this.)

**Comment by judwhite** [comment]
You could commit `./vendor`

**Comment by Tinywan** [comment]
I too
```bash
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "golang.org/x/sys": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sys?go-get=1": Get http://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection timed out

ProjectRoot name validation failed
```

**Comment by ploxiln** [comment]
I wonder if go modules offer a way to accomplish this ... have go download golang.org/x/sys from github.com/golang/sys and not try to access golang.org at all
