### ISSUE TITLE
nsqlookupd:  delete_topic  and delete_channel  404

### ISSUE THREAD

**Issue by yunnian** [nsqio/nsq#972]
The document said  have the api,but they are 404

 I found they are deleted in the source code,is right?

**Comment by jehiah** [comment]
@yunnian can you provide logs for an example HTTP request you are making to nsqlookupd?

I do see that we need to update docs to reflect the v1 endpoints (`/topic/delete` and `/channel/delete`) but the other endpoints (`/delete_topic` and `/delete_channel`) should still work.

**Comment by yunnian** [comment]
curl -I  -X DELETE "http://127.0.0.1:4161/delete_topic?topic=test"
curl -I -X DELETE "http://127.0.0.1:4161/delete_channel?topic=test&channel=Fighting"
curl -I  -X DELETE "http://127.0.0.1:4161/api/topics?topic=test"

 They are all   HTTP/1.1 404 Not Found

**Comment by jehiah** [comment]
@yunnian none of those endpoints respect the `DELETE` http verb.

https://github.com/nsqio/nsq/blob/master/nsqlookupd/http.go#L44-L48

**Comment by yunnian** [comment]
sorry , I made a mistake, I look for the api in  nsqadmin/http.go . At that time, I just want to see if it is post or get, the document does not explain.
Thank you for your answer.

**Comment by ploxiln** [comment]
I went looking just now and found POST mentioned here: http://nsq.io/components/nsqd.html#post-topicdelete but it may not be easy to find. Anyway I'm glad this is resolved for you.

**Comment by yunnian** [comment]
no no no ,I mean  the lookupd's api ,   url is http://nsq.io/components/nsqlookupd.html#delete_topic,  document not write is post or get .

**Comment by ploxiln** [comment]
Ah, I overlooked that, sorry. I've opened github.com/nsqio/nsqio.github.io/pull/29

**Comment by lambdaq** [comment]
it's  `curl -XPOST  http://127.1:4161/topic/delete?topic=blah` in case anyone else is having trouble deleting shit.
