### ISSUE TITLE
if all the nsqlookup down(perhaps the idc room has been hung up)，then the relationship of channel or topic will be gone

### ISSUE THREAD

**Issue by huangsanye** [nsqio/nsq#973]
if all the nsqlookup down(perhaps the idc room has been hung up)，then the relationship of channel or topic will be gone。

**Comment by mreiferson** [comment]
Message delivery should be unaffected, but the requirement is to have _at least one_ `nsqlookupd` available at all times (which should be straightforward, as they do not coordinate).
