### ISSUE TITLE
godep get github.com/bitly/nsq/... failure

### ISSUE THREAD

**Issue by zhangyide** [nsqio/nsq#976]
godep get github.com/bitly/nsq/... is failing.It output like this.
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: D:\go-workspace\src
godep: [WARNING]:       $GOPATH: D:\go-workspace
warning: "github.com/bitly/nsq/..." matched no packages
can't load package: package .: no buildable Go source files in D:\go-workspace\src
godep: exit status 1

**Comment by aaronjheng** [comment]
**github.com/bitly/nsq** is original. Use **github.com/nsqio/nsq** instead.

**Comment by zhangyide** [comment]
oh oh,  thanks!
