### ISSUE TITLE
how to set the log file path of nsqd and nsqlookupd

### ISSUE THREAD

**Issue by gzliudan** [nsqio/nsq#977]
there is no log-path, only data-path

**Comment by ploxiln** [comment]
There is currently no feature to log to file directly, logs are always written to stderr of the process (which is the terminal, if you run it in a terminal). You can use a service manager like systemd, upstart, docker etc. to have the stderr of the process written to rotating log files. (Unless you use windows. Long story.)

**Comment by gzliudan** [comment]
Is there a example service and configure file for systemd in centos 7.x?

**Comment by ploxiln** [comment]
#761 seems to have an example (and says you need to remove the `Type=` line)

**Comment by gzliudan** [comment]
Yes, I tested it, and it works. I wish there is an yum or rpm install package for centos 7.x

cat > /usr/lib/systemd/system/nsqlookupd.service <<-EOF
[Unit]
Description=nsqlookup daemon Service
After=network.target

[Service]
PrivateTmp=yes
ExecStart=/usr/local/nsq/bin/nsqlookupd -config /etc/nsq/nsqlookupd.conf
Restart=always

[Install]
WantedBy=multi-user.target
EOF

cat > /usr/lib/systemd/system/nsqd.service <<-EOF
[Unit]
Description=Realtime distributed messaging (nsqd)
After=network.target

[Service]
PrivateTmp=yes
ExecStart=/usr/local/nsq/bin/nsqd -config /etc/nsq/nsqd.conf
Restart=always

[Install]
WantedBy=multi-user.target
EOF

**Comment by ploxiln** [comment]
I'm glad you got it working :)
