### ISSUE TITLE
config file is not working for nsqadmin

### ISSUE THREAD

**Issue by gzliudan** [nsqio/nsq#978]
I set lookupd-http-addres in config file for nsqadmin, but it's not working:

/usr/local/nsq/bin/nsqadmin -config /etc/nsq/nsqadmin.conf
[nsqadmin] 2017/12/28 15:07:02.900520 --nsqd-http-address or --lookupd-http-address required.

cat  /etc/nsq/nsqadmin.conf
http-address = "0.0.0.0:4171"
lookupd-http-address = "127.0.0.1:4161"

**Comment by aaronjheng** [comment]
It should be a string list in config file, not a string literal. 
https://github.com/nsqio/nsq/blob/master/contrib/nsqadmin.cfg.example

**Comment by gzliudan** [comment]
thanks, but still can not work:

 cat /etc/nsq/nsqadmin.conf
http-address = "0.0.0.0:4171"

nsqlookupd_http_addressesv= [
    "127.0.0.1:4161"
]

**Comment by aaronjheng** [comment]
Wrong spelling.

**Comment by gzliudan** [comment]
Sorry, it's my mistake. Now it works.
