### ISSUE TITLE
Confusion about using NSQ in a distributed Environment

### ISSUE THREAD

**Issue by beegmon** [nsqio/nsq#980]
Hello!

We have been using NSQ for a while (nearly 2 years) with no real issues. We are currently running 0.3.8, with 1.0-compat on the road map here shortly. However, I seem to have confused myself in terms of how to use NSQ in a distributed environment, and we are seeing issue with message piling up on the publishing hosts.

In our environment we have the following:

30 instances each running a NSQd daemon, with their broadcast address set to their hostname, and the nsqlookupd address configured to a single nsqlookupd dameon running on a dedicated instances (in AWS).

Clients (nodejs and python processes) are configured to read/write to their local NSQd daemons.

We expected to not have to configure a client with a lookupd address, and only an NSQd tcp/http address for reading and writing.

We expected the local (to that processes) NSQ daemon (which is configured with a lookupd address) to register topics created on that host, and discover other hosts which also have those same topics, and connect to those other hosts to retrieve messages for the client.

At least that how we thought things were working, but apparently that isn't the case and some clients have been configured with a lookupd address, and other clients haven't...causing confusion about what the right way is to configure clients and daemons in a distributed environments across many nodes.

Ideally I would like to see the following:

A client connects to an NSQ daemon on its host @ 127.0.0.1 for reading and writing. It does not use lookupd but instead depends on the localhost nsqd to register and discover other nsqd hosts and their topics. The local nsqd instance is connectable from other hosts in the cluster.

The Localhost NSQd daemon is configured with an NSQlookupd address of a central nsqlookupd instance which is shared by all the nodes in the environment.

The localhost nsqd instance registers itself, the topics it manages, and connects to other nsqd instances to read messages waiting on other hosts for a said topic.

This is the way we thought things were working, and looking at some old issues that seemed to be the case. But something seems to have changed and we can't seem to track it down.

Is the way we have things setup now correct, or are we missing something?

**Comment by jehiah** [comment]
I think you are missing some context about how `nsqd` functions in a distributed environment. `nsqd` is an isolated data node. It does not coordinate with other data nodes. This allows nsqd to be resilient in aggregate to failures.

A good  design reference for you is http://nsq.io/deployment/topology_patterns.html

Your pattern of having a data source write to the local nsqd is the recommended configuration.

It's typical to decouple consumers from knowledge of the location of data sources, and to configure consumers with nsqlookupd, not any local nsqd address. Consumers then use nsqlookupd for discovery and connect to ALL nsqd nodes that have messages that topic. That allows the consumer to scale horizontally by adding more consumers when you need more capacity, and avoids bottlenecks of nsqd instances not getting messages consumed, as every consumer for a topic is connected and can potentially get those messages.

Hopefully this helps. Glad nsq has been working well for you for 2+ years!

**Comment by beegmon** [comment]
Thank you for filling in the missing context around nsqd!

I haven't touched nsq for some time, mostly because it just works and we almost never have issues with it but my documentation around the use NSQ for our project is pretty sparse, so I just couldn't connect the dots. Now it makes sense again!

Clients write local (client -> local nsqd instance -> nsqd reports the topics it holds to nsqlookupd)

Clients read global (client -> nsqlookupd (to find other nodes with that topic) -> client connects to other nodes -> reads queued messages from those nodes for that topic

Thank you for sparking my memory and sorry for the noise. This should have been something I was able to gather from the documentation, but it just wasn't clicking.
