### ISSUE TITLE
I want a long deferre time  ，but it did not take effect after setting up

### ISSUE THREAD

**Issue by yunnian** [nsqio/nsq#986]
I read the doc:
![image](https://user-images.githubusercontent.com/5779513/34955450-6444968c-fa5f-11e7-8f8a-1eb557a4c8c7.png)

so, I reset  the max-req-timeout,but the result still return .E_INVALID

![image](https://user-images.githubusercontent.com/5779513/34955249-8b6d8bb6-fa5e-11e7-8091-1695f7537125.png)

 It's json have something wrong?   Wait for your answer, thank you

**Comment by ploxiln** [comment]
Copying and pasting (and fenced-code-block quoting) plain text from logs is better than posting screen-shots.

In this case, the error message appears to say
> DPUB test 36000000
(6 zeroes: 36 million)
> out of range 0-3600000
(5 zeroes: 3.6 million)

These are milliseconds. The default is 1 hour: 3600 seconds or 3.6 million milliseconds. You can specify the `--max-req-timeout` flag when starting nsqd to set a non-default limit.

**Comment by yunnian** [comment]
I got it. than you very much!
